### ISSUE TITLE
2.2.0.1 Importance of Data Exploration

### ISSUE THREAD

**Issue by kwright76** [mschermann/data_viz_reader#1034]
Since data exploration is so prevalent in the class it must be just as important to mention as a topic in the book. I think the best spot for this is in the introduction as a preface to add context on the process of creating good viz's.

**Comment by mschermann** [comment]
Good Idea. How would you structure this content? What would be your source material. Why not a separate chapter on it?

**Comment by kwright76** [comment]
This should just be a brief explanation of some data exploration techniques like we used in our projects. I will use articles and journals to validate the importance and key points of data exploration. This can probably expanded to a full chapter as I gather people to contribute to the topic.
