### ISSUE TITLE
	Consolidation Needed for section 2.6.4 & 3.6.2 ('Infographics vs Data Visualization')

### ISSUE THREAD

**Issue by mayjai** [mschermann/data_viz_reader#1072]
https://github.com/mschermann/data_viz_reader/blob/6ac4aef742749773d8ec0eb297282739e8173725/01-intro.Rmd#L304-L333

### Content Proposal:
The two subsections are basically similar. I think the topic makes more sense in Chapter 3, where it compares data visualization and other different techniques. Section 2.6.4 is a subsection of Additional Resources, and is following after a lot of resources, which does not make sense.
However, the formatting in section 2.6.4 is more understandable, and I've also added a comparison table in section 2.6.4 earlier. So I think we should move the more detailed content in section 2.6.4 to section 3.6.2, and delete the current section 3.6.2.

**Comment by syragrg** [comment]
Hey May, I think the topic should stay in Chapter 3 as well. 3.6.2 is lacking the comparison table and everything else seems to be similar apart from the formatting and the third paragraph, which I feel is a little out of place/context.
