### ISSUE TITLE
Adding more actionable guidelines for 5.2.3 Color

### ISSUE THREAD

**Issue by JinjinJanelle** [mschermann/data_viz_reader#1087]
Chapter 5.2.3 talks about rules and tips for using colors in visualizations. But the content is very general and the content of the paragraph is sparse and not well structured. It is better to categorize the paragraph into several aspects and add corresponding actionable guidelines.

1. Number of colors: Do not use more than 6 colors in a single layout. Too many colors do not help readers distinguish categories easily, instead, readers will be confused. If more than six colors are needed, we should consider using another type of chart or categorize groups together (Rost, 2018).

![image](https://user-images.githubusercontent.com/49166499/56785095-98b72800-67c1-11e9-8677-64dc46fdcb6c.png)
(Rost, 2018) 

2. Use intuitive colors: Match the content of a color with the meaning in readers' culture. For example, green for forest and blue for lake, and red for Repulicans and blue for Democrats. But do avoid stereotypical colors, such as pink for women and blue for men.

3. Color gradients: When using color gradients, use light colors as low values and dark colors as high values. People associate darker colors with density and density with great numbers. Thus, on the two sides of a color gradient should be a light color and a dark color and the bigger the color difference is, the more effective the visual is (Wilson, 2017).  

Useful links: https://www.dataquest.io/blog/what-to-consider-when-choosing-colors-for-data-visualization/; https://towardsdatascience.com/viz-palette-for-data-visualization-color-8e678d996077

**Comment by VikitaNayak** [comment]
This is a good point. Color gradient is important to make the graph easy to understand for the audience

**Comment by mschermann** [comment]
@JinjinJanelle What is your plan for moving forward?

**Comment by mschermann** [comment]
@JinjinJanelle Can we close this?

**Comment by JinjinJanelle** [comment]
Updated in the reader already.
