### ISSUE TITLE
Content Proposal for Chapter 5: Patterns - enriching content about using layer in visualizations

### ISSUE THREAD

**Issue by jacksonh2** [mschermann/data_viz_reader#1106]
Layering/layers play an crucial role in the entire data visualization concept; when done well, layers can help the visualization creator include more contexts in the visualization, add more depth to the visualization while not overflowing the visualization with unnecessarily massive information. However, if done improperly, then it becomes too complex for the audience and the message will often be lost through the process.

Therefore, I believe that the reader should have a bigger section on explaining how to use layers in data visualization properly, with some visual examples and more in-depth explanation on the pros and cons, rather than just having a simple paragraph like this:
![image](https://user-images.githubusercontent.com/41307867/56845144-6bc24e00-6871-11e9-8453-ae1f0c764086.png)

Some useful links to contents and graphs about layering are listed below:
https://medium.com/accurat-studio/the-architecture-of-a-data-visualization-470b807799b4
https://www.oracle.com/solutions/business-analytics/data-visualization/geo-layers.html

This is just something to based on, as I will add in more specific content and the specific graphs(cases) that I think would be the best to include to help explain the benefits of layering.

**Comment by jymhe120** [comment]
Thanks for sharing, Jackson. The Oracle Analytics Library link seems interesting and the 
Accurat studio link definitely demonstrates how much depth we can dive with layering. Since you have already committed the content into the reader, I will close this issue.
