### ISSUE TITLE
Content Proposal for 6.8:  Rearrange the content and add more examples and graphs

### ISSUE THREAD

**Issue by pragyansharma24** [mschermann/data_viz_reader#1108]
We should add more examples of what are visual lies and how they have been used to convince the audience.  
**ADDITION:**
1. Add examples for 6.8.7 from the link below:
https://www.learningsolutionsmag.com/articles/misleading-data-visualizations-can-confuse-deceive-learners
https://www.forbes.com/sites/naomirobbins/2012/02/28/misleading-graphs-displaying-a-change-in-one-variable-using-area-or-volume/#4392dbb71781

**RESTRUCTURING:** 
2. Remove the link below as it is not working
https://github.com/mschermann/data_viz_reader/blob/6ac4aef742749773d8ec0eb297282739e8173725/05-ethics.Rmd#L198
3.  Restructure the content for the link below. 
https://github.com/mschermann/data_viz_reader/blob/6ac4aef742749773d8ec0eb297282739e8173725/05-ethics.Rmd#L177
4. Last 2 paragraphs are not part of section 6.8.8 but that is unclear.
Either move that portion to the section conclusion or create a new heading

**Comment by pragyansharma24** [comment]
Hi Vidya,
I noticed that you are also working on Chapter 6: Ethics. 
@Vidya313 : Would you be interested in collaborating for this one? Let me know. Thanks.

**Comment by Vidya313** [comment]
Yes Pragyan , I will collaborate in restructuring the Ethics chapter.
