### ISSUE TITLE
2.2.2 and 2.2.6 has the same paragraph

### ISSUE THREAD

**Issue by syragrg** [mschermann/data_viz_reader#1118]
under Understanding Concepts that are Difficult to Contextualize 2.2.2
https://github.com/mschermann/data_viz_reader/blob/6ac4aef742749773d8ec0eb297282739e8173725/01-intro.Rmd#L67

https://github.com/mschermann/data_viz_reader/blob/db3b43077671d7816bf3ac6445a03ffe5b946acf/01-intro.Rmd#L100-L102

reuse of paragraph.

**Comment by kthang** [comment]
I have addressed this in my newest pull request
