### ISSUE TITLE
Content proposal for Chapter3 - Section 3.1 - Design Principles

### ISSUE THREAD

**Issue by AayushiVAgrawal** [mschermann/data_viz_reader#1126]
**I think we can add the following content in section 3.1**
The role of data visualization in communicating the complex insights hidden inside data is vital. This is becoming more and more important since the audience for data visualizations is also expanding along with the size of data. Data visualizations are now consumed by people from all sorts of professional backgrounds. For the same reason, the ease of consumption is now a hot topic. While data scientists and analysts have an eye for digging out the key insights from even complex visualizations, a top business stakeholder or an average person might not be able to do the same.

And this is what makes effective data visualization the need of the hour. Communicating the data effectively is an art. However, many data scientists lag behind when it comes to the design and aesthetic aspects of visualizing data.

Here are some of the key design principles for creating beautiful and effective data visualizations for everyone.
Reference - https://www.promptcloud.com/blog/design-principles-for-effective-data-visualization/

**Comment by strivedi2** [comment]
If the issue has been addressed in PR #1139 then it can be closed.
