### ISSUE TITLE
Content Proposal for Case Studies 

### ISSUE THREAD

**Issue by kthang** [mschermann/data_viz_reader#1128]
I would like a Case Study that discusses Beauty vs Functionality when making visualizations.  

I found an interesting article that discusses this very issue 

https://www.infoworld.com/article/3048315/the-inevitability-of-data-visualization-criticism.html

My proposal is that I add a case study that addresses this topic using the article

**Comment by kthang** [comment]
This is a rough first draft of the new case study:

Andy Cotgreave is the current Senior Technical Evangelist at Tableau.  In the linked article he defends the use of elaborate visualizations and argues that beauty is a quality worth pursuing when making data visualizations.  In particular, he is interested in tackling the common criticism of “it would have been better as a line chart."  

One visualization that he focuses on is a work that shows the effect of introducing vaccines on the number of polio cases in the US made by the Wall Street Journal.  Cotgreave contrasts the colorful heatmap, which is harder to parse, and a linegraph that is plain, but easy to understand.  

In his article, Cotgreave argues that the heatmap was visually striking, and its novelty made him more likely to interact with it.  He later asks the reader whether or not the line version would have won awards, or been virally shared as the heatmap was.  While Cotgreave acknowledges the readability of the line graph, he ultimately feels that there is a place for visualizations to be beautiful.

**Comment by kthang** [comment]
This content is currently in pull request #1176.

**Comment by bharatimalik** [comment]
This is a great addition to the reader!

**Comment by preranap1** [comment]
Hey Kevin! I really like this as a part of the case studies. We have had many discussions in class as to why visualizations should be simple and easy to understand. It is really clever to add a case study that argues otherwise since it helps us understand the pros and cons of both arguments. thank you for this addition. Let me know if you need any help with this one.

**Comment by jymhe120** [comment]
Since this content is already in a pull request and got approved. I think we may close this issue. Nicely done, Kevin!

**Comment by kthang** [comment]
I'm going to close this issue.  Thanks for the feedback everyone.
