### ISSUE TITLE
Content Proposal for Chapter 3 (Section 3.2.2) - Choosing best form of Visualization 

### ISSUE THREAD

**Issue by Psharma2193** [mschermann/data_viz_reader#1133]
**Analysis Agenda**
While going through the reader’s chapters, we observed that section 3.2 has a very brief content on Best Practices. We think this section can be explained better with more details on chart selection for various analysis problems in data visualization. 
More valuable content can be added to the Section 3.2.2 that elaborates on how to choose the best form of visualization and evaluating them. We propose to include content on some of the most commonly used analysis types and which chart types are most suitable for them. With this addition we would like to include tips on handling such analysis. 

**Visualization is extensively used for below types of analysis - **
1. Trends over Time
2. Comparison and Ranking
3. Correlation
4. Part to Whole
5. Geographical Data

Adding chart suggestion on presenting such data ideally will be informative for readers.

**References:**

http://www.dataplusscience.com/files/visual-analysis-guidebook.pdf

https://www.methodspace.com/tips-on-interpreting-data-visualizations/

**Comment by bharatimalik** [comment]
I loved this content proposal. It will definitely enhance the reader!

**Comment by rlwy** [comment]
@Psharma2193 was this issue resolved in PR #1169 and #1174 ? Can we close the issue?

**Comment by strivedi2** [comment]
I can see parts 1- 4 on the reader. Not sure about 5. Geographical data- is this complete? If yes, then the issue can be closed. If no, part 5 can be added next week.

**Comment by VikitaNayak** [comment]
Yes, we can add it next week.

**Comment by VikitaNayak** [comment]
@rlwy This is not completed yet. We are still working on this issue. I think we will be close it next week.

**Comment by strivedi2** [comment]
Completed in PR #1240 hence closing issue
