### ISSUE TITLE
Content Proposal for 5.8 Word Cloud

### ISSUE THREAD

**Issue by AjayDeshmukh14** [mschermann/data_viz_reader#1134]
I feel that Tableau is a widely used platform and thus we should also include the content of how to create a word cloud in Tableau. Thus I feel we should add this content to the topic 'Word Cloud'
Creating a word cloud in Tableau is quite straight forward you will need the Tableau Desktop application or a Tableau Online account for the same. To generate a word cloud in Tableau, open Tableau Desktop and connect it to the desired data source. Drag the desired dimension to Text on the Marks card. Then drag the same dimension to Size on the Marks card. Now right-click on the dimension on the Size card and select Measure from Count. If needed, change the Mark type from Automatic to Text. To add color, drag the same dimension to Color on the Marks card.

Reference: https://kb.tableau.com/articles/howto/creating-a-word-cloud

**Comment by bharatimalik** [comment]
I think we can close this issue now, as the pull request has been approved and merged.
