### ISSUE TITLE
Content Proposal for chapter 3 - style guides

### ISSUE THREAD

**Issue by harizhisham** [mschermann/data_viz_reader#1136]
Given that most of us come from a Python/R background, we're quite used to referring to documentation and style guides to creating our charts and visualizations. 

I would like to propose a section in Chapter 3 of the reader to include general guidelines and links for teams to develop a general style template that is of high quality and easily reproducible. Rather than fidgeting around in Tableau for the sake of hoping to make a pretty chart, students would go into projects with a good idea of what the end chart should look like in terms of design. 

[This](https://medium.com/@traffordDataLab/developing-a-data-visualisation-style-cd24f88fa59) by Trafford Data Lab outlines how their team makes style templates in R. Note that they have developed a nice API to easily format charts in their template style.

Furthermore, [FiveThirtyEight](https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/FiveThirtyEights-data-journalism-workflow-with-R) talks about their general visualization-making workflow and mentions that they too have developed their own template. 

Action Items:
- Add subsection outlining how we can develop style templates to make visualization workflow more efficient.

References
Data Lab, Trafford. 'Developing a data visualisation style', 23 October 2017. https://medium.com/@traffordDataLab/developing-a-data-visualisation-style-cd24f88fa59

Flowers, Andrew. ‘FiveThirtyEight’s Data Journalism Workflow with R’, useR! 2016 international R User conference, 15 June 2016. https://channel9.msdn.com/Events/useR-international-R-User-conference/useR2016/FiveThirtyEights-data-journalism-workflow-with-R

**Comment by preranap1** [comment]
Interesting! Would love to see how this pans out!

**Comment by bharatimalik** [comment]
This will be a good addition to the reader! Good fine!

**Comment by XZou0803** [comment]
I like this new part! Very useful!
