### ISSUE TITLE
Fix text alignment for image source caption in Section 3.2.2.1

### ISSUE THREAD

**Issue by rlwy** [mschermann/data_viz_reader#1194]
https://github.com/mschermann/data_viz_reader/blob/5a7706c82062b8ce7b07c40269b91762cd9cb1c1/02-fundamentals.Rmd#L216-L222

Move caption to a new line below their respective charts.

**Comment by harizhisham** [comment]
was this change merged to contributions?

**Comment by rlwy** [comment]
> was this change merged to contributions?

Just did it, will close the issue now.
