### ISSUE TITLE
Content Proposal to enhance Chapter 7: Conclusion - Phase-2

### ISSUE THREAD

**Issue by srivasud** [mschermann/data_viz_reader#1196]
1. Fix alignment issues  and bullet formatting issues in section 7.1
2. Add and refine contents in section 7.1

**Comment by harizhisham** [comment]
https://github.com/mschermann/data_viz_reader/blob/5a7706c82062b8ce7b07c40269b91762cd9cb1c1/06-conclusion.Rmd#L20

Does anyone have a link to the referenced study?

**Comment by Kushall-Dayal** [comment]
1.Formatting Section 7.2
2.Adding additional content  for Section 7.2
Pull Request #1196

**Comment by srivasud** [comment]
@harizhisham 
I found the below links may be useful for you.
1) https://home.kpmg/content/dam/kpmg/pdf/2015/10/Going_beyond_the_%20data_Turning_Insights_Into_Value_2016-04-21%2022-22-44.pdf

2) https://assets.kpmg/content/dam/kpmg/pdf/2015/04/going-beyond-data-and-analytics-v4.pdf

**Comment by Marvin510** [comment]
Fixing issues in 7.2 and adding additional resources.
Pull request #1222

**Comment by harizhisham** [comment]
added source to KPMG study in 7.1
Pull request #1223
