### ISSUE TITLE
Data Viz Project - Addition of Application of Data Visualization in Reader

### ISSUE THREAD

**Issue by VikitaNayak** [mschermann/data_viz_reader#1224]
I wanted to add some content here to explain the application of data visualization. One of the application is in the field of Marketing.

**Comment by VikitaNayak** [comment]
https://trendemon.com/blog/why-data-visualization-is-key-in-content-marketing-analytics/

**Comment by mschermann** [comment]
@VikitaNayak What is your plan for moving forward?

**Comment by VikitaNayak** [comment]
I want to add content on application of data visualization on various
fields.one of them I mentioned is marketing..other fields include customer
experience industry, CRM etc.

**Comment by VikitaNayak** [comment]
**Content Proposal** 

Just to reiterate that we plan to add include content on types of data viz projects across the application of data viz in industries such as Marketing, CRM, CX, and relevant case studies.

**Comment by VikitaNayak** [comment]
Closing this out as it is overlapping with our new issue for this week.
