### ISSUE TITLE
Introduction of the general Data Viz Project Chapter

### ISSUE THREAD

**Issue by kwright76** [mschermann/data_viz_reader#1229]
Explain how a data viz project idea is from
- use case examples
- needs
- what insights to find
Answer the who, what, when, and how.

**Comment by rlwy** [comment]
Found a website that has some good points for this topic: https://learning.oreilly.com/library/view/visualizing-data/9780596514556/ch01.html

**Comment by strivedi2** [comment]
> Found a website that has some good points for this topic: https://learning.oreilly.com/library/view/visualizing-data/9780596514556/ch01.html

This is a great find! It gives great detail about the important pre-requisites for the data viz project.

**Comment by strivedi2** [comment]
Here is another useful link on potential pitfalls/ reasons that could lead to project failures for a data viz project:
https://towardsdatascience.com/6-reasons-why-data-visualisation-projects-fail-1ea7a56d7602

This can be a useful addition to the introduction through shared learning from others' experiences. For any project, it is important not only to identify goals and objectives, but also learn about what did not work and potential pitfalls that one can look out for to prevent repeating the same mistakes that were done in the past.

**Comment by strivedi2** [comment]
During my search for types of visualizations, I also found this link that I believe can be a useful addition to the introduction:
https://www.oreilly.com/library/view/designing-data-visualizations/9781449314774/ch01.html

It talks about data visualization in terms of 'Informative versus Persuasive versus Visual Art'- something that we often discuss in class and see in many visualization examples. I believe 
understanding the nature of a visualization in a project using the framework highlighted in this link is a great starting point.

**Comment by syragrg** [comment]
https://datajournalismhandbook.org/1.0/en/understanding_data_7.html

this article addresses the how portion of finding insights from data visualization that we can possibly use! It mentions that in order to make the finding of insights in data more effective, the following process is very important: 1. Visualize 2. Analyse/interpret what you see 3. Documenting your Insights and steps 4. Transform datasets (to explore more patterns and different findings)
