### ISSUE TITLE
Important prerequisites of a data viz project

### ISSUE THREAD

**Issue by srivasud** [mschermann/data_viz_reader#1231]
Few important prerequisites are listed below:
- Clarifying the purpose of your project. Why are we doing this project? What is the purpose of this project (Understanding the end deliverable)?
- Understanding the scope of this project.
- Understanding the audience.
- Understanding the data.

**Comment by rtamhankar** [comment]
The detailed information on the above prerequisites would be a great addition! I found the below link for the second prerequisite 'Understanding the audience'. I hope it helps!
https://www.techchange.org/2015/05/21/audience-matters-in-data-visualization/

**Comment by Kushall-Dayal** [comment]
Few **Success** factor for a data viz project:
- Selecting the right type visualization which suites the purpose
- Should be simple,readable and understandable such that the take away lasts long
- Designed such that it is pleasing to the eyes ,is interesting and keeps the audience engaged
- Repeating and iterating through several revision results in an elegant visualization
 
One can find the aforementioned factors detailed in the link below:
- https://www.e-nor.com/blog/data-visualization/makes-good-visualization

**Comment by Qing0608** [comment]
How to structure a data viz project:
1.      Bring big data visualization up front
2.      Connect time and space
3.      Visualize the voice of the employee
4.      Map data visualization to the real world
5.      Improve supply chain management
6.      Identify workflow bottlenecks

reference:
https://searchbusinessanalytics.techtarget.com/tip/6-big-data-visualization-project-ideas-and-tools

**Comment by Marvin510** [comment]
I got this information from Hitachi. They have a start guide on prerequisites for a data visualization project.
1 - Define the project - objectives, core KPIs
2- Data visualization Selection - identify metrics 
3- Dashboard Layout and Design - best practices 
4- User interaction -  what to consider such as filters  drill down capabilities etc.

https://www.hitachivantara.com/en-us/pdf/white-paper/data-visualization-dashboard-projects-quickstart-guide-whitepaper.pdf

**Comment by harizhisham** [comment]
This article I found on Medium addresses the topic from a data science perspective, but since data visualization is a subset of DS, I think it's relevant. Additionally, the article lays out the fundamentals of a DS project very broadly and can be adapted to creating visualizations.

In summary (main points taken from the article:
- Understand the problem that needs to be addressed and solved
- Assess the situation with respect to the problem
- Understand the potential risks and benefits of the project
- Define a success criteria (or metric) to assess the project

This article might fit in nicely with understanding the purpose of a project. The article also mentions being empathetic a lot - so in addition to understanding the audience, it is also important to understand who your key stakeholders are, and how your project might help solve their problem.

Article: https://towardsdatascience.com/how-to-ask-the-right-questions-as-a-data-scientist-913621907411

**Comment by harizhisham** [comment]
@Kushall-Dayal brought up some great points over at #1238. We can utilize some of the source material and pointers he brought up in the overall chapter we're building.

**Comment by harizhisham** [comment]
Wanted to add this for reference down the pipeline. It has some very good pointers on the 7 stages of a data viz project:

https://www.oreilly.com/library/view/visualizing-data/9780596514556/ch01.html

**Comment by srivasud** [comment]
First Version (Week-8):
============
We set the layout defining the pre-requisites:

+ Clarifying the purpose of your project. Why are we doing this project? What is the purpose of this project (Understanding the end deliverable)?
+ Understanding the scope of this project.
+ Understanding the audience.
+ Understanding the data.

What's left for next week? (week-9):
====================
+ Add "Define a success criteria (or metric) to assess the project". 
+ Refine the contents around the above topics (defining the goal, understanding audience and data)

**Comment by gauravhassija** [comment]
Great material guys, we in issue #1286 referred this interesting article for identifying important prerequisites
https://www.crazyegg.com/blog/leverage-marketing-with-data-visualizations/

Along with points on 'Understanding your Audience', it talks about the importance of knowing the different data visualizations(line chart, bar chart, etc.) and when to use them.

**Comment by harizhisham** [comment]
We should use some of the material in #1238 to draft out "define a success criteria (or metric) to assess the project" for next week! I like this bit referenced from the O'Reilly link above:

> Visualizing data is just like any other type of communication: success is defined by your audience’s ability to pick up on, and be excited about, your insight.

Hopefully this gives some idea as to how we can write out this section.

My only concern would be where should we insert this section? At the beginning or end of the chapter?

**Comment by srivasud** [comment]
On May 30th: (Week#9)
After reviewing the topcis included in the chapter, I found that there is a separate chapter for "Success criteria". So we will only address any bugs related to "Pre-requisites of data viz project"
Found few issues related to not correctly formatting to "Bold" and we will talk a bit about KPIs as part of project goals.

**Comment by VikitaNayak** [comment]
@srivasud did you resolve this problem?

**Comment by srivasud** [comment]
Week-9
=======
1. We addressed formatting issues, rephrased few sentences to correct grammatical issues in "Important Pre-requisites"
2. Re-organized the contents as subsections.
3. Added KPI examples.

**Comment by srivasud** [comment]
Closing this issue as we resolved all of the above issues!

**Comment by Kushall-Dayal** [comment]
Added some tips on choosing colors for visualization as prerequisite
Pull Request #1388
