### ISSUE TITLE
Tools for Data Visualization Projects

### ISSUE THREAD

**Issue by XZou0803** [mschermann/data_viz_reader#1232]
For the Sub-chapter-- How to structure a data viz project, there is a useful resource to start. 
This part should include:
1. Tools for FOR NON-DEVELOPERS
2. FOR COMPLEX PROJECTS
3. FOR MAPPING AND INTERACTIVITY

The resource is here: https://www.upwork.com/hiring/data/19-data-visualization-tools/

We can work together to enrich this part!

**Comment by 82817** [comment]
I like this idea, and the reference helps a lot too. I found an article that talks about this topic as well.

https://venngage.com/blog/data-visualization-tips-content-strategy/

I've only skimmed through some parts but it talks about planning, tools, audience, understanding data, etc. Which reinforce the topic of "How to structure a data viz project"

**Comment by Cindyli0310** [comment]
@82817 Hi Jason,
The idea of working on planning part is great. However, do you mean we should know some prerequisite requirements before really doing the data visualization project?

**Comment by Cindyli0310** [comment]
I also find two useful sources related to data visualization project:
The first one is '11 design tips for data visualization':
https://www.dataquest.io/blog/design-tips-for-data-viz/
The second one is '35 useful visualization tools' such as Tableau, Chart Studio which can help to build ideal visualization:
https://www.creativebloq.com/design-tools/data-visualization-712402

**Comment by 82817** [comment]
@Cindyli0310 What I mean by planning is that before you start doing visualization, you should understand your data, your audience, know how to use your tools, etc.

**Comment by jma4** [comment]
I found this website for improving data visualization design. It's not necessary to build fancy and complex graphics, there are few simple things could do to massively improve how the visualizations look and how people interpret it. I think it would better support the contents for the non-developers part.
[25 Tips to Instantly Improve Your Data Visualization Design](https://www.columnfivemedia.com/25-tips-to-upgrade-your-data-visualization-design)

**Comment by XZou0803** [comment]
Yes, I agree! We can summarize the tips and then combine them with tools to contribute to "How to structure a data viz project!

**Comment by Cindyli0310** [comment]
> @Cindyli0310 What I mean by planning is that before you start doing visualization, you should understand your data, your audience, know how to use your tools, etc.

@82817 Hi Jason,
I really like your idea, the exploration part is very important. However, because we need to define building a data viz project, I think it is better to give a complete idea of the project.

**Comment by XZou0803** [comment]
This issue has been solved
