### ISSUE TITLE
Success Factors for a Data Visualization

### ISSUE THREAD

**Issue by Kushall-Dayal** [mschermann/data_viz_reader#1238]
Few **Success** factors for a data viz project are:
- Selecting the right type visualization which suites the purpose.The link provided discusses this in detail:
https://www.datalabsagency.com/2014/12/22/15-most-common-types-of-data-visualisation/

- Should be simple,readable and understandable such that the take away lasts long

- Designed such that it is pleasing to the eyes ,is interesting and keeps the audience engaged.More on that here:
https://www.dataquest.io/blog/what-to-consider-when-choosing-colors-for-data-visualization/

- Repeating and iterating through several revision results in an elegant visualization

**Comment by harizhisham** [comment]
This looks good - we could potentially use some of these as a way to determine if a project helps accomplish an end goal. 

Specifically, these points you brought up have to do with understanding who your audience and stakeholders are to ensure a successful project. 

I'll refer this issue to our main thread over at #1231

**Comment by Marvin510** [comment]
Kushall- I would like to add what the Harvard Business Review has to say about success factors for Data Visualizations: https://hbr.org/2013/04/the-three-elements-of-successf

It emphasizes the importance of understanding your audience. How will they read or interpret the information. Do they process the knowledge to understand the viz or will they need clues and guidance to interpret? Do they have any expectations?  can the audience take actions with your viz?

You also need to set up a clear framework.  For example when using an icon it should resemble the item it represents.

It should also tell a story. After all you are trying to inform or persuade the audience of an idea or topic.

**Comment by Kushall-Dayal** [comment]
Points Discussed in this issue are in some form already added in Ch 6

+ Selecting the right type visualization:
https://github.com/mschermann/data_viz_reader/blob/670e2582620adbc83086a5b018abdeae1293685d/06-process.Rmd#L207
to
https://github.com/mschermann/data_viz_reader/blob/670e2582620adbc83086a5b018abdeae1293685d/06-process.Rmd#L212

+ Design such that it is pleasing to the eyes:
 discussed in the pull request  #1388 

As the case that @Marvin510 shared with me also has points that has already been discussed 
+ It understands the audience.:https://github.com/mschermann/data_viz_reader/blob/670e2582620adbc83086a5b018abdeae1293685d/06-process.Rmd#L25
+ It tells a story:
