### ISSUE TITLE
Types of Data Viz Projects - Best Practices & Industry Applications

### ISSUE THREAD

**Issue by agrasonal** [mschermann/data_viz_reader#1242]
The topics we will cover as a part of “Types of Data Visualizations’ for the reader:

**1.     Life-Cycle of a Data Visualization Project**
We will outline the process and the steps data analysts can undertake while working on a data visualization project. This can act as a guideline for any future data analysis and visualization projects we undertake. We will break this further into the following steps:
— Step 1: Understanding the Business Issues
— Step 2: Understanding Your Data Set
— Step 3: Data Preparation
— Step 4: Exploratory Analysis/ Modeling
— Step 5: Validation
— Step 6: Visualization and Presentation

(Ref: https://www.northeastern.edu/graduate/blog/data-analysis-project-lifecycle/)

**2.     How to decide what type of visualization to use:**
Here our attempt will be to understand how to choose the right kind of visualization for the data at hand. This is imperative because choosing the wrong visual or using a default chart can cause confusion to the reader sometimes even leading to misinterpretation. 

(Ref: https://blog.hubspot.com/marketing/types-of-graphs-for-data-visualization)
(Ref: https://visme.co/blog/types-of-graphs/#business)
(Ref: https://dzone.com/articles/top-10-industries-benefiting-from-big-data-and-ana)

**3.    Visualizations relevant to different industries**
In order to give you a clearer idea of how data insights and predictive analytics are actually changing industries, we will begin by exploring certain best practices for visualizations for different industries. We will also understand the impact of data visualization on different industries.

(Ref: https://flowingdata.com/2018/12/27/best-data-visualization-projects-of-2018/)
(Ref: https://www.mibar.net/blog/why-data-visualization-is-a-necessity-for-modern-businesses/

**Comment by preranap1** [comment]
looking forward to working on this.

**Comment by preranap1** [comment]
Hey guys, We can also use this link to explain how to decide the right type of visualization.

https://www.datapine.com/blog/how-to-choose-the-right-data-visualization-types/

**Comment by shriya22** [comment]
Looking forward to working on  the reader!! 
We can also take a look at this link which helps in picking the appropriate data vizualization tools based on specific requirements:
https://www.upwork.com/hiring/data/19-data-visualization-tools/

**Comment by pragyansharma24** [comment]
Thank you Sonal for collaborating all the ideas. 
We can also add some content from this link. It has the graphs specific for engineering. 
https://visme.co/blog/types-of-graphs/#engineering
This has some nice and interactive visualizations. 
https://www.webdesignerdepot.com/2009/06/50-great-examples-of-data-visualization/

Fancy charts :)

**Comment by bharatimalik** [comment]
Thank you all for sharing some of the amazing resources for this project.

One more addition could be to know when does data visualization project fails so that we can be well prepared. 
https://towardsdatascience.com/6-reasons-why-data-visualisation-projects-fail-1ea7a56d7602
https://searchbusinessanalytics.techtarget.com/feature/Data-visualization-tools-may-be-glamorous-but-focus-on-business-value
https://www.iotforall.com/data-visualization-strategy-for-business/

[This](https://www.blastam.com/blog/data-visualization-techniques-agile-process) article which tells you how an agile process can be an effective visualization technique could be another great addition!

**Comment by bharatimalik** [comment]
We can also use the article about [35 incredible data viz tools](https://www.creativebloq.com/design-tools/data-visualization-712402) that would be helpful for step 6 of life cycle of a data visualization project

**Comment by strivedi2** [comment]
> Thank you all for sharing some of the amazing resources for this project.
> 
> [This](https://www.blastam.com/blog/data-visualization-techniques-agile-process) article which tells you how an agile process can be an effective visualization technique could be another great addition!
> 
> Another addition could be to know when does data visualization project fails so that we can be well prepared.
> 
> 1. [6 reasons why data viz project fails](https://towardsdatascience.com/6-reasons-why-data-visualisation-projects-fail-1ea7a56d7602)
> 2. [Focus on business value for successful data viz project](https://searchbusinessanalytics.techtarget.com/feature/Data-visualization-tools-may-be-glamorous-but-focus-on-business-value)
> 3. [Data viz strategy for business](https://www.iotforall.com/data-visualization-strategy-for-business/)

These are wonderful resources. We in #1229 are also planning to use the reasons for data viz project failures as important learnings to be kept in mind when starting a data viz project.

**Comment by bharatimalik** [comment]
> > Thank you all for sharing some of the amazing resources for this project.
> > [This](https://www.blastam.com/blog/data-visualization-techniques-agile-process) article which tells you how an agile process can be an effective visualization technique could be another great addition!
> > Another addition could be to know when does data visualization project fails so that we can be well prepared.
> > 
> > 1. [6 reasons why data viz project fails](https://towardsdatascience.com/6-reasons-why-data-visualisation-projects-fail-1ea7a56d7602)
> > 2. [Focus on business value for successful data viz project](https://searchbusinessanalytics.techtarget.com/feature/Data-visualization-tools-may-be-glamorous-but-focus-on-business-value)
> > 3. [Data viz strategy for business](https://www.iotforall.com/data-visualization-strategy-for-business/)
> 
> These are wonderful resources. We in #1229 are also planning to use the reasons for data viz project failures as important learnings to be kept in mind when starting a data viz project.

Ahh! Thanks for letting us know. This could have been one of the closing notes for life cycle of a data visualization project. So when we reach that section in our proposal in the coming weeks we can collaborate for this particular topic!

**Comment by bharatimalik** [comment]
Following are some of the interesting resources which can help decide what type of visualization to use:
1. [Data Viz Catalogue](https://datavizcatalogue.com/)
2. [Viz Types](https://guides.library.duke.edu/datavis/vis_types)
3. [Data Viz Project](https://datavizproject.com/)

**Comment by agrasonal** [comment]
All the promised deliverables have been implemented. Therefore, we are closing this issue.
