### ISSUE TITLE
Week 7 How to run data viz project: how to structure

### ISSUE THREAD

**Issue by kthang** [mschermann/data_viz_reader#1246]
This issue will be writing a section about **How to Structure a Data Viz Project**.

The outline and references will be posted below.  

@mayjai , @btamsir , @ttussing

**Comment by kthang** [comment]
Structuring Your Final Deliverable:

i. Hook Audience on Key Message 
  a. Biggest Takeaway 
  b. What is your Headline?
ii, Background and Context
  a. Define Problem/historical background
  b. Author context
iii. Key Findings
  a. Arguments
  b. Anticipate Responses
  c. Logical Flow
iv. Conclusion
  a. Takeaways
  b. Thoughts on the Future
  c. How to improve your presentation
  d. References

**Comment by btamsir** [comment]
https://ieeexplore.ieee.org/document/6634103
Borkin et all is a great reference for how to structure a data visualization project. He outlines what to focus on with respect to the audience, chart type, chart attributes, and more.

**Comment by mayjai** [comment]
https://hbr.org/2013/03/when-data-visualization-works-and

**Comment by btamsir** [comment]
For instance, 

In Borkin et al:
    Borkin et al has a section on memorability and how to make a visualization memorable. We can 
expand his findings on our outline sections "Hook the audience on key message" and "Key Findings."

**Comment by mayjai** [comment]
I found some articles that go well under the "Conclusion" section:
Subsection - Takeaways:
https://hbr.org/2013/03/the-question-all-smart-visualizations

Subsection - Thoughts on the Future:
https://hbr.org/2016/06/visualizations-that-really-work?referral=03758&cm_vc=rr_item_page.top_right

Subsection - How to improve your presentation:
https://hbr.org/2013/03/when-data-visualization-works-and

**Comment by ttussing** [comment]
Case Studies:
NYT Article studying Success of White and Black boys who grew up in wealthy households:
[Extensive Data Shows Punishing
Reach of Racism for Black Boys](https://www.nytimes.com/interactive/2018/03/19/upshot/race-class-white-and-black-men.html)
Success: Hook Audience on Key Message, Background and Context, Define Problem/historical background, Author context, Key Findings, Arguments, Anticipate Responses, Logical Flow, References
Falls: No clear conclusion, no specific Thoughts on the Future, no reference on How to improve your presentation
---
NYT article of future success based on development years:
[The Best and Worst Places to Grow Up: How Your Area Compares](https://www.nytimes.com/interactive/2015/05/03/upshot/the-best-and-worst-places-to-grow-up-how-your-area-compares.html?action=click&contentCollection=U.S.&region=Footer&module=WhatsNext&version=WhatsNext&contentID=WhatsNext&moduleDetail=undefined&pgtype=Multimedia)
Success: Hook Audience on Key Message, Background and Context, Define Problem/historical background, Author context, Key Findings, Arguments, References
Falls: Does not Anticipate Responses, No clear conclusion, no specific Thoughts on the Future, no reference on How to improve your presentation

**Comment by ttussing** [comment]
I used a NYT article on [Geography Matters](https://www.nytimes.com/interactive/2016/04/11/upshot/for-the-poor-geography-is-life-and-death.html) which provided excellent examples of background and context on life expectancy and why they chose the data

**Comment by mayjai** [comment]
I used a Harvard Business Review [article](https://hbr.org/2013/03/the-question-all-smart-visualizations), which talks about the importance of the takeaways, and this [article](https://www.gooddata.com/blog/8-ways-turn-good-data-great-visualizations) for some great tips, as well as an [article](https://libguides.mit.edu/citing)  form MIT Libraries that talk about reference.

**Comment by btamsir** [comment]
Great! The first version is done and now this issue can be closed.
