### ISSUE TITLE
Content Proposal for How to run a Data Viz Project 

### ISSUE THREAD

**Issue by Psharma2193** [mschermann/data_viz_reader#1247]
For this section, our team has planned to work on Data Viz Project focusing on Marketing domain. 

- Important prerequisites: We would like to understand important mechanisms required for effective data visualization.   
- Risks and pitfalls: Identify reason for failure and how to avoid them.
- Success factors: We will also look at the metrics of interest and understand visualizations that cater to these metrics suitable for needs of investors or other CFOs.

Reference:
https://www.crazyegg.com/blog/leverage-marketing-with-data-visualizations/
https://www.tapclicks.com/best-data-visualizations/

**Comment by VikitaNayak** [comment]
I found something about risks and pitfalls here: https://www.copypress.com/blog/common-pitfall-visualization/
This explains what can go wrong in the marketing field related to data visualizations

**Comment by gauravhassija** [comment]
This looks like a great addition. Looking forward to working on finding Prerequisites for a good Data Viz project.

**Comment by VikitaNayak** [comment]
Great! We can use charts for our reader project from this link https://community.tableau.com/thread/242441

**Comment by Psharma2193** [comment]
Closing the issue as the changes are coming in right sequence and the broken images were fixed in Issue #1307
