### ISSUE TITLE
Linked Images break generation of book in PDF format

### ISSUE THREAD

**Issue by mschermann** [mschermann/data_viz_reader#1251]
https://github.com/mschermann/data_viz_reader/blob/b2608a4f001f867e03e66a3843bfcad699b4094a/04-patterns.Rmd#L103

If you include images via links, the PDF of the reader will not be generated. Explore whether you can include images directly.

**Comment by XZou0803** [comment]
I found another four pics have the same problem and created a pull request to fix them.
