### ISSUE TITLE
Reverse format for 6.7.8 and 6.7.9

### ISSUE THREAD

**Issue by XZou0803** [mschermann/data_viz_reader#1296]
I found some formatting problem in 6.7.8 and 6.7.9, so I will reverse them in the next pull request.

**Comment by jma4** [comment]
That's a good idea, so we could easily see if there are more contents could be added into paragraph.

**Comment by Cindyli0310** [comment]
@XZou0803 Hi Nina, I am totally agree with you. There are some formatting, graph and text issue need to fix.  Look forward your revising result.

**Comment by 82817** [comment]
Pull request #1297 merged. Closing issue
