### ISSUE TITLE
Unorganized format for chap 6.7.5-6.7.7 need to fix

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#1298]
Duplicate title for 6.7.5 and 6.7.6 , need to remove title for 6.7.6. On the other hand, 6.7.7 FOR NON-DEVELOPERS should be a subject for 6.7.5, not a new title. The paragraph format  is massy too. Some bullet point should be listed in a new line instead of combining all the points in one paragraph. Moreover, some graphs show be added to make the explanation clearer.
https://github.com/mschermann/data_viz_reader/blob/670e2582620adbc83086a5b018abdeae1293685d/06-process.Rmd#L296

**Comment by XZou0803** [comment]
Totally agree!

**Comment by bharatimalik** [comment]
I noticed the same!

**Comment by VikitaNayak** [comment]
@Cindyli0310 I am adding the missing content for section 6.7.5 which is Platform

**Comment by Cindyli0310** [comment]
> @Cindyli0310 I am adding the missing content for section 6.7.5 which is Platform
Hi @VikitaNayak ,thanks for adding that. Would you mind sharing the link then I can look at?

**Comment by VikitaNayak** [comment]
@Cindyli0310 I have already closed that issue

**Comment by Cindyli0310** [comment]
> @Cindyli0310 I have already closed that issue

Got it.
