### ISSUE TITLE
Section 6.1 Formating issues

### ISSUE THREAD

**Issue by rlwy** [mschermann/data_viz_reader#1304]
Formatting issues.
The list items and bold text are not rendered correctly.
https://github.com/mschermann/data_viz_reader/blob/670e2582620adbc83086a5b018abdeae1293685d/06-process.Rmd#L16-L25

**Comment by XZou0803** [comment]
Yes, I noticed that, too. Also, the last paragraph of this chapter has the same problem.
![image](https://user-images.githubusercontent.com/31682566/58725834-ffb59700-8394-11e9-914f-7aba853e20eb.png)
