### ISSUE TITLE
Most lists are not formatted correctly

### ISSUE THREAD

**Issue by rlwy** [mschermann/data_viz_reader#1306]
To fix all display of list items in the new chapter.

**Comment by mayjai** [comment]
I found a lot of wrong format lists too. It will look much better after formatting them correctly.

**Comment by rlwy** [comment]
hey @mayjai I pushed my fix to format all the list items, you can review it and see if i missed anything. Thanks!

**Comment by mayjai** [comment]
@rlwy I reviewed and approved your pull request. It looks great after the change!

**Comment by rlwy** [comment]
Thanks @mayjai !
