### ISSUE TITLE
Section 6.1 incorrect format

### ISSUE THREAD

**Issue by VikitaNayak** [mschermann/data_viz_reader#1332]
![image](https://user-images.githubusercontent.com/43161990/58753467-678edf00-8474-11e9-8c7f-1851add4c758.png)

**Comment by srivasud** [comment]
@VikitaNayak 
Just to let you know, we have addressed this issue in https://github.com/mschermann/data_viz_reader/issues/1231

**Comment by VikitaNayak** [comment]
Okay great. then I am closing this issue

**Comment by VikitaNayak** [comment]
@srivasud Can you please confirm if you are already working on it?

**Comment by srivasud** [comment]
@VikitaNayak Thanks! We have already addressed the formatting issues in section-6.1. The fixes are already in contributions branch.

**Comment by VikitaNayak** [comment]
Thanks for confirming!
