### ISSUE TITLE
Formatting required for Section - 6.8.4

### ISSUE THREAD

**Issue by Psharma2193** [mschermann/data_viz_reader#1334]
Correcting the format of list.

![image](https://user-images.githubusercontent.com/37756459/58753551-8641a580-8475-11e9-8a24-d9e4803ee6d5.png)

**Comment by mayjai** [comment]
Nice catch! I'm working on this issue now.

**Comment by btamsir** [comment]
We were about to raise an issue for this! Nice catch.

**Comment by mayjai** [comment]
This section is fixed in #1367
