### ISSUE TITLE
6.2 Inconsistant format

### ISSUE THREAD

**Issue by jymhe120** [mschermann/data_viz_reader#1353]
<img width="1131" alt="Screen Shot 2019-06-02 at 12 47 12 AM" src="https://user-images.githubusercontent.com/35418915/58758448-0d236c00-84d0-11e9-8d29-74a76a2f04d3.png">
Some of the bold titles have colon the others don't.  Need to change the format to make it consistent. Adding a colon after each title is easier to read.

**Comment by syragrg** [comment]
great catch!
