### ISSUE TITLE
6.4.1.Finding Insights from Data Visualization-Visualize need a more detailed explanation

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#1360]
In 6.4.1.Finding Insights from Data Visualization, the author explain Visualize is the first step of finding insights from Data Visualization. However, the explanation is not detailed. I will suggest to add more detailed reasons why we need visualize. 
https://github.com/mschermann/data_viz_reader/blob/670e2582620adbc83086a5b018abdeae1293685d/06-process.Rmd#L96

**Comment by btamsir** [comment]
Great idea! If the first section is ambiguous, it would be great to clarify with explanations.

**Comment by XZou0803** [comment]
This is a good idea! Looking forward to the context!

**Comment by Cindyli0310** [comment]
> Great idea! If the first section is ambiguous, it would be great to clarify with explanations.
@btamsir Thanks！

**Comment by Cindyli0310** [comment]
> This is a good idea! Looking forward to the context!

Thank you!
