### ISSUE TITLE
6.8.4-Change the format to match other parts under the subsection 

### ISSUE THREAD

**Issue by mayjai** [mschermann/data_viz_reader#1365]
https://github.com/mschermann/data_viz_reader/blob/670e2582620adbc83086a5b018abdeae1293685d/06-process.Rmd#L444-L474
The format of the parts in subsection 6.8 is mostly paragraph structures, instead of bullet points. So it will be more consistent to change the format of 6.8.4 to a paragraph.

**Comment by ttussing** [comment]
Good idea! Consistency is important here

**Comment by ttussing** [comment]
Pull request closed #1367

**Comment by mayjai** [comment]
I also improve the content.
