### ISSUE TITLE
Adding chart images for 6.7.1 - Data Visualization in Business

### ISSUE THREAD

**Issue by bharatimalik** [mschermann/data_viz_reader#1379]
Adding chart images will help the reader in better understanding.

**Comment by harizhisham** [comment]
Agreed! I think for brevity's sake, we can reference one of the charts from this bib reference: 

“44 Types of Graphs Perfect for Every Top Industry.” n.d. https://visme.co/blog/types-of-graphs/#business.

We already have it in the bib, so it would be a quick addition to the reader.

**Comment by shriya22** [comment]
Thank you for assigning me! I will work on it right away!!!

**Comment by shriya22** [comment]
Done and approved hence closing the issue
