### ISSUE TITLE
6.7.7 NON-DEVELOPERS new content needs 

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#1389]
For 6.7.7 NON-DEVELOPERS needs some more representable graphs and each tools link. 
Even the paragraph introduced different platforms with graphs which made by these specific tool, if we can add each tool's name graphs and resource links, that will help users to find correct platforms.
https://github.com/mschermann/data_viz_reader/blob/670e2582620adbc83086a5b018abdeae1293685d/06-process.Rmd#L301

**Comment by XZou0803** [comment]
This issue has been solved
