### ISSUE TITLE
Week 10 issue 2: Chapter on how to select best type of visualization using audience framework

### ISSUE THREAD

**Issue by VikitaNayak** [mschermann/data_viz_reader#1446]
From the Data Visualization class, we have learnt a framework using which we understand what kind of visualization to create, who is our audience and what are they looking for. Below is the audience framework we learnt in the class:
![image](https://user-images.githubusercontent.com/43161990/58981619-8d272b80-8787-11e9-8620-03dbf9e96c08.png)
A separate chapter can be created to explain this framework and its application

**Comment by srivasud** [comment]
Hi @VikitaNayak 
I have logged exactly the same issue to be added in chapter-2 when design principles are described.
https://github.com/mschermann/data_viz_reader/issues/1423
Thanks

**Comment by VikitaNayak** [comment]
Closing this issue since it is already logged as #1423
