### ISSUE TITLE
References missing

### ISSUE THREAD

**Issue by mschermann** [mschermann/data_viz_reader#301]
The following references are mentioned in the text but were either incomplete or missing in the `book.bib` file. Please add them. Make sure that you stick to the formatting of the `book.bib` file.

pandoc-citeproc: reference viz not found
pandoc-citeproc: reference info_viz not found
pandoc-citeproc: reference history_viz not found
pandoc-citeproc: reference charts_viz not found
pandoc-citeproc: reference eagereyes_viz not found
pandoc-citeproc: reference research_viz not found
pandoc-citeproc: reference twitter_Kosara not found
pandoc-citeproc: reference flowingdata not found
pandoc-citeproc: reference infogram not found
pandoc-citeproc: reference data_viz_history not found
pandoc-citeproc: reference intuitive-dash not found
pandoc-citeproc: reference design_principles not found
pandoc-citeproc: reference decept_study not found
pandoc-citeproc: reference rose_tint not found
pandoc-citeproc: reference evil_axes not found
pandoc-citeproc: reference mislead_graph_ex not found
pandoc-citeproc: reference charts_viz not found
pandoc-citeproc: reference next_steps not found
pandoc-citeproc: reference next_steps not found
pandoc-citeproc: reference data_journ not found
pandoc-citeproc: reference DataVizBestPrac not found
pandoc-citeproc: reference benefits_interactive_viz not found
pandoc-citeproc: reference Tufte_2001 not found
pandoc-citeproc: reference Tufte_2001 not found
pandoc-citeproc: reference Tufte_2001 not found
pandoc-citeproc: reference Tufte_2001 not found
pandoc-citeproc: reference Tufte_2001 not found
pandoc-citeproc: reference Tufte_2001 not found
pandoc-citeproc: reference Tufte_2001 not found
pandoc-citeproc: reference int_viz_2 not found
pandoc-citeproc: reference Immigration not found
pandoc-citeproc: reference population_pyramid not found
pandoc-citeproc: reference syria_chart not found
pandoc-citeproc: reference oscars_sowhite_chart not found
pandoc-citeproc: reference int_viz_2 not found
pandoc-citeproc: reference oscars_sowhite_chart not found
pandoc-citeproc: reference oscars_sowhite_chart not found
pandoc-citeproc: reference int_viz_2 not found
pandoc-citeproc: reference case_thesis not found
pandoc-citeproc: reference vizwiz_malaria not found
pandoc-citeproc: reference info_beautiful not found
pandoc-citeproc: reference country_chart not found
pandoc-citeproc: reference country_original not found
pandoc-citeproc: reference hans not found
pandoc-citeproc: reference interworks not found
pandoc-citeproc: reference KDD99 not found
pandoc-citeproc: reference britain_diet_2016 not found
pandoc-citeproc: reference britain-diet-data-trends not found
pandoc-citeproc: reference britain_diet_2016 not found
pandoc-citeproc: reference britain-diet-data-typical_diet not found
pandoc-citeproc: reference britain_diet_2016 not found
pandoc-citeproc: reference TabPy not found
pandoc-citeproc: reference data_meaning not found
pandoc-citeproc: reference design_ebooks not found
pandoc-citeproc: reference Calendar_Layout not found
pandoc-citeproc: reference CalendarView not found
pandoc-citeproc: reference DataUSA not found
pandoc-citeproc: reference CensusDataViz not found

**Comment by wooohu** [comment]
Added bib entries corresponding to the following Case Studies tags:
info_beautiful
britain_diet_2016
vizwiz_malaria
hans
country_chart

Also deleted case_thesis tag in Case Studies because the exact article was not found

**Comment by wooohu** [comment]
Added bib entries corresponding to the following tags in Patterns:
britain_diet_2016
TabPy
DataUSA
CensusDataViz

I also looked for 'data_meaning' and 'britain-diet-data-trends' but could not find the websites they referred to.  What should we do with these tags?

**Comment by mschermann** [comment]
Delete them.
