### ISSUE TITLE
Labels wrong

### ISSUE THREAD

**Issue by mschermann** [mschermann/data_viz_reader#302]
The following labels do not work. Please fix:

1: The label(s) fig:hickey-before, fig:hickey-after not found 
2: The label(s) fig:hickey-breakdown not found 
3: The label(s) fig:hickey-3D not found 
4: The label(s) fig:henry-quarter, fig:henry-half not found 
5: The label(s) fig:hickey-before, fig:hickey-after not found 
6: The label(s) fig:hickey-breakdown not found 
7: The label(s) fig:hickey-3D not found 
8: The label(s) fig:henry-quarter, fig:henry-half not found

**Comment by PreethiSR** [comment]
All the figures are available now. Hence closing the issue.
