### ISSUE TITLE
How to Better Organize Chapter 4 (Case Studies)?

### ISSUE THREAD

**Issue by lpyuan** [mschermann/data_viz_reader#313]
Problem:
Should we organize chapter 4 in the order of articles we added or just by different cases and put their articles information only in references part? Or  should we combine cases in difference themes and reorganize the chapter?

Because in this chapter, some of the contents are from one article, but we seems like separate them in an ambiguous order. Here is the [class reader](https://mschermann.github.io/data_viz_reader/case-studies.html#cool-information-graphics-and-data-viz-from-2016): 

For example: 4.5/4.6/4.7/4.8/4.9/4.10 are all cases cited from 4.2 [article](http://blog.visme.co/best-information-graphics-2016/.), but now they are ordered in parallel with 4.2, then there are only two lines under 4.2. And 4.1,4.3, 4.4 also have this problem.

![screen shot 2018-05-16 at 3 58 05 pm](https://user-images.githubusercontent.com/31947601/40148255-f843c4c2-5921-11e8-86dc-085bf8137db0.png)

**Comment by SaloniS95** [comment]
I think this is how we should reorganize Section 4 : 

Sections 4.1, 4.2, 4.3, 4.18, 4.19 and 4.26 should all be put under 4.24 considering they are links to articles that contain some cool/unique data visualizations.

The remaining individual case studies that show the specific data visualizations with them can be treated as independent entities like they are currently. There are some case studies that are missing a visual with them and what I think is that it would be more appealing and understandable if each individual case study had at least 1 visual with it.

**Comment by lpyuan** [comment]
Yes! Thanks for adding more suggestions on this. It is obviously that 4.19 and 4.26 are not case studies, which should not be put in the same way as others. And I also agree with your points that each case studies better had at least one visual chart with reference.

Maybe we can work together to solve this problem? @SaloniS95

**Comment by SaloniS95** [comment]
Sure! @lpyuan 

Also, in my other Issue that I put up, I added this part where I think some other sections' subtopics can be put in section 4 and vice versa : 

Sections :: suggested section
5.6 : case studies
5.10 : case study
4.27: fundamentals

what do you think about these??

**Comment by SaloniS95** [comment]
Yes
4.27 would seem better in section 5 - patterns.

**Comment by katharinegrant** [comment]
For the individual case studies, what do you think about grouping the case studies by type of visualization (e.g. all maps grouped together)?

**Comment by lpyuan** [comment]
That's a good idea! I think we can do in that way~
