### ISSUE TITLE
Reorganize Overlapping Contents in Chapter 5-Patterns and Chapter 4-Cases Studies

### ISSUE THREAD

**Issue by gleamingMushroom** [mschermann/data_viz_reader#314]
For now, we can see a lot of overlaps between chapter 4 and chapter 5, some contents of cases studies, bad/good visualization examples, improvement tips are organized under chapter 5 instead of chapter 4. 

Would it be better to:
1. Move all materials in chapter 5 but actually related to chapter 4 such as visualization examples and tips to chapter 4;
2. Define a more clear structure of chapter 5 about what content should be added in here.

**Comment by mschermann** [comment]
check the other issue on this
