### ISSUE TITLE
Organize Fundamentals Chapter by Related Topics?

### ISSUE THREAD

**Issue by skakers** [mschermann/data_viz_reader#315]
There are reflections/references in fundamentals with similar themes, and it might make the chapter more cohesive to group them?

Some ideas for possible sections: 
History
Design Principles
Best Practices
Tools
Special Features (e.g. interactivity)
Additional References

**Comment by cmccarney** [comment]
This makes sense but since there is already some History in the introduction, maybe we move all of the history there.

**Comment by skakers** [comment]
I think that's a good idea!

**Comment by Sikhadasr** [comment]
I have grouped the additional references/resources at one place in Introduction and have grouped some of the information regarding the tools.
