### ISSUE TITLE
Chapter 4 , 5, 6 

### ISSUE THREAD

**Issue by SaloniS95** [mschermann/data_viz_reader#316]
What exactly does the "Patterns" portion represent? Currently it is very heterogeneous and not very specific. 

According to me the following topics from chapter 4,5  amd 6 need to go to different sections 

Section::: suggested section 

5.9 : fundamentals 
5.6 : case studies 
5.10 :case study 
5.13 :  fundamentals 
4.27 : fundamentals 
6.3 : fundamentals / patterns 
6.4 : fundamentals / patterns

**Comment by cmccarney** [comment]
Regarding chapter 6: I think we should consolidate all of the deceptive/misleading visualizations in the ethics chapter. Fundamentals/Patterns can address good and bad graphs, but if we're talking about misleading the audience, that is an ethical issue.

**Comment by mschermann** [comment]
Good idea. 

My idea for the patterns chapter is to collect recipes for creating effective graphs / solve common problems when developing charts.
