### ISSUE TITLE
A lot of text piled up but no clear emphasis and graph examples

### ISSUE THREAD

**Issue by EchoXu5** [mschermann/data_viz_reader#318]
When I read this reader, I found a lot of paragraphs are just text piled up there. There are no clearer layers for some topics and emphasis or graph examples. This issue will make our reader not so readable and well understandable. 

For emphasis, it will be a clear clue for everyone to get the main point quickly. So I suggest highlighting the main point in each topic.

For graph examples, it will be necessary to explain some graph use image, not words. I suggest those topics to try to add at least one image below the text.
For example:
In Chapter 5: Patterns: 5.1 Avoiding Common Mistakes with Time Series
The passage just uses text to describe the graph and no graph for example.  It makes it hard to understand. No emphasis sentence showed up either.

**Comment by EchoXu5** [comment]
Finally, I found two contents in Chapter 5&pattern is duplicated or wrong located content. Already corrected them.
Highlighted some important sentences and edited some typos.

**Comment by hitomi0108** [comment]
That's a good point! Maybe we should use the same format for the topic highlight. May I ask what kind of highlight did you use?

**Comment by EchoXu5** [comment]
Hi, Hitomi,

Sorry to reply late.Thanks for your interest!.

What I mean is that let our book look like a real book. It has clear main
point sentences highlighted with color or something else. So we can just
read all highlighted sentences to get the main idea and find specific
topics what we want to read more.

Let's work together to make this reader more readable!

Best,
Yunjia

Yunjia(Echo) Xu
Santa Clara University
Leavey School of Business, Business Analytics
