### ISSUE TITLE
Some idea for Patterns Chapter5 

### ISSUE THREAD

**Issue by Hazel-Han** [mschermann/data_viz_reader#319]
1. What to include:  According to our original thought, I think we should include principles that are reproducible or make it easy to develop charts in Chapter 5. Different from Chapter Fundamentals, which should include all general ideas for viz, Chapter Patterns should include something that can be practiced. Right now base on what we already have, some sessions list below in Chapter 3 Fundamentals should be moved into Chapter 5:

(Pick the Right Chart Type 3.7
Visual Data Communication 3.14
Gestalt Principles for Data  3.15
Definitions of Data Deception and Graphic Integrity 3.5.1)

About deception part, I think differently from suggestion in issue #316 . Deceptive charts are useful tool to develop charts and enhance ideas so this part may be put into Patterns part. 

2. Integration: Right now some sessions in Chapter 5 are overlapped and some sessions are too detail to be a separate session. My suggestion is combine session with same idea, such as 5.1 and 5.6, also we may integrate all general tips into one single session.

**Comment by gleamingMushroom** [comment]
As my understanding of Patterns, it should include the visualization methods, design techniques, and practical experiences, in other words, something we can learn from to improve our skill. So I agree with keeping the deceptive charts in Chapter 5 and move these contents from Chater 3 to 5, maybe also move "3.5 What I learned recreating one chart using 24 tools" as it's about tool and experience.

**Comment by Hazel-Han** [comment]
Yes, agree. I think any related tools or useful techniques should be include in Chapter 5. Maybe we can solve this part together!

**Comment by gleamingMushroom** [comment]
I moved some content from other section to Patterns, @Hazel-Han if you also find the content should be included in Patterns are all there, we can close this issue!

**Comment by Hazel-Han** [comment]
I think problems I mentioned in Patterns have all been solved, we can close this issue now. @gleamingMushroom
