### ISSUE TITLE
Best Data Visualization - Case Study - Consolidation

### ISSUE THREAD

**Issue by amritasharma05** [mschermann/data_viz_reader#320]
In Case Studies there are multiple bullet points which cover similar information. For example:-
10 Best Data Visualization Projects of 2015
16 Captivating Data Visualization Examples
15 Data Visualizations That Will Blow Your Mind
All the above can be consolidated and summarized together. I was also think we can add insights at the end that we can draw from the best data visualizations similar to what we discussed in class (Minard).

**Comment by katharinegrant** [comment]
Consolidated in #343
