### ISSUE TITLE
Intro Page - Resources at the bottom, move to another section?

### ISSUE THREAD

**Issue by tylerhyoung** [mschermann/data_viz_reader#342]
This is my suggestion to clean up the bottom of the intro page, but I welcome your input.

I think with the intro, short and clean is best to grab attention and make a smooth transition to the rest of the book. That said, there are four sections at the bottom (not all committed to the master yet) that I think should be moved elsewhere but I'm not sure where is best.

"Useful Links on Data Visualization Trends, Tutorials and Research Papers"
"Resources for Aspiring Data Visualists"
"Other sources of great visualization"
"More ways to improve your visualization design"

It's all solid content, but they seem more like conclusion topics and will send readers elsewhere, when the goal of the first chapter should be enticing them to dive into chapter 2. 

How do you think we can best integrate these sections into the reader?

**Comment by Sikhadasr** [comment]
I integrated these topics together but could not figure out a suitable place for them. How about keeping them in references or conclusion?

**Comment by kriener51** [comment]
I think they would be best suited in the references section since they all point to specific resources.

**Comment by FengSCU** [comment]
I agree that "Useful Links on Data Visualization Trends, Tutorials and Research Papers" should be put in either references section or conclusion section, instead of intro.
