### ISSUE TITLE
Outline for Case Studies

### ISSUE THREAD

**Issue by katharinegrant** [mschermann/data_viz_reader#347]
For the titles and headers in the case study chapter, I would like for us to decide on the levels for the headers. Since @lpyuan and @SaloniS95 have started to reorganize and remove non-case studies in #313 I think that if we rearrange the actual case studies, we can then have the second level headers (e.g. 4.1 or ##) as the groupings and the individual case studies as third level (e.g. 4.1.1 or ###). With the case studies currently being all second level, the Case Study section of the table of contents feels unnecessarily long.
Thoughts?

**Comment by amritasharma05** [comment]
I was thinking to reorganize Case Study more of lines on below:
1. Best Data Visualization of All times - This can be consolidated including all individual examples
2. Individual Case Studies
3. Good Data Visualization Examples
4. Insights - What kind of insights can be drawn from these case studies which we refer in the future.
Obviously numbering and reordering can be done base done data.
Any other thoughts?

**Comment by katharinegrant** [comment]
How would you differentiate between parts 2 and 3? Other than a few, I'd imagine most case studies were included because of being "Good Data Visualization Examples".  And would part 1 be what we consider the best of those?
But I definitely like the idea of an insights section! Should it go above the "Application of Data Visualization" section, or elsewhere?

**Comment by amritasharma05** [comment]
1. Best Data Visualization - There are multiple references mentioned such as 10 Best Data Visualization of all times, 15 best examples, etc I was thinking of including all this together.
2. Individual Case Studies - Actual Case Studies (HBR) or white paper reviews, etc which have critiqued and summarized.
3. Good examples - Basic examples such as Minard, etc.

**Comment by katharinegrant** [comment]
The multiple references section I think is now closer to the bottom as more of a "for further reading" section instead of as the intro to the chapter.
If the Good Examples are more basic, then maybe we should put them before the more complex case studies? That way the chapter goes:

1. Basic/introductory examples
2. Complex examples with more analysis
3. References for further exploration
