### ISSUE TITLE
Merge History Parts of Intro and Fundamentals

### ISSUE THREAD

**Issue by YingjieYu** [mschermann/data_viz_reader#352]
In intro, there is a topic named "Key Figures in the History of Data Visualization".  And the opening of Fundamentals talks about A Brief History of Data Visualization. I think this two could be merged to make the reader more logical.

**Comment by gleamingMushroom** [comment]
Totally agree, "2.3 Key Figures in the History of Data Visualization" could be a subchapter of "3.1 A Brief History of Data Visualization".

**Comment by Hazel-Han** [comment]
This problem has been figured out. If you guys also agree with the adjustment we can close this issue.
