### ISSUE TITLE
Issues with proof reading

### ISSUE THREAD

**Issue by allisonyanc** [mschermann/data_viz_reader#363]
When I was trying to proofread some parts of a chapter, especially when the text length is longer than few paragraphs, after I pull request there'll always be conflicts and sometimes the conflicts could be more than 10... I found it hard and scary when trying to resolve the conflicts because it requires me to read the parts again and also needs to make sure I won't delete anything useful by mistake.
So I'm wondering is it only my concerns, or is it the right way to do it?

**Comment by ppandey2** [comment]
I think I also have had the same issue, probably because of large content. I would suggest just follow the markers and it kind of lets you know what exactly moved in that part so in a way you don't end up deleting content. Sometimes I think it also happens because of fetch origin failure.
