### ISSUE TITLE
case studies content

### ISSUE THREAD

**Issue by FengSCU** [mschermann/data_viz_reader#366]
When I read case studies, I feel that some contents are repetitive. For example, "Best Data Visualization Projects of 2015" occurs in both  "Best Data Visualizations cases" and " Articles to Read..." sections. I understand such content may include multiple graphs. My suggestions are
1) Move "Articles to read to check out some cool visualizations are mentioned below :" section to reference section, and with a link so people can check the article directly.
2) Delete the content without reproduced graph (1.1-1.4)

**Comment by FengSCU** [comment]
In addition, about last section "Two Awesome Visualists": I only see one - David McCandless, is there any content missing when editing?

**Comment by amritasharma05** [comment]
I tried to consolidate all the best data visualizations together which are individual examples including Hans Rosling case study
