### ISSUE TITLE
Use of we, you and I in the description text - content

### ISSUE THREAD

**Issue by ppandey2** [mschermann/data_viz_reader#375]
Though not a very important matter to be addressed but sometimes I see sentences using we, you, I , for instance, "We understand from this graph that...", and sometimes "I infer from the article that..." and at few places, "This is what you need for a good visualization...". I have tried making them follow one trend.
Other than that, there are places where it is mentioned, "we learnt this in the class", so we are making a reader on visualization, is it correct to mention, in the class - referring to our Data Viz class or content like that?

**Comment by amritasharma05** [comment]
I agree with the the idea of 'This is what you need for a good visualization..' format of describing and put in content. But how do we mention our opinions? Our ideas and thoughts?

**Comment by ppandey2** [comment]
After having a look at all the chapters, content in the context of this issue looks fine. Thus, closing the issue.
