### ISSUE TITLE
use of reference

### ISSUE THREAD

**Issue by hitomi0108** [mschermann/data_viz_reader#384]
I noticed that reference also contains some "non-reference" contents such as website recommendations and case study examples, which makes the reference messing.
I'm thinking maybe we should use the reference content only for listing all the reference source and put those website recommendations into somewhere more appropriate.

**Comment by hitomi0108** [comment]
I also noticed that some people tend to add reference right under their contents. Maybe we should put all the reference source into the reference content in a nicely formatted way? Thoughts?

**Comment by hitomi0108** [comment]
"4. Using The Wrong Graphs" is more like a context for Ethics instead of reference.
And its format is different from all other references.

**Comment by mcchiang06** [comment]
I noticed this issue and looked at the reference again. I agree there are something in the reference should be moved to other chapters. One thing I moved is "7.1 More ways to improve your visualization design," I think this part should go to the Fundamental chapter. 
After this, I think the reference is cleaner now.

**Comment by hitomi0108** [comment]
I noticed that "4. Using The Wrong Graphs"  has been moved to other chapters. Thanks!
