### ISSUE TITLE
Issue with Merge Conflict

### ISSUE THREAD

**Issue by tianminli1199** [mschermann/data_viz_reader#385]
During the cleanup last week and this week, I noticed that there are repetitive paragraphs/sentences in the reader. The essential problem is that people simply delete conflict markers such as <<<<<<<, =======, >>>>>>>  but didn't look at why there is a conflict and many times it is multiple people working on the same thing. It is recommended to read contents around the conflict markers to avoid duplication.

**Comment by mcchiang06** [comment]
Yes! I agree that we should not just simply delete the conflict marker and pretend the conflicts have been solved. But sometime when I just correct the typos, I see the conflicts show up. I don't understand why those conflicts come from. So I just deleted the markers and repetitive sentences.

Deleting those repetitive is an easy way to make the contribution.

**Comment by tianminli1199** [comment]
Checked duplicates within each chapter and got rid of all duplicates.
