### ISSUE TITLE
The format of reference is not consistent

### ISSUE THREAD

**Issue by mcchiang06** [mschermann/data_viz_reader#477]
When I read the reference chapter, the format of many reference items is not consistent. For example, some items show the year: N/A (**Author: Andrei Zinovyev, year: N/A**) and some without year information(**4.3 Design Iron Fist**  **Author: Jarrod Drysdale** )

Some items show the data information, like February 28th, 2016 and show just show the year information, like 2015. Those just show the year information actually can show the date information, such as **2.17 Next Steps for Data Visualization Research**  . And some are just wrong , such as "“An Aging Population.” XXXX."

Some other titles are weird that start with"---" , such as  ———. 2018. “Infogram- Data Visualization.” or XXX, such as "XXX, XX. XXXX. “Using Data Visualization to Find Insights in Data.”

Moreover, some links of the reference can't be used. For exmaple, "visualizer, A great. 1982. “A ficticious web page title.” http://great{\_}viz{\_}org." . "———. 2018b. “Tableau Groups.” https://www.linkedin.com/search/results/groups/?keywords=tableau{\&}origin=SWITCH{\_}SEARCH{\_}VERTICAL.
"

**Comment by neophyticfern** [comment]
Corrected one of the references - dataviz_political_socialsciences
(N/A (Author: Andrei Zinovyev, year: N/A) )
Added the correct reference below the old reference
