### ISSUE TITLE
Wrong Source and Reference 

### ISSUE THREAD

**Issue by mcchiang06** [mschermann/data_viz_reader#482]
there are so many places in the reader show Source: (???) referenced in (???). I list them as below.

2.1 What is Data Visualization?
2.5.2 David McCandless
3.1 Storytelling
3.3 Three Rules to Follow in order to Develop Intuitive Dashboards
3.4.5 Three Rules to Follow in order to Develop Intuitive Dashboards
3.5.2 Interactive Data Visualization
3.6 Research Results & What’s Next
Chapter 4 Case Studies
4.1.2 Two Centuries of U.S. Immigration
4.4.3 From Pyramid to Pillar: A Century of Change, Population of the U.S.
4.5.8 A Guide to Who is Fighting Whom in Syria
4.5.9 Adding up the White Oscars Winners
4.5.17 Britain’s diet in data
5.1 Using Shapes as Filters in Tableau When Your Fields Are Measures
5.9.3 Conclusions
5.13 An example to back some of our theories on ‘how to tell stories using data visualization’ / ‘exploratory data visualization’
6.5 Definitions of Data Deception and Graphic Integrity
7.1 More ways to improve your visualization design

**Comment by SaloniS95** [comment]
I went through each topic you mentioned, and I can see that in the latest class reader, the sources and the references have been added for the mentioned topics. 

The only topics that I could not find were 3.3, 3.4.5, 5.13 and 7.1. There is a possibility that these might have been moved around in the latest version of the class reader and hence I can't find them where you mentioned them.

**Comment by wooohu** [comment]
7.1 was moved to Fundamentals section and I'm working on the reference for it now.  All the others @SaloniS95  mentioned are not in any of the modules so I'm guessing they were completely removed.  I'll close out this issue once 7.1 is fixed.
