### ISSUE TITLE
Missing reference/link in 04 Patterns

### ISSUE THREAD

**Issue by FengSCU** [mschermann/data_viz_reader#486]
As I read 04 patterns, I found some of contents lack reference, please check the following:

## Genetic Network Reconstruction 
any **reference**?

## Building Advanced Analytics Application with TabPy 
[@TabPy]
 ...Imagine a scenario where we can just enter some x values in a dashboard form, and the visualization would predict the y variable!!! Here is a **link** that shows how to integrate and visualize data from Python in Tableau.
Where is the link???

## Pick the Right Chart Type
**reference?**

**Comment by mcchiang06** [comment]
Building Advanced Analytics Application with TabPy
I think the link is here.
https://www.tableau.com/about/blog/2017/1/building-advanced-analytics-applications-tabpy-64916
On the Bib file, the contributor used the tag in the wrong way and I already correct it.
