### ISSUE TITLE
Reference Tag is missing at book.bib file

### ISSUE THREAD

**Issue by mcchiang06** [mschermann/data_viz_reader#509]
Some tags in the R markdown file is not in the book.bib file and make the reader has the "???" marks. Either we should create those tags in the book.bib file or correct the tags to have the correct reference links or remove the tags that no longer used in the R markdown file. 

For exmaple, at "case studies" chapter, there are tags such as"15_mindblowing" "population_pyramid". However, this tag can't be found in book.bib file.
Another example is http://vudlab.com/simpsons/ . This link doeesn't exist.

**Comment by Hazel-Han** [comment]
I think someone already added '15_mindblowing' and 'population_pyramid' in book.bib, I can find it now. Still that 'simpsons' link has been deleted. Maybe we can close this issue now.
