### ISSUE TITLE
abstract in book.bib

### ISSUE THREAD

**Issue by SaloniS95** [mschermann/data_viz_reader#594]
While going through the book.bib references, I found an abstract with an entire paragraph in that reference. The title is **"Using_Typography_to_Expand_the_Design_Space_of_Data_Visualization"**. 

Are abstracts supposed to be there in the book.bib? None of the other references have an abstract with them.

![issue1](https://user-images.githubusercontent.com/31704828/40999548-0f41865c-68c0-11e8-8bea-1c2792d5ea6e.PNG)

**Comment by Hazel-Han** [comment]
I checked and found only three of references have abstract, and all of abstracts now are quite short. I think we can leave them there.

**Comment by mschermann** [comment]
Abstracts are fine
