### ISSUE TITLE
Repeated content in book.bib

### ISSUE THREAD

**Issue by Hazel-Han** [mschermann/data_viz_reader#612]
When look through book.bib file, I found lots of references are repeated two, three or even four times which may caused by didn't solve conflicts well while merging. 
I removed some of them but still lots exist. Do we need to remove all repeated content or just leave them?

**Comment by SaloniS95** [comment]
I noticed them too and I working on removing them. I don't think we need the repeating references as long as the spellings and the capitalizations are the same. I am not deleting refs like 'Data' and 'data' because these capitalizations all need to be edited to where these references have been put in the class reader.

**Comment by SaloniS95** [comment]
Sure!

**Comment by FengSCU** [comment]
I found that issue too. Already delete several of them.

**Comment by SaloniS95** [comment]
Update: I have deleted almost all the repetitive contents from the book.bib. Some of the refs that I could not remove have the following issues : 
1. Same refs, different capitalizations: for example, refs like - 'Data' and 'data'
2. Same refs, different access dates.

**Comment by lpyuan** [comment]
I am also working on this. Maybe for those almost same refs but still have a little differences, we better check what we used in the original reader and unify them in the bib file? @SaloniS95

**Comment by SaloniS95** [comment]
@lpyuan yes that would be good.

**Comment by Hazel-Han** [comment]
Hey guys, I checked those references again and found most of repeated contents have been removed. Is it ok that I close this issue? @SaloniS95 @FengSCU @lpyuan

**Comment by FengSCU** [comment]
Agree, I already done my part.

**Comment by gleamingMushroom** [comment]
Hi, I checked again, there are no duplicate references anymore, I think this issue can be closed.

**Comment by lpyuan** [comment]
Yes I think we can close this issues now~
