### ISSUE TITLE
Relevance of Entry in Fundamentals

### ISSUE THREAD

**Issue by wooohu** [mschermann/data_viz_reader#635]
While fixing the references for an entry in the Fundamentals section, I came across two paragraphs that may not be relevant to data viz.  The titles of these paragraphs are listed below:
Designbetter.co
Type Classification

The first one is focused on graphic and product design, and the second is about typography.  I have kept them and added the missing references for now, but if anyone has suggestions on whether to keep or remove these subtopics, that would be helpful.  Thanks!

**Comment by ppandey2** [comment]
Maybe we reduce the typography paragraph and not completely remove it. Suggestions...

**Comment by wooohu** [comment]
@neophyticfern @ppandey2 I like both those ideas, I've made those adjustments now.  Thanks!
