### ISSUE TITLE
Duplicate Text in Chapter 2.1

### ISSUE THREAD

**Issue by JinjinJanelle** [mschermann/data_viz_reader#734]
The quote (Friedman 2008) after first paragraph in Chapter 2.1 is the same as the paragraph after the quote.

**Comment by 82817** [comment]
I've noticed this as well. I also checked the RMD file to make sure it is not a problem with the code.

The extra paragraph after the code should be removed.

**Comment by gauravhassija** [comment]
I agree with the duplicate text. The paragraph from the reference link should be kept and the other should be deleted.

**Comment by JinjinJanelle** [comment]
The problem was fixed.
