### ISSUE TITLE
Duplicate Subtitle in Chapter 2.2.3

### ISSUE THREAD

**Issue by JinjinJanelle** [mschermann/data_viz_reader#735]
A duplicate and wrong subtitle above Chapter 2.2.3

**Comment by preranap1** [comment]
yes. It can be removed.
Also, it would be good to include the billion dollar-o-gram chart here as it appears here first.
Currently, the diagram is in the conclusion section (7.1).

**Comment by JinjinJanelle** [comment]
The problem was fixed.
