### ISSUE TITLE
Duplicate and Wrong Paragraph of Chapter 2.2.6

### ISSUE THREAD

**Issue by JinjinJanelle** [mschermann/data_viz_reader#736]
The paragraph under Chapter 2.2.6 does not match the title and is the same as the second paragraph of Chapter 2.2.5.

**Comment by strivedi2** [comment]
I agree. In my issue #772 I have mentioned how sections 2.2.4- 2.2.6 are not relevant in the Importance of Data Visualization (reader section 2.2) and need to be addressed.

**Comment by Kushall-Dayal** [comment]
Section 2.2.5 can be concise as it sways away and talks about the importance of visualization in a very generic sense.
The table has a criteria "Appealing" which I think is irrelevant to section it is being discussed in

**Comment by syragrg** [comment]
I would remove the paragraph from 2.2.5. Perhaps it would fit better under 3.2 as an intro for best practices.

**Comment by JinjinJanelle** [comment]
The problem was fixed.
