### ISSUE TITLE
Duplicate Paragraph in Chapter 2.3.1.1

### ISSUE THREAD

**Issue by JinjinJanelle** [mschermann/data_viz_reader#737]
The first and second paragraphs under Chapter 2.3.1.1 are duplicates.

**Comment by strivedi2** [comment]
I noticed the same. Adding link to the code below to help locate the issue:
`https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L107`
