### ISSUE TITLE
Unreadable Table in Chapter 2.3.1.1

### ISSUE THREAD

**Issue by JinjinJanelle** [mschermann/data_viz_reader#738]
The timeline of visualization history is unreadable because of a lack of proper separations.

**Comment by agrasonal** [comment]
I agree with you and believe that the history text after proper formatting, if supported with the timeline graph mentioned in the reference book - (http://www.datavis.ca/papers/hbook.pdf), will help the readers get a better understanding.

**Comment by strivedi2** [comment]
I found the same issue. Adding reference to the code here. Maybe we can work together to address this. https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L112

**Comment by JinjinJanelle** [comment]
This problem was fixed.
