### ISSUE TITLE
Inconsistent Placement of Page Number

### ISSUE THREAD

**Issue by rlwy** [mschermann/data_viz_reader#739]
The page number placement varies across pages:
- top left corner (even-pages)
- top right corner (odd-pages)
- bottom center (cover page of a chapter - always on a odd-number page)

May want to consider removing the bottom center placement as it leads to having blank pages at the end of a chapter, should the chapter end on an odd-number page.

**Comment by jma4** [comment]
I think all these issues are caused by saving it as pdf file.
