### ISSUE TITLE
Images are Cut Off on Some Pages

### ISSUE THREAD

**Issue by rlwy** [mschermann/data_viz_reader#741]
Examples of affected pages:
<img width="527" alt="Screen Shot 2019-04-03 at 11 33 09 PM" src="https://user-images.githubusercontent.com/7339316/55534540-b7267980-5682-11e9-947f-0356deb9fba9.png">
<img width="527" alt="Screen Shot 2019-04-03 at 11 35 18 PM" src="https://user-images.githubusercontent.com/7339316/55534542-b7bf1000-5682-11e9-9135-d1082068c2ec.png">
<img width="527" alt="Screen Shot 2019-04-03 at 11 34 50 PM" src="https://user-images.githubusercontent.com/7339316/55534543-b7bf1000-5682-11e9-8401-866fed4bb35d.png">

**Comment by bharatimalik** [comment]
I could see all the graphs properly. Did you save the webpage as a PDF and are you referring to that PDF?

**Comment by rlwy** [comment]
Unable to reproduce. Images are appearing correctly in rendered HTML version.
