### ISSUE TITLE
Text Wrap Code and Text

### ISSUE THREAD

**Issue by rlwy** [mschermann/data_viz_reader#742]
<img width="536" alt="Screen Shot 2019-04-03 at 11 47 35 PM" src="https://user-images.githubusercontent.com/7339316/55535113-2f416f00-5684-11e9-8380-bc90d9f26ae5.png">
<img width="530" alt="Screen Shot 2019-04-03 at 11 44 08 PM" src="https://user-images.githubusercontent.com/7339316/55535224-83e4ea00-5684-11e9-830b-ed2ddd997a02.png">

**Comment by KlippL** [comment]
Can you add more about what needs to be changed? 

There are many different screenshots here without a more in detail explanation of what needs improving.

**Comment by rlwy** [comment]
Hi @KlippL, I was thinking to make all images centered on a page and text in code bins to be wrap (not going over their container space). In the examples, we can see that some code just goes over the page and we can't read them. So instead of running over the container space, we put them on a new line.

**Comment by rlwy** [comment]
Unable to determine the cause of this issue. The display seems to be fine in the HTML version and is only appearing off in the PDF version.
