### ISSUE TITLE
Invalid content (???) in published text due to mismatch of citation tags

### ISSUE THREAD

**Issue by rlwy** [mschermann/data_viz_reader#743]
Invalid content (???) in published text.

Examples:
<img width="532" alt="Screen Shot 2019-04-03 at 11 53 05 PM" src="https://user-images.githubusercontent.com/7339316/55535382-108fa800-5685-11e9-8721-06c41f64063d.png">

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L790
<img width="529" alt="Screen Shot 2019-04-03 at 11 45 56 PM" src="https://user-images.githubusercontent.com/7339316/55535470-5b112480-5685-11e9-8085-5a6171cb0ff0.png">

Issue is caused by typo on citation. Using the screenshot of the first example, The citation tag [@intuitive-dash] in the *.rmb* file do not match the bibliography metadata in *book.bib*, which uses [@intuitive_dash]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L453-L455
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/book.bib#L994

**Comment by jma4** [comment]
I think it would be easier for people to read through if you kindly add which chapter it is loacted or the page number in the title. Thank you

**Comment by KlippL** [comment]
I agree that the invalid content needs to be replaced but to reiterate the point made by jma4, we need to resolve each of the (???) separately, so making sure each of the Issues has their own label for the location would be helpful to make sure we resolve all of them.

**Comment by mschermann** [comment]
You can create issues directly from code. https://help.github.com/en/articles/opening-an-issue-from-code

**Comment by preranap1** [comment]
I think the invalid content is a missing reference. 
This could be the missing link: https://www.perceptualedge.com/articles/visual_business_intelligence/dboard_confusion_revisited.pdf

**Comment by rlwy** [comment]
The issue occurs across the entire project. Should we be creating an issue for every occurrence? It may be possible to resolve some of them if we look into the issue but some cannot be recovered. I would suggest to remove them, where it is not possible to recover as they give no value to the reader in their current form of (???) and it is not possible for future collaborators to unriddle them without knowledge of their origin.

**Comment by rlwy** [comment]
Thanks @jma4 @KlippL @preranap1 for the feedback. I managed to dig into the code today and found the cause of the issue. I've updated the comment in my issue with the explanation of it.

You can refer to the citation documentation for R markdown for more details. https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax
