### ISSUE TITLE
4.5.3 hard to understand the amount of plastic pollution in Visualization of Ocean Plastic collection 

### ISSUE THREAD

**Issue by jma4** [mschermann/data_viz_reader#744]
It's hard to read the scales of plastic amount in the graph clearly and it also could lead to misunderstanding of there are less amount of plastic waste in the oceans.

**Comment by VikitaNayak** [comment]
Yes, maybe we can change the color of text from dark gray to black which will make it easier to read

**Comment by JinjinJanelle** [comment]
Also, in the first graph, the years have different gaps. It is better to use serrated x-axis between to indicate it.

**Comment by jma4** [comment]
Proposal:
In this visualization, it shows large amount of plastic in the ocean, however it still might be misguiding people that plastic pollution is a minor problem. Plastic pollution can be seen gathering at two main areas also most part of the ocean showing no sign of plastic. Although other graphics demonstrates how serious is the issue, I would add an explaining paragraph in order to avoid misreading of this graphic.
