### ISSUE TITLE
Insert external links for recommended tools

### ISSUE THREAD

**Issue by rlwy** [mschermann/data_viz_reader#745]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L435

To link the recommended tools in the text to their sites. For example, on page 58, Drake, DataWrangler and OpenRefine have been suggested as tools to use for data cleaning. We can link them to their appropriate sites for reader convenience. 

Drake: https://www.factual.com/blog/introducing-drake-a-kind-of-make-for-data/
DataWrangler: http://vis.stanford.edu/wrangler/
OpenRefine: http://openrefine.org/

**Comment by harizhisham** [comment]
I like this idea, as it provides the reader a quick way to access the tools without having to google themselves.

Perhaps we can also do this for the other tools mentioned in the section for quick reference?

**Comment by rlwy** [comment]
@jymhe120 thanks for fixing this!
