### ISSUE TITLE
Fix Citation- 5.8 Paragraph 4

### ISSUE THREAD

**Issue by KlippL** [mschermann/data_viz_reader#746]
The (???) after Python seems like it is missing a citation:
"Python: (???)"

Whereas the previous paragraph looks like this:
R: (analysis 2018)

**Comment by mschermann** [comment]
you can create the issue directly from the code: https://github.com/mschermann/data_viz_reader/issues/747#issue-429448621

https://help.github.com/en/articles/opening-an-issue-from-code

**Comment by ttussing** [comment]
This information might be associated with [Duong vu, 2018](https://www.datacamp.com/community/tutorials/wordcloud-python)

We can also use this source to build out this section

**Comment by KlippL** [comment]
The person who originally cited this was using:
https://www.geeksforgeeks.org/generating-word-cloud-python/

However, your link @ttussing has very similar information and would also be a good addition if someone was learning how to make a word cloud in python.
