### ISSUE TITLE
Missing citation

### ISSUE THREAD

**Issue by mschermann** [mschermann/data_viz_reader#747]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L790

**Comment by Vidya313** [comment]
The issue is fixed , the reference '[@viz_R]' is working fine.
![image](https://user-images.githubusercontent.com/49168495/57563767-a68ab280-7356-11e9-8a97-ca3601179243.png)

Hence closing this issue.
