### ISSUE TITLE
Citation in wrong format - 5.1 Paragraph 1

### ISSUE THREAD

**Issue by KlippL** [mschermann/data_viz_reader#748]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/04-patterns.Rmd#L8

(Gervini, 2009) is not in the proper citation format.

**Comment by jma4** [comment]
I don't quite understand the issue here, is it because of lacking url link?

**Comment by KlippL** [comment]
Correct. The beginning of the reader specifies the proper citation format and this doesn't follow that format with the url link.

**Comment by KlippL** [comment]
So when I google the 2 sentences that the citation seems to be referencing:

> "We can use data visualization for outlier detection in a data set. Different methods for outlier detection in functional data have been developed over the years. Several of these methods rely on different notions of functional depth, robust principal components, or random projections of infinite-dimensional data into R. Some distributional approaches have also been considered (Gervini, 2009)"

I see references to a paper written by Arribas-Gil and Romo from the citation above:
[https://www.researchgate.net/publication/260758235_Shape_outlier_detection_and_visualization_for_functional_data_The_outliergram]

Then when I search for Gervini within the paper, Gervini is a reference within the paper:

> Also, some distributional approaches have been considered (Gervini, 2009).

The weird thing about this citation is that the author seemed to only choose to include this one citation though there are many more within the paragraph that they slightly paraphrased, the ideas within that sentiment were citations of other works. 
![image](https://user-images.githubusercontent.com/39971612/55691930-efb2a580-5957-11e9-8c09-98b210ac43b9.png)

It seems like not we need to make a decision of which kind of citations we should include in the reader when including ideas from an academic article.
