### ISSUE TITLE
Better graph labels 

### ISSUE THREAD

**Issue by KlippL** [mschermann/data_viz_reader#749]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L27

There are two graphs side by side, the left graph has proper X, Y axis labels of speed and dist, while the graph on the right doesn't have renamed axis labels. This would look much better if there were proper X, Y axis labels for both graphs. 

![image](https://user-images.githubusercontent.com/39971612/55584651-93425280-56d9-11e9-8ace-4e8bf9113f54.png)

**Comment by kwright76** [comment]
Included with the labels, consistency in images and using the same data should be used as to not confuse the audience.

**Comment by pragyansharma24** [comment]
Yes @KlippL, I agree that in the second graph the axes are not labeled correctly. 

Also, notice that both the graphs are representing the same data.  Only the axes are flipped. 
They look different because the axes width looks similar to the previous one.

**Comment by btamsir** [comment]
Agreed. Also in R, you can rename the x and y axis using commands 

plot(x, y, main="title", sub="subtitle",
  xlab="X-axis label", ylab="y-axis label."

**Comment by KlippL** [comment]
I'm actually not entirely certain why the author chose to include the second representation of the graph with the outliers. The switched axis doesn't seem to be making an additional point, and there is no comment explaining why the author chose that second representation. It might almost be better to get rid of line 27 in the code and just have the graph with outliers and without outliers.
