### ISSUE TITLE
3.5 & 3.5.1-Title character Capitalization format is not consistency

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#751]
Titles in 3.5 & 3.5.1 "Data Visualization" and "Data visualization" format are not consistent. The author should change 3.5 title "Data visualization" to "Data Visualization".
<img width="524" alt="Screen Shot 2019-04-04 at 7 43 51 PM" src="https://user-images.githubusercontent.com/40288420/55603017-5a2bd180-571d-11e9-9b2a-69862f33ca6d.png">
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L406
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L408

**Comment by XZou0803** [comment]
I feel the same as you, and in here, I think it would be a little confused to use "industry" sometimes and also use "business" sometimes, the author might considered the two words the same but actually, they are not.
 I recommend to change the word "industry" and just unified to "business" or "business areas" as well!

**Comment by jma4** [comment]
I think industry includes some non-profitable organizations not only focused on profit-oriented business. 
But I agree with you that the author should make it more clear argument.

**Comment by Cindyli0310** [comment]
I fixed the issue last week, so I close it now.
