### ISSUE TITLE
Fix Citation 5.10.1

### ISSUE THREAD

**Issue by KlippL** [mschermann/data_viz_reader#752]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L476

![image](https://user-images.githubusercontent.com/39971612/55585646-0220ab00-56dc-11e9-8393-a2a9ee2db4d3.png)

The (???) needs to be updated with a proper citation

**Comment by jacksonh2** [comment]
Hi Laura, I have noticed the same issue, and the missing citations are definitely all over the reader with the (???)
Here's a link that I found that's related to the topic and possibly might be the missing link/citation.

https://www.tableau.com/about/blog/2016/2/how-use-custom-shapes-filters-your-dashboard-50200

**Comment by KlippL** [comment]
The citation was fixed by someone else
