### ISSUE TITLE
3.1.3.1 Figures' text description impropriate format and impropriate text color

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#754]
The figures of 3.11 text description("Erase non-data-ink and redundant data-ink" and " Erase non-data-ink and redundant data-ink")are on the top of the figures, which makes readers feel confused. Instead of putting on the top, the author should create a standard format and position for all figures text descriptions.

<img width="842" alt="Screen Shot 2019-04-04 at 1 21 59 PM" src="https://user-images.githubusercontent.com/40288420/55586704-778d7b00-56de-11e9-9738-1af81617ef76.png">
<img width="872" alt="Screen Shot 2019-04-04 at 1 24 08 PM" src="https://user-images.githubusercontent.com/40288420/55586708-78bea800-56de-11e9-8548-c98658d8d36c.png">

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L54
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L55

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L58
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L59

**Comment by jma4** [comment]
These two visualizations are located at 3.1.3.1 instead of 3.1.1. I think the author was trying to show two examples of "Erase non-data-ink and redundant data-ink" which is quiet intuited for me but I agree with you that to put the description would cause less misunderstandings.

**Comment by Cindyli0310** [comment]
Hi,
Thanks a lot for correcting me. I will revised it now. 
I agree the examples are very clear, but I just feel like the graph and text format is a little bit when reading it.

**Comment by Cindyli0310** [comment]
Revision Proposal:
1.Changing graph text description location:

- Putting text description below each graph but above source citation because it is easier for reader to read.  

- How to change in rmd: my conceptually thinking is that switching code position for both 'redundant data-ink"(line 54) and " Erase non-data-ink and redundant data-ink"(line 59)  with graphs. 

2. Changing graph text description text format:

- Changing figure text descriptions to a different color and bold it. Because many figure text descriptions in Reader chapters has light grey color, I will recommend 3.1.3.1 figures should change to a same color.
I searched one ' change font color code'  example on slackflow which is violets are <span style="color:blue">blue</span>. I will try to use it when writing the code.
