### ISSUE TITLE
4.7.1 invalid reference url

### ISSUE THREAD

**Issue by jma4** [mschermann/data_viz_reader#756]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/03-casestudies.Rmd#L275

The url provided in the reference is unable to reach the website.

**Comment by Marvin510** [comment]
I tried finding the original source but it seems to be gone. However, I did find other links with more information on " Muyueh Lee’s talk titled, Green Honey". 
http://www.reloade.com/blog/2014/02/talk-muyueh-lee-open-data-workshop-2013.php

**Comment by jma4** [comment]
The link that @Marvin510 provided is related to Muyueh Lee's work. However, the content and graph are not exactly  the same. For now, I keep this issue open and until I find other source or re-write the paragraph.
