### ISSUE TITLE
4.2.3 Graph does not fullly reflect features mentioned in the paragraph

### ISSUE THREAD

**Issue by 82817** [mschermann/data_viz_reader#758]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/03-casestudies.Rmd#L42-L57

In this paragraph, the author mentioned how Uber first optimized maps with detail, color, typography then added routes on top of the map. It also mentioned how Choropleths graphs (heat maps) are implemented. However, the graphs mentioned in the bottom only showed a single style of map. 

In the article that it referenced, there are additional graphs available that I believe will better depict the purpose of this article [
![image](https://user-images.githubusercontent.com/40615815/55594381-3e600580-56f4-11e9-88ab-129d00d844d7.png)
](url)

**Comment by Vidya313** [comment]
I agree suitable graphs can be added to represent the information presented in the paragraph.

**Comment by 82817** [comment]
Issue Closed, please refer to Pull Request #999
