### ISSUE TITLE
4.6.2---Wrong citation

### ISSUE THREAD

**Issue by XZou0803** [mschermann/data_viz_reader#759]
There is a wrong citation in 4.6.2 What’s really warming the world?
The paragraph only described the contents from Roston and Migliozzi 2015, no mention what's from Crooks 2017, so listing Crooks here is a misunderstanding.

![image](https://user-images.githubusercontent.com/31682566/55594577-fee5e900-56f4-11e9-9755-dcad24ec0524.png)

**Comment by jymhe120** [comment]
In the reference link for Crooks 2017, it does mention "What's really warming the world", below is a screenshot of it:
![image](https://user-images.githubusercontent.com/41307867/55701683-f6a5dc00-5988-11e9-8665-58da68a8e786.png)
The author might have drawn ideas from the description that's written by Crooks and thus gave him the citation. I don't think that it's a big issue including it there.

**Comment by XZou0803** [comment]
Thanks to Maria pointed out the suggestions! And I didn't notice that and totally agree with you.
I will close this issue.
