### ISSUE TITLE
4.8.1---Important Information are covered

### ISSUE THREAD

**Issue by XZou0803** [mschermann/data_viz_reader#761]
For the first graph in 4.8.1 Connecting the Dots Behind the Election, important information is overlapped by a meaningless block. It may be caused by the mistaking screenshot. 
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/03-casestudies.Rmd#L30
![image](https://user-images.githubusercontent.com/31682566/55595620-a36a2a00-56f9-11e9-89e0-2c9a3f2827d7.png)

**Comment by KlippL** [comment]
Professor Schermann showed me how to create an issue directly from the code, and I found it helpful:
https://help.github.com/en/articles/opening-an-issue-from-code
Hope you find it helpful too! 

Also, putting 4.8.1 in the title for searchability might be helpful to that people don't create a new issue for one that you have already found :-)

**Comment by XZou0803** [comment]
Thanks for the advice!

**Comment by Kushall-Dayal** [comment]
Here is a clear view of the image
sourced from: https://www.nytimes.com/interactive/2015/05/17/us/elections/2016-presidential-campaigns-staff-connections-clinton-bush-cruz-paul-rubio-walker.html

![V7](https://user-images.githubusercontent.com/49147275/55680465-b08c4200-58ce-11e9-8eff-d867a7935cc0.jpeg)

**Comment by XZou0803** [comment]
Thank you so much Kushall!

**Comment by XZou0803** [comment]
this problem has been solved.
