### ISSUE TITLE
4.9.9 --Graph hard to read

### ISSUE THREAD

**Issue by XZou0803** [mschermann/data_viz_reader#762]
The graph in 4.9.9 Goldilocks Exoplanets is vague and hard to read for readers as well as the publisher. 
![image](https://user-images.githubusercontent.com/31682566/55596045-977f6780-56fb-11e9-867b-eae939d246f1.png)
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/03-casestudies.Rmd#L425

**Comment by agrasonal** [comment]
I also noticed the same. However, the graph on the referenced website isn't opening either. What do you suggest we do about that?

**Comment by XZou0803** [comment]
Yes, I can' t find the original graph on the website either. So maybe there is a solution for sharp this picture in Photoshop.

**Comment by Cindyli0310** [comment]
Hi guys,
I also found the similar issue in other chapters, and I searched an interesting paper online to deal with vague graph. The paper includes some codes which can fix the vague problem in R, and hopefully it can be helpful for this question. 
https://thepoliticalmethodologist.com/2013/11/25/making-high-resolution-graphics-for-academic-publishing/

**Comment by XZou0803** [comment]
Thank you Cindy! That's very helpful!
