### ISSUE TITLE
Duplicate sections 2.4 & 2.7 for heading 'Contemporary Visualists' in chapter 2 #764

### ISSUE THREAD

**Issue by agrasonal** [mschermann/data_viz_reader#765]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L381

**Comment by phoenixren** [comment]
I noticed that too. I think it makes more sense to only keep 2.4 since it's more related to the history of data visualization.

**Comment by agrasonal** [comment]
I am closing this issue as this has been already taken care of.
