### ISSUE TITLE
Duplicate sections covering - 'Infographics vs Data Visualization' under section (2.6.4) & section (3.6.2) 

### ISSUE THREAD

**Issue by agrasonal** [mschermann/data_viz_reader#766]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L275

Duplicate sections covering - 'Infographics vs Data Visualization' in chapter 2 (2.6.4) & chapter 3(3.6.2) - needs to be removed from chapter 2 in order to maintain the context of section.

**Comment by strivedi2** [comment]
I agree. Just realized the same and I also believe that this sub-section makes more sense in Chapter 3 than Chapter 2.

**Comment by gauravhassija** [comment]
I agree! I feel the reference link in section 2.6.4 does not provide any concrete information as to when you should use either. I think they(Infographics and Data Visualization) should be used together to create effective visualizations.

**Comment by agrasonal** [comment]
Closing the issue as @mayjai is addressing this issue for week 4 #1072
