### ISSUE TITLE
In Chapter 3, need to remove section 3.4.1 ( Data mining vs Data Viz) and add it under section 3.6 to combine all special topics under one heading

### ISSUE THREAD

**Issue by agrasonal** [mschermann/data_viz_reader#767]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L383

**Comment by strivedi2** [comment]
I second that. The two different Special topics sub-sections are confusing.

**Comment by mayjai** [comment]
I agree, the duplicate titles are confusing. And besides, we don't need a subsection (3.4.1) under 3.4, since there's only one subsection under that section right now.

**Comment by gauravhassija** [comment]
I feel the title 'Special Topics' being repetitive, is confusing. I agree that they should be combined under one heading as their content is similar.

**Comment by agrasonal** [comment]
Closing this issue as changes have been merged into contributions.
