### ISSUE TITLE
5.3.6 Bar Charts: vague graph

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#769]
The graph is too vague and the words in the graph are hard to read.

<img width="520" alt="Screen Shot 2019-04-04 at 7 13 18 PM" src="https://user-images.githubusercontent.com/40288420/55599829-5e042780-570e-11e9-98c1-66e58d7d313c.png">

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L116

**Comment by VikitaNayak** [comment]
@Cindyli0310 Also, from the graph it is not very clear about the Year range. They just have mentioned Y1, Y2 etc. Same goes with the Y axis where it is not mentioned what those numbers are.

**Comment by Cindyli0310** [comment]
@VikitaNayak Hi,I am totally agree.It makes people feel really confused. The graph should have additional definition on what is X and Y axis.

**Comment by Cindyli0310** [comment]
I fixed the problem with updating a new graph. So I close the issue.
