### ISSUE TITLE
3.2 Best Practices-invalid ciation

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#770]
Need to fix the citation issue, whether need to add another citation or delete the questions mark citation.
<img width="814" alt="Screen Shot 2019-04-04 at 7 35 58 PM" src="https://user-images.githubusercontent.com/40288420/55600387-a886a380-5710-11e9-8b34-4341b2de0ca7.png">
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L143

**Comment by KlippL** [comment]
Professor Schermann showed me how to create an issue directly from the code, and I found it helpful:
https://help.github.com/en/articles/opening-an-issue-from-code
Hope you find it helpful too!

**Comment by Cindyli0310** [comment]
> Professor Schermann showed me how to create an issue directly from the code, and I found it helpful:
> https://help.github.com/en/articles/opening-an-issue-from-code
> Hope you find it helpful too!

Hi Laura, 
Thanks a lot for sharing the link, that is so helpful!

**Comment by agrasonal** [comment]
Correct reference link - https://datajournalismhandbook.org/1.0/en/understanding_data_7.html
