### ISSUE TITLE
Updating inconsistent sub-sections 2.2.4 - 2.2.6 (reader)

### ISSUE THREAD

**Issue by strivedi2** [mschermann/data_viz_reader#772]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/01-intro.Rmd#L48

Sections 2.2.4 -2.2.6 in the reader seem inconsistent given that the section talks about Importance of Data Visualization and these sub-sections are more focussed on use cases and drift away from the general theme of the sub-section. 
They can either be reorganized into a new subsection on use cases/ industry examples for visualization or added to a more relevant sub-section/ chapter.

**Comment by agrasonal** [comment]
I agree with you on that and strongly feel that a separate section on use cases would make a lot of sense. This would be important as data visualization plays a key role in decision making for any kind of business and addition of industry best practices would expose the reader to effectiveness of different data visualization techniques across different disciplines.

**Comment by strivedi2** [comment]
That's great to hear! Do you have a chapter of section in mind where a new sub-section on use cases might fit or would you consider creating a new chapter on use cases/ industry application of data visualization.

**Comment by agrasonal** [comment]
Maybe section 3.5 (Data visualization in Business) can be restructured and include use cases for different disciplines like - sales&marketing, finance, politics, healthcare, e-commerce, etc.

**Comment by XZou0803** [comment]
I agree for Agrasonal! 
But I think it might be better for adding them to 3.5 not for Chapter 4, because in Chapter 4, the author used lots of graphs(instances) to show in every sub-sections but this part seems leak of graphs currently.

**Comment by agrasonal** [comment]
> I agree for Agrasonal!
> But I think it might be better for adding them to 3.5 not for Chapter 4, because in Chapter 4, the author used lots of graphs(instances) to show in every sub-sections but this part seems leak of graphs currently.

I agree with you and meant the same. This is because chapter 4 already discusses a lot of use cases in detail. So, sub-section 3.5 which discusses broader categories like - sales&marketing, finance, politics, healthcare, e-commerce, etc., will link the two chapters in a better way.

**Comment by strivedi2** [comment]
The 

> Maybe section 3.5 (Data visualization in Business) can be restructured and include use cases for different disciplines like - sales&marketing, finance, politics, healthcare, e-commerce, etc.
> 
> This will seamlessly flow into chapter 4 - (Case Studies), where specific cases have been discussed in detail.

Yes! I have the same opinion after reading through section 3.5. The section currently is very brief in terms of industry use-cases and talks more about steps of creating data visualizations. 

- Specifically, the table in sub-section 3.5.1 can be substantially improved by adding more use cases and applications from across the different industries suggested in your comment.
- In sub-section 3.5.2, examples from some of these use cases can be added to improve quality of the original content and to also help tie it back to industry applications in 3.5.1. For example, under 3.5.2.1 Cleaning, an example can be added from any of the use cases on how cleaning can improve quality of data used for analysis and visualization.
-

**Comment by strivedi2** [comment]
I have assigned myself and @agrasonal to this issue. Feel free to add or remove. I have also added  milestone as Week 4 so that there is time to research and add relevant use cases in coming weeks and include examples in sub-section 3.5.2.

**Comment by strivedi2** [comment]
Added new pull request #1127 to include Use cases from an older pull request. Issue will be closed once they are approved.

**Comment by strivedi2** [comment]
Pull request merged into contributions.
