### ISSUE TITLE
Chap3-Unformatted reference citation 

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#773]
The reference citation format in Chap3 is not unify. As the following two citations : first one is not found , the second one is unclear where the source come from, is a book? Journal or Website?
<img width="724" alt="Screen Shot 2019-04-04 at 8 00 06 PM" src="https://user-images.githubusercontent.com/40288420/55601495-fb168e80-5715-11e9-98bc-4c1992c7f41a.png">
The author need to unify the citation format either by manually correction or using some online citation tool such as ‘Noodltools’ to make it unity.
Noodletools link:
https://www.noodletools.com/

**Comment by harizhisham** [comment]
Seems like references are an issue throughout the entire data viz reader. The first link could just be out-of-date. 

I've added the 'reference issue' label so others can pick up on this as well.

**Comment by Cindyli0310** [comment]
@harizhisham Hi, I feel the reference issue here is much clearer. Thanks a lot for adding on the label.
