### ISSUE TITLE
Section 2.2.2 remove random serial number 3 at Line 41

### ISSUE THREAD

**Issue by srivasud** [mschermann/data_viz_reader#774]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/01-intro.Rmd#L41

The below sentence in Section 2.2.2 has a spurious serial number 3.
"3. It can reveal interesting small patterns–“Data detective.”"
This "3" needs to be removed or list David McCandless quotes as list of points serially numbered.

**Comment by jma4** [comment]
I think it is a redundant sentence. I also tried to look at McCandless' ted talk through the reference link and it turned out that the video or content is no longer exist. We might need to put a valid url to the reference.

**Comment by srivasud** [comment]
This issue is already addressed by a different issue. I do not find this issue relevant anymore in contributions branch. Hence closing this issue.
