### ISSUE TITLE
Restructure and expand section 5.3 (chapter5)

### ISSUE THREAD

**Issue by agrasonal** [mschermann/data_viz_reader#775]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L77

Chapter 5:
Section 5.3.1: Can be reworked to explain what to ask when deciding which type of chart to use (Reference - https://blog.hubspot.com/marketing/types-of-graphs-for-data-visualization)

Section 5.3.2: Can be expanded to include the common types of data visualizations as sub-sections namely Charts, Tables, Graphs, Maps, Infographics, Dashboards (Reference - https://www.tableau.com/learn/articles/data-visualization). This would include clubbing the sections 5.4, 5.8, 5.9 as sub-sections into the above mentioned section.

**Comment by shriya22** [comment]
Yes I completely agree with you.It would help to get more information about which charts to use. I also found this 'chart suggestions' image which can help us get a general understanding of which chart is more suitable for a particular data type.
![image](https://user-images.githubusercontent.com/47867865/55651998-1ed1e700-579f-11e9-84e9-5c1a243bb09b.png)
source: https://eazybi.com/blog/data_visualization_and_chart_types/

**Comment by agrasonal** [comment]
I  totally agree. This would help give a better understanding of which chart types to use as per changing needs.

**Comment by pragyansharma24** [comment]
> Yes I completely agree with you.It would help to get more information about which charts to use. I also found this 'chart suggestions' image which can help us get a general understanding of which chart is more suitable for a particular data type.
> ![image](https://user-images.githubusercontent.com/47867865/55651998-1ed1e700-579f-11e9-84e9-5c1a243bb09b.png)
> source: https://eazybi.com/blog/data_visualization_and_chart_types/

**Comment by bharatimalik** [comment]
> Yes I completely agree with you.It would help to get more information about which charts to use. I also found this 'chart suggestions' image which can help us get a general understanding of which chart is more suitable for a particular data type.
> ![image](https://user-images.githubusercontent.com/47867865/55651998-1ed1e700-579f-11e9-84e9-5c1a243bb09b.png)
> source: https://eazybi.com/blog/data_visualization_and_chart_types/

I really liked the heading and the content of this image!

**Comment by agrasonal** [comment]
In oder to expand this section, I would recommend the following:

Section 5.3.1: What is the purpose of visualization?
_(Reference - https://blog.hubspot.com/marketing/types-of-graphs-for-data-visualization)_
- Comparison: Displays how two variables interact with each other 
- Composition: Displays how individual parts make up the whole of something
- Distribution: Helps to understand outliers, the normal tendency, and the range of values
- Relationship: Show a connection or correlation between two or more variables

Section 5.3.2: How to decide which chart type to use?

- Tables: Used when there are only few variables and data points
- Column Charts (Histograms, Stacked Column Charts, Bar Charts, Stacked Bar Charts) : Used to compare values for different categories or compare value changes over a period of time for a single category
- Line Charts: Used for trend-based visualizations of data over a period of time
- Area Charts: Essentially a line chart, used for presenting accumulative value changes over time
- Pie Charts: Used to visualize a part to whole relationship or a composition
- Scatter Plots:

**Comment by Psharma2193** [comment]
This will be a great addition to the reader!

**Comment by pragyansharma24** [comment]
Yes, I agree. Section 5.3 needs restructuring.
Also, adding the chart suggested by @shriya22 is a good idea as it clear and concise.

**Comment by agrasonal** [comment]
Closing the issue as the following has been completed and merged into master branch:
- Section 5.3.1: What makes a visualization effective?
- Section 5.3.2: How to decide which chart type to use?
