### ISSUE TITLE
4.8.1 visual instruction is partially bloacked

### ISSUE THREAD

**Issue by jma4** [mschermann/data_viz_reader#776]
The instruction on the bottom left is partially blocked and needed to be removed.

![img](https://user-images.githubusercontent.com/46701809/55606395-7899c900-572d-11e9-8007-401cdcc2643d.JPG)

**Comment by XZou0803** [comment]
Hi, I think we mentioned the same issue here. 
[https://github.com/mschermann/data_viz_reader/issues/761](url)

**Comment by jma4** [comment]
oh thanks, I probably missed it.
