### ISSUE TITLE
Unaddressed Title 

### ISSUE THREAD

**Issue by Vidya313** [mschermann/data_viz_reader#778]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L41

**Comment by srivasud** [comment]
Hi, 
I have issue logged to track this issue[https://github.com/mschermann/data_viz_reader/issues/774]
on the same exact line number.
Your issue is duplicate of #774.

**Comment by Vidya313** [comment]
Closing the issue as it is a duplicate of #774
