### ISSUE TITLE
Section 3.3.7 duplicate listing of key advantages of Tableau- remove one

### ISSUE THREAD

**Issue by srivasud** [mschermann/data_viz_reader#779]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/02-fundamentals.Rmd#L373

Remove one of the duplicate listing of key advantages of Tableau - especially remove Line#373

**Comment by mayjai** [comment]
Agreed, this clearly is a mistake. Also agreed that we should keep the number listed version, since that version makes the information more clear.
