### ISSUE TITLE
5.9 Dashboards - Missing Reference/Citation

### ISSUE THREAD

**Issue by Marvin510** [mschermann/data_viz_reader#781]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L443

Proper Citation needed

**Comment by Cindyli0310** [comment]
Hi Marvin,
I really agree that the author should add the citation/reference.
I also found this paragraph is actually from several different websites. Here are the two links related to "Generating Word Cloud in Python" and "Image-colored wordcloud" which authors used in the article. 

I rewrite the reference as below:

"Generating Word Cloud in Python." GeeksforGeeks, www.geeksforgeeks.org/ 
     generating-word-cloud-python/. Accessed 6 Apr. 2019. 

Mueller, Andreas. "Image-colored wordcloud." amueller.github.io, 2019, amueller.github.io/word_cloud/ 
     auto_examples/colored.html. Accessed 6 Apr. 2019.
