### ISSUE TITLE
5.10.1 Missing Link to article

### ISSUE THREAD

**Issue by Marvin510** [mschermann/data_viz_reader#782]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L476

Missing Link to article

**Comment by jymhe120** [comment]
Here's the reference link for this article and can be added to the reference later to fill this missing link: https://www.tableau.com/about/blog/2016/2/how-use-custom-shapes-filters-your-dashboard-50200

**Comment by Marvin510** [comment]
This issue has been resolved in another pull request.
