### ISSUE TITLE
7. Conclusion - Restructuring of last chapter

### ISSUE THREAD

**Issue by Marvin510** [mschermann/data_viz_reader#784]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/06-conclusion.Rmd#L1

Chapter 7 is supposed to be a concluding chapter. However, it incorporates sections that can be chapters on their own or should not form part of a conclusion.

Section 7.1 "The future of data visualization" can be a chapter on its own.
Section 7.2 "Key lessons going forward" is more of a cheat sheet of Must-Dos.
Section 7.3 "Blogs" is useful links and resources, not related to any conclusion.

The final chapter of this reader should either bring all previous chapters together as one to reinforce an idea, serve as a tool or evoke action in the reader's mind. As it stands, it does not accomplish anything.

**Comment by Kushall-Dayal** [comment]
I agree with your point ,I found the conclusion rather unsatisfactory .And section 7.3 and section 2.6 are the same

**Comment by Marvin510** [comment]
Solution:
- Remove duplicate section 7.3 from chapter 7
- Place 7.1 "The future of data visualization" in a new chapter
- Remove section 7.2 "Key lessons going forward" and merge with section 7.1 in another chapter
- Re-write the concluding chapter by bringing all previous chapters together as one to reinforce an idea, serve as a tool or evoke action in the reader's mind.

**Comment by VikitaNayak** [comment]
@Marvin510 Even I noticed the duplication of section 7.3. Also, Summary should be included in this chapter so that after reading the entire book readers will not forget what they read.

**Comment by Marvin510** [comment]
#1099  will address this issue
