### ISSUE TITLE
Section 6.6 the content does not seem to belong in "Data Ethics" chapter

### ISSUE THREAD

**Issue by srivasud** [mschermann/data_viz_reader#785]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/05-ethics.Rmd#L96-L105

The entire content in section 6.4 "A Tool for Social Change in Cities" more seem to fit in Case studies rather than in data ethics chapter.

**Comment by XZou0803** [comment]
I think maybe the author considered the city develop as progress for democracy. But it is also nice to be removed to case study cause it is based on a case and not obviously for ethics!
And here is an article about ethics and visualization, if you are interested in this chapter, hope it will be helpful
[https://repository.asu.edu/attachments/194100/content/OBrien_asu_0010N_17523.pdf](url)

**Comment by 82817** [comment]
I'm not sure if we have the same version, but "A Tool for Social Change in Cities" shows up as section 6.6 for me.

**Comment by preranap1** [comment]
The section "A Tool for Social Change in Cities" shows as 6.6 for me too but it is in the broader Ethics section. I think that is what is being discussed here.
Also, the citation is missing for this section. 
Could it be this: https://medium.com/@mateoneira/data-visualization-a-tool-for-social-change-cefb02b7ce4a

**Comment by srivasud** [comment]
Thanks guys for pointing out section 6.6. I corrected the subject line to reflect section 6.6

**Comment by srivasud** [comment]
This issue is already fixed and merged into contributions branch [pull request # data_viz_reader_785]
