### ISSUE TITLE
Section 6.8 Can we add a concluding note whether Coxcomb diagram is ethical

### ISSUE THREAD

**Issue by srivasud** [mschermann/data_viz_reader#786]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/05-ethics.Rmd#L140

Since this is present in "Data Ethics" chapter, would like to see a conclusion about Coxcomb diagram whether it is "Data Ethical" or not?

**Comment by preranap1** [comment]
I think the section "Misinformation can be beautiful" is included in the reader to make us understand that visualizations make a powerful impact and what the reader sees could be a part of a bigger story the creator decided to focus on in that particular graph/chart. 
It goes back to the three main components of effective visualizations we identified in class: Audience, Chart & Argument.

**Comment by srivasud** [comment]
Thanks for your comments. My point is, Coxcomb chart is an important design pattern that should find its mention under section 5.3. I think the author's motivation to present under "Data Ethics", especially the famous Coxcomb statistical chart is to drive the point that even though the charts may portray mis information it could be regarded ethical (and of course beautiful) for moral reason that lives could be better saved with improved sanitation.

**Comment by preranap1** [comment]
agreed!

**Comment by srivasud** [comment]
The following paragraph in that section 6.7 is clear and gives an understanding. We need not explicitly state whether this Coxcomb is ethical. It's left to the reader to infer that this is ethical since it was designed for a moral ethical good.

"Those beautiful Coxcomb diagrams are no exception. They show the causes of mortality in the Crimean war, and make a powerful case that better hygiene saved lives. But Hugh Small, a biographer of Nightingale, argues that she chose the Coxcomb diagram in order to make exactly this case. A simple bar chart would have been clearer: too clear for Nightingale’s purposes, because it suggested that winter was as much of a killer as poor hygiene was. Nightingale’s presentation of data was masterful. It was also designed not to inform but to persuade. When we look at modern data visualizations, we should remember that."

**Comment by srivasud** [comment]
Hence I decided to leave it as is (no fix needed here).
