### ISSUE TITLE
Section 6.9.5 missing graph

### ISSUE THREAD

**Issue by srivasud** [mschermann/data_viz_reader#787]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/05-ethics.Rmd#L190

The contents talks about graph Times sales vs its competitor. I do not see a reference to the graph (graph is missing)

**Comment by agrasonal** [comment]
Hi srivasud, I think the missing graphs can be found here:

The links - (Robbins 2011) & (Robbins 2012) in the section 6.9.6  and section 6.9.7 are broken and leading to 404 pages. The correct reference images can be found at: 

6.9.5 The Missing Baseline: https://www.statisticshowto.datasciencecentral.com/misleading-graphs/ 

6.9.6 The Graph is not Labeled Properly: https://www.forbes.com/sites/naomirobbins/2012/02/28/misleading-graphs-displaying-a-change-in-one-variable-using-area-or-volume/#4392dbb71781

6.9.7 Data is Left Out: https://www.forbes.com/sites/naomirobbins/2011/11/17/whats-wrong-with-this-graph/#79d7a8de2a33

**Comment by srivasud** [comment]
Thanks!

**Comment by srivasud** [comment]
Solution:-
========
A) Fix 6.9.5 missing base line graph

1. Will download the image from 
https://www.statisticshowto.datasciencecentral.com/wp-content/uploads/2014/01/misleading-graph-2.jpg and add this file to https://github.com/mschermann/data_viz_reader/tree/master/images
2. Refer this image in the section 6.9.5 as 
<img src="images/misleading-graph-2.jpg" alt="Misleading Graphs: The Missing Baseline">
3. Add a citation for this "Missing baseline" image as follows:
@misc{missing_base_line,
  author={Stephanie},
  year={2014},
  title = {Misleading Graphs: Real Life Examples},
  url={http://www.statisticshowto.com/misleading-graphs/},
  note = {Accessed: 2019-04-06}
}

and refer this as [@missing_base_line]
B) Incorrect URI in the citation for Section 6.9.6 

Fix the URI in the reference
Wrong href: 
<a href="https://www.forbes.com/sites/naomirobbins/2012/02/16/misleading-graphs-figures-not-drawn-to-scale/{\#}351dcf9c15ef" class="uri">https://www.forbes.com/sites/naomirobbins/2012/02/16/misleading-graphs-figures-not-drawn-to-scale/{\#}351dcf9c15ef</a>

Correct URI:
https://www.forbes.com/sites/naomirobbins/2012/02/28/misleading-graphs-displaying-a-change-in-one-variable-using-area-or-volume/#4392dbb71781
C) Broken links at the reference/citation for section 6.9.7
The correct URL is  https://www.forbes.com/sites/naomirobbins/2011/11/17/whats-wrong-with-this-graph/#79d7a8de2a33

**Comment by srivasud** [comment]
Discussed with Professor Michael on this, i will log a separate issue for section 6.9.7

**Comment by srivasud** [comment]
We have separate issues tracking section 6.9.6 and 6.9.7
