### ISSUE TITLE
2.6.4.3 and 2.6.2: tables can be formatted for better readability

### ISSUE THREAD

**Issue by strivedi2** [mschermann/data_viz_reader#788]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/01-intro.Rmd#L246 
Description column in the above table can be formatted to improve readability and utilize real estate on the page better.

https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/01-intro.Rmd#L290
Same holds for rationale column in the above table.

**Comment by strivedi2** [comment]
Section 2.6.4 Infographics vs Data Utilizations is repeated again in Chapter 3 section 3.6.2 under Special Topics. Section 2.6.4 can be removed which will also take care of the formatting issue.

**Comment by pragyansharma24** [comment]
I also noticed there are some format issues in the tables given in 7.1. 

![image](https://user-images.githubusercontent.com/45728559/55679060-3ef5c900-58b9-11e9-81b4-e2adfd6e2653.png)

**Comment by Vidya313** [comment]
I agree, the tables require better formatting to improve readability.

**Comment by gauravhassija** [comment]
Along with formatting issues, the table in section 2.6.3 has missing references

![image](https://user-images.githubusercontent.com/49177935/55702799-9153ea00-598c-11e9-8466-e0cc05a25d96.png)

**Comment by strivedi2** [comment]
Section removed in pull request #1060. Tables now available under section 7.3
