### ISSUE TITLE
Content Proposal for 3.2.3 Analyze and Interpret data visualizations

### ISSUE THREAD

**Issue by strivedi2** [mschermann/data_viz_reader#789]
The section on Analyzing and Interpreting data visualizations seems very brief. Given the relevance of this topic, the section can include more details. After all, analysis and ability to interpret a visualization is the essence of any data visualization project.

https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/02-fundamentals.Rmd#L163

**Comment by XZou0803** [comment]
Maybe we need to add some good instances for the questions:
What can be seen in this image? Is it what that was expected?
Are there any interesting patterns?
What does this mean in the context of the data?

Like for Q2, Plot is better for finding patterns.

**Comment by preranap1** [comment]
Great suggestion!
We can include best practices for visual analytics. 
Here is a link that can be referenced: http://www.dataplusscience.com/files/visual-analysis-guidebook.pdf

**Comment by mayjai** [comment]
Agreed on more detail needed. Also, right now 3.2.3.1 seems to have unnecessary index, since there's only one subsection under 3.2.3.

**Comment by strivedi2** [comment]
> Agreed on more detail needed. Also, right now 3.2.3.1 seems to have unnecessary index, since there's only one subsection under 3.2.3.

Agreed!

**Comment by strivedi2** [comment]
> Great suggestion!
> We can include best practices for visual analytics.
> Here is a link that can be referenced: http://www.dataplusscience.com/files/visual-analysis-guidebook.pdf

That's a great resource! Thanks for sharing. It will definitely help to get started on the section. I'm also interested in learning more about this topic as we go through the class and maybe that can also help add content to this section.

**Comment by strivedi2** [comment]
This is a formal structured proposal for the section on Analyze and Interpret Data Visualizations.

Section 3.2 has very brief content. This section can be explained with more details on chart selection for analysis problems in data visualization. Moreover, the section on Analyzing and Interpreting data visualizations seems to be missing a few details. Given the relevance of this topic, the section can include more details. After all, analysis and ability to interpret a visualization is the essence of any data visualization project.

A new sub-section on Evaluate Your Charts will be added: This will contain guidelines or parameters to evaluate charts/ visualizations. The following high-level guidelines or parameters will be added:
- Identifying problems and checking if the visualization is answering the intended questions
- How effective are chart views in terms of measures & dimensions, colors, etc.
- Does the Dashboard have a holistic design
- Points to review before finalizing the visualization

A quick 6 step approach to interpreting visualizations.

References:
http://www.dataplusscience.com/files/visual-analysis-guidebook.pdf
https://www.methodspace.com/tips-on-interpreting-data-visualizations/

**Comment by preranap1** [comment]
This seems like a good and a well thought through plan.

**Comment by gauravhassija** [comment]
The addition is great! The new content will certainly help in making effective visualizations,

**Comment by strivedi2** [comment]
Content updated in PR #1181
