### ISSUE TITLE
Section 2.1 Ambiguous (???) in Information visualization section

### ISSUE THREAD

**Issue by shriya22** [mschermann/data_viz_reader#790]

**Comment by 82817** [comment]
I've noticed the same issue. I tried to look up the same paragraphs online but didn't find any. Also, the way the parentheses are placed is wrong as well.

**Comment by bharatikandakumar** [comment]
The same issue caught my eye. I think there is a missing link.

**Comment by phoenixren** [comment]
I think it might be a missing citation source.

**Comment by Psharma2193** [comment]
I too have noticed the same issue at multiple places. Like - Section 3.2(pg 45), 3.3.2 (pg 49), 3.7(pg 64). I agree, issue seems to be because of citation

**Comment by pragyansharma24** [comment]
Hi Shriya,
I have created a list of citation issues with ??? in all the chapter. 
So, I am marking it as closed.
