### ISSUE TITLE
Section 2.2.5 : Starting from the 5th paragraph, there is no connection with the title 'Law enforcement and fraud detection'

### ISSUE THREAD

**Issue by shriya22** [mschermann/data_viz_reader#791]
From the 5th paragraph, the criteria that data visualization has to satisfy is provided.Hence I would suggest to create this as a separate section itself which basically summarizes and concludes the importance of data visualization.
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L71-L91

**Comment by XZou0803** [comment]
I think you can create an issue directly from the code:
https://help.github.com/en/articles/opening-an-issue-from-code
If you already created this issue, you can just edit it and add the LINK URL(generated by creating a new issue) for the code.
Hope you find it helpful!

**Comment by agrasonal** [comment]
I agree with shriya.

We are discussing the same issue here - (Inconsistent sub-sections 2.2.4 - 2.2.6 (reader) #772), removing subsections 2.2.4, 2.2.5, 2.2.6 and instead creating a revised section in chapter 3 where we can include all use cases at one place.

**Comment by shriya22** [comment]
Oh yes thank you, I didn't realize the issue is already present.

**Comment by 82817** [comment]
I've noticed the same problem as well. I'd also add that the second paragraph diverged from the theme of this section as well.

**Comment by shriya22** [comment]
And thank you Nina Zou that was very helpful

**Comment by gauravhassija** [comment]
I think the 5th paragraph is a bit repetitive and can be omitted. The text is similar to that from section 2.2.1

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L80

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L34

Last few sentences are same.

**Comment by shriya22** [comment]
I am closing this issue as I can see that is has already been resolved in the reader
