### ISSUE TITLE
section 5.3.9 and 5.3.10: Misplaced image for stream graph

### ISSUE THREAD

**Issue by shriya22** [mschermann/data_viz_reader#793]
![aya-stream](https://user-images.githubusercontent.com/47867865/55648193-82a2e280-5794-11e9-8caa-afb18039315b.png)

This is the stream graph ,which is wrongly present in the heat map section 5.3.10.Hence i would suggest that this image has to be moved from heat map section to the stream graph section
source: https://en.wikipedia.org/wiki/Streamgraph

**Comment by harizhisham** [comment]
Good catch. I agree with moving the graph up to 5.3.9, since that section is missing a graph entirely.
