### ISSUE TITLE
Section 2.3.1 : The general statement about history seems inappropriate under the title 'Brief History'  

### ISSUE THREAD

**Issue by Vidya313** [mschermann/data_viz_reader#794]
Moving the statement under the main heading under general section ' 2.3 History of Data Visualization ' would make more sense.

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L100

**Comment by shriya22** [comment]
Yes I completely agree and adding to that i would also suggest to rename the next section(Data Visualization: A Modern Product?) as brief history,as it contains the time,phase and description of data visualization

**Comment by Vidya313** [comment]
Fixed the issue merged the changes, hence closing the issue
