### ISSUE TITLE
Section 2.5 : Inappropriate title

### ISSUE THREAD

**Issue by Vidya313** [mschermann/data_viz_reader#795]
The section consists of  a set of examples, but title begins as 'An example ..'  hence requires to be changed as 'Examples to back...' or any better title. It would be good to have a shorter title.
  
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L173

**Comment by Cindyli0310** [comment]
Hi,
I totally agree with you. Shorter title is easier for people to read and understand.

**Comment by btamsir** [comment]
Yes! It would be much better to have a more concise title such as, "Validating Theories, Visual Stories, and Exploratory Visualization.

**Comment by Psharma2193** [comment]
True, the title is confusing. I agree with what @Cindyli0310 suggested. We can also shorten it to: How to tell stories using Data Visualization.

**Comment by Vidya313** [comment]
The issue is resolved in the pull request https://github.com/mschermann/data_viz_reader/commit/7c66017f2d1a0291fedf139b34a988fa5a9a4291
hence closing the issue.
