### ISSUE TITLE
Section 2.5 : The numbering of the sections is not uniform throughout  the document

### ISSUE THREAD

**Issue by Vidya313** [mschermann/data_viz_reader#796]
Examples can be numbered as 2.5.1 and so on.

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L175

**Comment by Qing0608** [comment]
I agreed, it's better formatting the same as other chapters, like 2.5.1, 2.5.2, 2.5.3 and so on.

**Comment by Vidya313** [comment]
Issue is being handled in another  issue #849 , hence marking this issue duplicate and closing .
