### ISSUE TITLE
Section 6.1: Improper explanation of guidelines 

### ISSUE THREAD

**Issue by preranap1** [mschermann/data_viz_reader#798]
The third paragraph of section 6.1 addresses four guidelines applicable in information gathering field.
Here the bullets are not in the right format. Also, they don't seem to be guidelines really and hence can be better structured. 

https://mschermann.github.io/data_viz_reader/ethics.html

**Comment by jacksonh2** [comment]
Hi, I no longer see the paragraph you are mentioned about when the issue was first opened. Please verify that this is still an issue, or else close the issue. Thanks.

**Comment by preranap1** [comment]
Hi, This issue has been dealt with and can be closed.
