### ISSUE TITLE
Section 6.2 Table heading missing. Information out of context

### ISSUE THREAD

**Issue by preranap1** [mschermann/data_viz_reader#799]
Section 6.2 talks about the implication of Good/Bad Data Visualization. 
The table at the end of the paragraph seems out of place. 

https://mschermann.github.io/data_viz_reader/ethics.html

**Comment by srivasud** [comment]
I agree that the contents of subsection 6.2 is irrelevant to the title. 
I think, this subsection title "Implication of good/bad visualization" may be more appropriate under special topics (section 3.4 or section 3.6).

**Comment by syragrg** [comment]
Subsection 6.2 actually does not even touch on the implications of good or bad data visualization but more on why using visuals to present data is powerful and the benefits that comes with using visuals(easy to recall etc). The title of the subsection should be changed or as Srivasud mentioned, it should be placed under other appropriate subsection.

**Comment by preranap1** [comment]
this issue has been taken care of by including a new subsection 6.3.3 Design and the table has also been properly labeled as ways of creating distorted graphs. Hence this issue is being closed.
