### ISSUE TITLE
Section 2.6.1 : Adding some introduction about Tableau will be a helpful addition.

### ISSUE THREAD

**Issue by Vidya313** [mschermann/data_viz_reader#800]
Adding content about Tableau and reorganization of the section 2.6.1 will be good enhancement.

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L227

**Comment by KlippL** [comment]
I agree... Tableau is so important for any line of work we will go into, and there seems to be a lack of material in the reader about it. 
In my comment: Expand section 5.10 #753
I also want to expand the information about how to do certain things in Tableau. 

Hopefully, together we can add much more detail about Tableau.

**Comment by Vidya313** [comment]
Sure , we can collaborate and work on expanding the content on Tableau.

**Comment by Vidya313** [comment]
This issue is being addressed in another issue #753 hence marking this issue as duplicate and will keep it open till the issue is fixed through #753.

**Comment by KlippL** [comment]
Thanks for working on this with me, I'm thinking we can close the issue now if that's ok.
