### ISSUE TITLE
6.8 References can be added

### ISSUE THREAD

**Issue by preranap1** [mschermann/data_viz_reader#801]
This section can be made more informative. 
In the Section: Misinformation can be beautiful too, the author shares some examples of visualizations are beautiful but do not convey enough meaning. Currently, there are separate paragraphs explaining these examples. I believe links to the actual examples will help drive the point better and stronger. My suggestion is to include links as references to these examples especially the New Yorker's Inequality and Subway graph and David McCandless’s “Debtris” animation 

https://mschermann.github.io/data_viz_reader/ethics.html#misinformation-can-be-beautiful-too

**Comment by preranap1** [comment]
Here are the links to the suggested examples that can be added to the reader:

1. New Yorker's Inequality and Subway graph: https://projects.newyorker.com/story/subway/

2. David McCandless’s “Debtris” animation: https://informationisbeautiful.net/2010/debtris/
https://www.youtube.com/watch?v=K7Pahd2X-eE

**Comment by srivasud** [comment]
Hi,
There is another issue [https://github.com/mschermann/data_viz_reader/issues/786] related to the same exact section. Just an information. I think of all the few examples discussed there, Coxcomb chart/diagram pattern is important and more appropriate in Chart section or the least add an argument that Coxcomb apart from being beautiful the information is ethical.
Thanks!

**Comment by preranap1** [comment]
yes, issue 786 is related to the same section. But issue 786 is addressing the coxcomb diagram while this one is not. Hence I think its good to keep them as separate issues.

**Comment by preranap1** [comment]
The issue is being closed as it was addressed in my earlier pull requests.
