### ISSUE TITLE
Section 5.7.1 and 5.7.2: very similar takeways

### ISSUE THREAD

**Issue by shriya22** [mschermann/data_viz_reader#802]

**Comment by pragyansharma24** [comment]
When I read the reader I felt the same but after going through the source link : 
[https://source.opennews.org/articles/what-i-learned-recreating-one-chart-using-24-tools/]
I realized that both points are different.

Section 5.7.1 is talking about the "AUDIENCE" and "ARGUMENT" - what is the goal of the creator.
while section 5.7.2 is talking about the "CREATOR" i.e. the person, who is making those graph, what is their mindset and what tools they are comfortable using.

**Comment by Vidya313** [comment]
I agree with Pragyan; they are two different topics. However, editing the titles or the content suitably would address it more clear and avoid the confusion.

**Comment by shriya22** [comment]
I am closing this as the pull request has been reviewed and approved
