### ISSUE TITLE
Section 7.2: Grammatical Mistakes

### ISSUE THREAD

**Issue by preranap1** [mschermann/data_viz_reader#803]
There are glaring grammatical errors in this section. Especially in the bullet 'Think as author/reader', the sentence formation is wrong with incorrect tenses, etc. This paragraph can be re-written.

https://mschermann.github.io/data_viz_reader/conclusion.html#key-lessons-going-forward

**Comment by Cindyli0310** [comment]
Hi,
Rather than putting a link here, you can use https://help.github.com/en/articles/opening-an-issue-from-code to create an issue in rmd based on the specific line. I think it is much easier to edit or revise. 
Cindy

**Comment by preranap1** [comment]
Hi Cindy,
Thank you for the suggestion. Since it was mentioned that technical issues should be code based I did not include the rmd file link here. Also, grammatical issues are easier to detect in text/link I feel. In any case here is the link to the line of code. Hope this helps :)

https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/06-conclusion.Rmd#L53

Best,
Prerana

**Comment by shriya22** [comment]
Yes I noticed that as well and adding to that, the next line also has grammatical errors and is confusing.
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/06-conclusion.Rmd#L55
