### ISSUE TITLE
Addition of new sub-section in conclusion

### ISSUE THREAD

**Issue by preranap1** [mschermann/data_viz_reader#804]
"Laying the groundwork for data visualization" can be made as a separate section as it does not fall under the "Key Lessons Going Forward" section that it is a part of now

https://mschermann.github.io/data_viz_reader/conclusion.html#key-lessons-going-forward

**Comment by preranap1** [comment]
The next header "How Is It Being Used?" can also be made into a separate sub-section. 
The name "How Is It Being Used?" is ambiguous too. A suggestion would be to change it to something along the lines of "How Businesses use Visualizations" would be more appropriate as it gives context to what will be addressed in the coming paragraphs.

Not sure what "(SAS NA)" means just below the header. Is that an indication of a missing reference?

**Comment by pragyansharma24** [comment]
Yes @preranap1,  (SAS NA) means the citation/ reference is missing.

**Comment by preranap1** [comment]
Thanks @pragyansharma24 for confirming...will look into this when trying to resolve this issue.

**Comment by mschermann** [comment]
@preranap1 can this be closed?
