### ISSUE TITLE
Section 3.3.3   Inappropriate content

### ISSUE THREAD

**Issue by Vidya313** [mschermann/data_viz_reader#805]
The title refers to python tool but the content mentioned is about the d3.js  . Suspect content is misplaced in this section.

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L253

**Comment by 82817** [comment]
I believe you are correct, the content does not seem to relate to this section at all. I'd suggest replacing that paragraph with the paragraph from the referenced link: 
"_Scroll through the Python Package Index and you'll find libraries for practically every data visualization need—from GazeParser for eye movement research to pastalog for realtime visualizations of neural network training. And while many of these libraries are intensely focused on accomplishing a specific task, some can be used no matter what your field._ (Bierly [2016](https://mode.com/blog/python-data-visualization-libraries))

**Comment by shriya22** [comment]
Yes I suspect that too. d3.js is a tool for visualizing data, but I couldn't find any connection to python as well

**Comment by kwright76** [comment]
Agreed, the information should flow and relate to each other. If something other than python such as d3 is mentioned it should be introduced as such.

**Comment by phoenixren** [comment]
Yes, it seems a bit odd to have a single paragraph about D3 without any other tools.

**Comment by Vidya313** [comment]
The issue is fixed and merged hence closing the issue.
