### ISSUE TITLE
Section 2.2.1 unnecessary bold font

### ISSUE THREAD

**Issue by 82817** [mschermann/data_viz_reader#806]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L34-L38

Not sure why the text of the author being referenced is bolded. This also occurs in 2.2.2. If the purpose of bolding is to emphasize the importance of the author, it might help to add an additional sentence or two to give the reader some background on the author and why he/she is important.

**Comment by Cindyli0310** [comment]
Hi,
I also noticed this issue, and actually I feel it is a little bit annoying. There are many different chapters has similar issue. For example, 2.5.3 paragraph also bold the first sentence of first paragraph and last sentence on the second paragraph which I feel a little bit confused when reading it. 
<img width="806" alt="Screen Shot 2019-04-05 at 7 23 10 PM" src="https://user-images.githubusercontent.com/40288420/55663822-8f492a00-57d8-11e9-9ac9-ce788d94c420.png">

**Comment by AayushiVAgrawal** [comment]
The first paragraph in the third subheading of article 2.5 is highly confusing. Automatic visualization should be done or not is unclear.

**Comment by rlwy** [comment]
Issue was resolved in PR #942
