### ISSUE TITLE
Section 2.2.4 poorly phrased sentence

### ISSUE THREAD

**Issue by 82817** [mschermann/data_viz_reader#807]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L52

In section 2.2.4, the last sentence in the first paragraph is exceedingly long. It mentioned multiple benefits using a different format (more...better...better) while mixing lots of "and" and commas. This creates confusion for the reader to not be able to clearly identify one benefit from another.

Since this is directly cited from the original document, we can consider paraphrasing or get rid of the sentence completely.

**Comment by kwright76** [comment]
To paraphrase I suggest the following.

Efficient performance monitoring, patient data management, and operational business planning are each expected results of decisions made from visualizations in the healthcare industry.

**Comment by btamsir** [comment]
I agree. There are multiple run-on sentences which are grammatically untenable especially the second one.

**Comment by 82817** [comment]
Issue fixed (pull request #807)
