### ISSUE TITLE
2.2.2. Misplaced Content

### ISSUE THREAD

**Issue by bharatikandakumar** [mschermann/data_viz_reader#808]
This sentence should belong in 2.2.3. And the number 3 has to be removed
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L41

**Comment by shriya22** [comment]
Yes i noticed that as well, and I would suggest it to be completely removed as the same is already given in 2.2.3

**Comment by bharatikandakumar** [comment]
This issues has already been fixed
