### ISSUE TITLE
Content in Section 6.4 is a better fit in other subsections

### ISSUE THREAD

**Issue by 82817** [mschermann/data_viz_reader#809]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/05-ethics.Rmd#L58-L84

The first paragraph in section 6.4 repeats a lot of concepts introduced earlier in the Ethics chapter. Even though Data Deception is a new term introduced, the concepts are again similar to what was already introduced to the audience. 

I believe it'll be more powerful to slice some of the information and spread it out to 6.1, 6.2 and 6.3. More specifically, the table under 6.4 fits well in 6.2 where the implication of bad Data Visualization is not mentioned explicitly. The first paragraph can go to 6.3 and the rest can fit in 6.2.

**Comment by srivasud** [comment]
1. I think the first two lines in the first paragraph has repetitive information. It can be removed!
2. This section 6.4 defines formally "Data deception" and principles of graph integrity. Other than the first paragraph the rest of the contents in section 6.4 can be retained as is. 
3. The title for Section 6.2 "Implications of Good/Bad Visualizations"  and the contents are out of context in this "Ethics" chapter. There is another ticket that talks about section 6.2.

**Comment by 82817** [comment]
After taking the suggestions from @srivasud, I've come up with the following proposal for how to fix Section 6.4 as well as Section 6.2

1. Take out the first two lines of the first paragraph in 6.4.
2. Starting from "More people than ever..." to the end of the bullet points (right before the table), will be kept in this section. The section should be renamed as "Data Deception and Data Integrity"
3. The table on the bottom of 6.4 describes ways an improper graph might be created. This fits well with the content in 6.3 General Guidelines for Ethical Visuals, especially 6.3.3 Design. I would put it in 6.3.3 and title "things to avoid when creating your visualization".
4. The whole section 6.2 is out of context for ethics. I would put it in 3.4 (after 3.4.1) and name the section "Implications of Good Data Visualization". The reason is that this section never talked about the implications of bad visualization.
5. After putting 6.2 into the new section, we can take out "3.4 Special Topic" and let "Data Mining and Data Visualization" take over the title for 3.4

**Comment by 82817** [comment]
Fixed it in pull request #1179. Closing issue
