### ISSUE TITLE
2.3.1.1. Table format Missing

### ISSUE THREAD

**Issue by bharatikandakumar** [mschermann/data_viz_reader#813]
Time, Phase, Description column heading is in place. But the content is not tabulated.

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L115

**Comment by shriya22** [comment]
I completely agree, this has to be tabulated as it is very hard to understand it without one.

**Comment by phoenixren** [comment]
Yes, and there is also duplicated content which should be deleted

**Comment by AayushiVAgrawal** [comment]
The information is extremely cluttered and difficult to read. The sole motive of showing a proper time line to increase understandability is not getting fulfilled.

**Comment by bharatikandakumar** [comment]
Updated the table format. Hence closing this issue
