### ISSUE TITLE
2.1 What is Data Visualization :Why data visualization is such a powerful tool incorrect bullet points

### ISSUE THREAD

**Issue by rtamhankar** [mschermann/data_viz_reader#817]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L23
Bullet points should be 'Intuitive', 'Fast', 'Flexible' etc instead of writing the entire sentences like 
'It is intuitive' etc.

**Comment by btamsir** [comment]
Agreed. This makes it more much more concise.
