### ISSUE TITLE
2.2 Content Proposal - Importance of Data Visualization 

### ISSUE THREAD

**Issue by rtamhankar** [mschermann/data_viz_reader#818]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L28

A short introductory paragraph can be added before explaining each point in a separate section.

**Comment by Vidya313** [comment]
I agree , it will be good to have an introductory content.

**Comment by rtamhankar** [comment]
Content Proposal - 
Below content can be added in the Introductory paragraph.

According to the World Economic Forum, the world produces 2.5 quintillion bytes of data every day, and 90% of all data has been created in the last two years. With so much data, it’s become increasingly difficult to manage and make sense of it all. It would be impossible for any single person to wade through data line-by-line and see distinct patterns and make observations. Data proliferation can be managed as part of the data science process, which includes data visualization.
Reference: https://www.microstrategy.com/us/resources/introductory-guides/data-visualization-what-it-is-and-why-we-use-it

Data visualization is the presentation of data in a pictorial or graphical format. It enables decision-makers to see analytics presented visually, so they can grasp difficult concepts or identify new patterns. With interactive visualization, you can take the concept a step further by using technology to drill down into charts and graphs for more detail, interactively changing what data you see and how it’s processed.
Reference : https://www.sas.com/en_us/insights/big-data/data-visualization.html

Data visualization has become an indispensable part of the business world and an ever increasing part of managing our daily life. Effective data visualization should be informative, efficient, appealing, and in some cases interactive and predictive.
Reference: https://data-visualization.cioreview.com/cxoinsight/what-is-data-visualization-and-why-is-it-important-nid-11806-cid-163.html

**Comment by rtamhankar** [comment]
Pull request has been created #1157 and merged successfully into contributions.
