### ISSUE TITLE
3.1.3 Tufte’s Principles of Design- Additional information can be added in the introductory paragraph

### ISSUE THREAD

**Issue by rtamhankar** [mschermann/data_viz_reader#819]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L43

A small introduction to the Graphical integrity can be added in the introductory paragraph as follows.
"Graphical integrity refers to how accurately the visual elements represent the data. The information can vary widely, even for data that is related. So there is a desire and tendency to scale the data disproportionately in order to make it fit in the space allowed. When values are tightly packed in one area, and sparse in another, there is a desire and tendency to spread things out evenly. In each case, this can lead to a false impression of the data, and incorrect conclusions."
Reference: https://study.com/academy/lesson/edward-tufte-6-principles-of-graphical-integrity.html

**Comment by Marvin510** [comment]
Totally agree, I would also suggest developing more content on this topic.

**Comment by AjayDeshmukh14** [comment]
I agree with you, this description definitely adds depth to the argument and should be added.

**Comment by rtamhankar** [comment]
Pull request was created and additional content has been added.
