### ISSUE TITLE
4.2 Geographic Visualizations - more information can be added in the introductory paragraph

### ISSUE THREAD

**Issue by rtamhankar** [mschermann/data_viz_reader#820]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/03-casestudies.Rmd#L22

More information about the importance and necessity of geographic visualizations can be added in the introductory paragraph

**Comment by kwright76** [comment]
Agreed, maybe we can include some of the techniques used to do this and then give the examples.

**Comment by rtamhankar** [comment]
The content proposal has been created for this issue..Reference - 1086
Hence, closing the same.
