### ISSUE TITLE
2.1 information visualization should include visual examples for Presentation, Exploratory Analysis,Confirmatory Analysis

### ISSUE THREAD

**Issue by Kushall-Dayal** [mschermann/data_viz_reader#821]
Revision Proposal:

Here are the pictures for each 

Presentation:
![Best_Real_Estate_Investing_Example_Powerpoint_Presentation_Examples_1-](https://user-images.githubusercontent.com/49147275/55677198-35a83480-5898-11e9-8736-90a6d041336b.jpg)

Exploratory Analysis:
<img width="904" alt="prosper-eda" src="https://user-images.githubusercontent.com/49147275/55677211-81f37480-5898-11e9-8b74-4bbc019740f3.png">

Confirmatory Analysis:
![Second-order-confirmatory-factor-analysis-factor-loadings-for-the-implementation](https://user-images.githubusercontent.com/49147275/55677206-65efd300-5898-11e9-982a-7ff4208d670d.png)

**Comment by VikitaNayak** [comment]
@Kushall-Dayal Yes, these graphs will be more helpful to understand the types of analysis.

**Comment by JinjinJanelle** [comment]
I agree with you. Also, I think the definitions are somewhat unclear, especially for confirmatory analysis. It would be very helpful if the definitions are of more details with graphs.

**Comment by Kushall-Dayal** [comment]
Pull request #941
