### ISSUE TITLE
2.6 Error in the very first line :"visualizes" should be "visualist"

### ISSUE THREAD

**Issue by Kushall-Dayal** [mschermann/data_viz_reader#822]

**Comment by gauravhassija** [comment]
I must say this error was very well spotted
Here is the Rmd link for reference 
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L225

**Comment by Kushall-Dayal** [comment]
The section 2.6 from the reader was removed in #1060
