### ISSUE TITLE
2.2.2, 2.2.3, 2.2.5, 2.2.6: The referenced link mentioned for McCandless TED talk is invalid

### ISSUE THREAD

**Issue by bharatimalik** [mschermann/data_viz_reader#825]
The correct link is 
https://www.ted.com/talks/david_mccandless_the_beauty_of_data_visualization

**Comment by Marvin510** [comment]
Nice Job,! there seems to be a lot of missing links/citation through out the document.

**Comment by syragrg** [comment]
The link for the TED talk is invalid under 2.2.5 as well.

**Comment by bharatimalik** [comment]
> The link for the TED talk is invalid under 2.2.5 as well.

Thank you! :)
