### ISSUE TITLE
2.6.4.3 Reference information belongs in references. 

### ISSUE THREAD

**Issue by kwright76** [mschermann/data_viz_reader#828]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L299

**Comment by kthang** [comment]
![image](https://user-images.githubusercontent.com/20415266/55693528-62c21900-5964-11e9-82a3-fd9623f8c374.png)

Additionally, in the bookdown version of the reader, history of visualization was 2.3, not 2.1.

**Comment by rlwy** [comment]
I think the original contributor of the text might have wanted to have it as an end-of-chapter reference but didn't do the proper citation markdown for it.
