### ISSUE TITLE
2.6.4.4 - 2.7.2 Historical figures should be under key figures

### ISSUE THREAD

**Issue by kwright76** [mschermann/data_viz_reader#829]
We could create an appendix for any irrelevant, but still interesting historical facts/figures.

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L332

**Comment by Qing0608** [comment]
Actually 2.7 is totally the same as 2.4, so either of them should be deleted. And 2.6.4.4-2.6.4.9 should move to key figures.

**Comment by kwright76** [comment]
This was a null issue
