### ISSUE TITLE
3.1.3.1 What was revised and edited

### ISSUE THREAD

**Issue by kwright76** [mschermann/data_viz_reader#830]
I believe the basics should be covered to show what should be revised and edited in a visualization. The explanation here is brief and can be misunderstood. 

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L65

**Comment by Vidya313** [comment]
I agree it is good to provide guidelines to identify the necessity for revision in some form of a checklist. Else it might be misunderstood to be an imminent action.
