### ISSUE TITLE
2.2.4: Hyperlink for i2b2, R, Tableau, Python would help the reader who doesn't have knowledge on them

### ISSUE THREAD

**Issue by bharatimalik** [mschermann/data_viz_reader#832]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/01-intro.Rmd#L56

Hyperlinks for them could be:

i2b2: https://www.i2b2.org/
R: https://www.r-project.org/
Tableau: https://www.tableau.com/
Python: https://www.python.org/

**Comment by Qing0608** [comment]
That's really a good idea, and very helpful for beginners!
