### ISSUE TITLE
Section 5.8: Sample image of word cloud required

### ISSUE THREAD

**Issue by pragyansharma24** [mschermann/data_viz_reader#833]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L423

There is no example image for the word cloud. Having an image would add to readers' comprehension of how a word cloud looks like.

**Comment by Vidya313** [comment]
I agree, providing relevant examples will improve understandability.
