### ISSUE TITLE
Section 5.1: Add graph for cars2$dist and cars2$speed after outlier removal

### ISSUE THREAD

**Issue by pragyansharma24** [mschermann/data_viz_reader#834]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L32

The graph for cars2$dist and cars2$speed after outlier removal is not present.

**Comment by ttussing** [comment]
I think this issue is similar to one that was recently resolved, can you compare this issue to #1026 and see if it was completed correctly? Thanks!

**Comment by pragyansharma24** [comment]
Resolved.  [https://github.com/mschermann/data_viz_reader/pull/1026](url)
