### ISSUE TITLE
2.4.1 A graph can be added

### ISSUE THREAD

**Issue by phoenixren** [mschermann/data_viz_reader#837]
In section 2.4.1, I think a visualization created by Hans Rosling illustrating the rise of Asia can be added as an example

**Comment by Kushall-Dayal** [comment]
Here are the illustrations from the ted talk being mentioned in section 2.4.1:

![v3](https://user-images.githubusercontent.com/49147275/55678510-06052680-58b0-11e9-8fe0-ab64edc29229.PNG)

![V4](https://user-images.githubusercontent.com/49147275/55678511-07ceea00-58b0-11e9-9987-451c5439ea31.PNG)

He predicted that India and China under ideal conditions would over take western superpowers by  27th July 2048(That’s Precise!)

**Comment by rtamhankar** [comment]
I agree with you. The addition of the graphs/illustrations would helpful!

**Comment by phoenixren** [comment]
Revision Proposal: Add a data visualization graph of Hans Rosling's illustration about the rise of Asian countries under section 2.4.1
