### ISSUE TITLE
2.6.2 Table format issue

### ISSUE THREAD

**Issue by phoenixren** [mschermann/data_viz_reader#839]
The table in section 2.6.2 can be reformatted to be wider

**Comment by pragyansharma24** [comment]
Yes, many tables have this issue. 
I guess the CSS needs to fixed. Currently, the table width is only 47% of the page and the column width is 22%. 

![image](https://user-images.githubusercontent.com/45728559/55679751-a6b21100-58c5-11e9-8af3-dbd84b3a55ea.png)

**Comment by AjayDeshmukh14** [comment]
I feel that it will be a better idea to make changes in this [.rmd file at Line 261](https://github.com/mschermann/data_viz_reader/blob/master/01-intro.Rmd#L261). As **rmd** appears to be the source and HTML file is just an export for the same. Even if we make changes in the HTML they will be overridden once there is a change in rm file and re-exported.

**Comment by rlwy** [comment]
Instead of changing the 22%, the fix should be on the table width to be 100% (full page width).
