### ISSUE TITLE
Section 5.3.9: Misplaced graph

### ISSUE THREAD

**Issue by pragyansharma24** [mschermann/data_viz_reader#841]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L151

Stream graph image is placed under Heat map section.

**Comment by jymhe120** [comment]
Agreed. The stream graph image is misplaced under the heat map section, and the heat map image is one paragraph down from the stream graph image. Thus once we move the stream graph image back into the stream map section it should be fixed.

**Comment by pragyansharma24** [comment]
[link](https://github.com/mschermann/data_viz_reader/issues/793)

**Comment by pragyansharma24** [comment]
Duplicate of #793
