### ISSUE TITLE
Section 5.5: Are the choices of colors appropriate?

### ISSUE THREAD

**Issue by pragyansharma24** [mschermann/data_viz_reader#842]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L274
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L291

The graphs have a green color for negative change and grey for positive change. 
Although the topic is about choosing the right baseline, should we edit the colors green to red for negative changes and keep green for positive changes?

**REVISION PROPOSAL**
1. **For negative changes**: change the color from green to red
2. **For positive changes**: change the color from grey/black to green.

**Comment by bharatimalik** [comment]
I also feel that the colors chosen could have been Green for positive and Red for negative.

Green
A relaxing color, green evokes peaceful images of nature and serenity. It’s also a symbol of safety and may encourage decisiveness.
Red
Anything red jumps out of a data visualization and expresses powerful emotions in an instant. It’s perfect for emphasis and calling attention to data against the background.

Definitions of Green and Red source: https://www.tapclicks.com/the-influence-of-color-in-data-visualization/

**Comment by Psharma2193** [comment]
Yes, I agree that the current color representation doesn't justify the graph. They can be changed for better interpretation.

**Comment by pragyansharma24** [comment]
Thank you @bharatimalik and @Psharma2193 for the feedback.

**Comment by pragyansharma24** [comment]
REVISION PROPOSAL: 
1. **for negative changes**: changing the color green to red  
2. **for positive changes**: changing the color from grey/black to green.

**Comment by pragyansharma24** [comment]
Resolved.
