### ISSUE TITLE
Placement of these links should have been under 2.6.3 

### ISSUE THREAD

**Issue by bharatimalik** [mschermann/data_viz_reader#843]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/01-intro.Rmd#L299

The links mentioned from 2.1 to 2.7 doesn't seem right to be under 2.6.4: Infographics vs. Data Visualization. Instead it must have been under 2.6.3 (Useful Links on Data Visualization Resources, Trends, and Tutorials.

The bullet numbers are also wrong in their current placement.

A new subsection could be created: 2.6.3.1: "Few more links for Data Visualization"
and then 2.1 could be renumbered as 2.6.3.1.1
and then 2.2 could be renumbered as 2.6.3.1.2
and so on

**Comment by bharatimalik** [comment]
As per #850 my new suggestion would be to make 7.3.1 instead of 2.6.3.1

**Comment by Qing0608** [comment]
I also found some duplicated link in both 2.6.2. and 2.6.3. And some link was misplaced, for example, http://beautifuldata.net/ and https://datavizblog.com/ should be put under 2.6.2(blog) section instead of 2.6.3(resources).

**Comment by bharatimalik** [comment]
This issue doesn't exist anymore in the reader!
