### ISSUE TITLE
6.1: Displaying the 4 guidelines one below the other will be visually more appealing

### ISSUE THREAD

**Issue by bharatimalik** [mschermann/data_viz_reader#844]
https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/05-ethics.Rmd#L17

**Comment by bharatimalik** [comment]
![image](https://user-images.githubusercontent.com/42341805/55677174-da764200-5897-11e9-9bc5-f8e522fa94b4.png)

**Comment by Kushall-Dayal** [comment]
I agree with the same .I also think key words should be highlighted(bold) like 1.selection bias 2. False or irrelevant 3.accurate and relevant, moral pitfalls 4.unethical-trap, evidence-based approach
