### ISSUE TITLE
Missing pictorial representation of billion dollar-o-gram in section 2.2.2

### ISSUE THREAD

**Issue by Kushall-Dayal** [mschermann/data_viz_reader#845]
Revision Proposal:

The section describes the billion dollar-o-gram in its full glory but a visual cue would be helpful about the thing being discussed

Here is a picture of billion dollar-o-gram

![book_billion](https://user-images.githubusercontent.com/49147275/55677159-b7e42900-5897-11e9-9d7f-6c8cdc2de9d3.jpg)

**Comment by Kushall-Dayal** [comment]
The same depiction can be found in chapter 7 (Fig 7.1)

**Comment by VikitaNayak** [comment]
@Kushall-Dayal Also, I found it difficult to read this graph

**Comment by btamsir** [comment]
Agreed. If a presenter is delivering the context to validate this figure, it would be too much to both listen and digest it.

**Comment by Kushall-Dayal** [comment]
Pull request #1015
