### ISSUE TITLE
2.3.1.1 bad format and duplicate information

### ISSUE THREAD

**Issue by Qing0608** [mschermann/data_viz_reader#846]
The chart in 2.3.1.1, there are duplicate information in first two paragraph. Also the format is difficult to read, it supposed to be clearly separated into three columns: Time, Phase, Description.

**Comment by mayjai** [comment]
Here is the code of the issue:
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L105-L107

I think it would be easier to locate the issue for further fixing.
