### ISSUE TITLE
3.6.1, 2.2.2 : Unnecessary numbering 

### ISSUE THREAD

**Issue by Psharma2193** [mschermann/data_viz_reader#849]
For 2.2.2 - The number can be removed and the sentence can be added to the paragraph
For 3.6.1 - It can be completely removed as it is irrelevant

<img width="295" alt="issue2_2" src="https://user-images.githubusercontent.com/37756459/55677632-40ff5e00-58a0-11e9-9a7a-c42ebc2b0caa.PNG">
<img width="507" alt="issue2_1" src="https://user-images.githubusercontent.com/37756459/55677633-40ff5e00-58a0-11e9-8598-d5a4771f8dfb.PNG">

**Comment by Vidya313** [comment]
I agree , the numbering seem irrelevant.

**Comment by kthang** [comment]
I would go further and delete the entire bullet.  It seems to be a leftover from copy and pasting.  Right now, it would need more context to make sense.

**Comment by strivedi2** [comment]
If the issue is categorized as 'Done' in the project, maybe it can be closed?

**Comment by Psharma2193** [comment]
Closing the Issue as it has been done
