### ISSUE TITLE
Duplicate content in 2.6 and 7.3 with some differences.

### ISSUE THREAD

**Issue by bharatimalik** [mschermann/data_viz_reader#850]
I think we should remove 2.6 altogether and keep only 7.3 (with content additions from 2.6). This would mean that the additional links are in the end. If the additional links are kept in 2.6 and not in the end, we might lose some of our readers in section 2 itself.

**Comment by Marvin510** [comment]
Chapter seven is supposed to be the conclusion. I would argue this content be put elsewhere. I didn't realize the same information was displayed in two different chapters. This is something worth looking at.

**Comment by bharatimalik** [comment]
Definitely something to look at.. I myself started visiting those additional links while reading chapter 2. I came back to chapter 3 because I had an motive of completing my assignment. But if a general reader leaves the main reading and visits the additional links in between his/her reading, he/she may or may not come back to the original reading. Thus I still feel that these additional links should be moved in the end.

**Comment by bharatimalik** [comment]
It was already taken care of in issue #878, thus closing this issue!
