### ISSUE TITLE
Section 3.6.1.4, Pg 62: Missing Quote symbol

### ISSUE THREAD

**Issue by Psharma2193** [mschermann/data_viz_reader#851]
The question mark should be replaced
<img width="470" alt="issue3" src="https://user-images.githubusercontent.com/37756459/55677733-fe3e8580-58a1-11e9-92d9-e23ce3fffa29.PNG">
.

**Comment by bharatimalik** [comment]
I don't see any page numbers on the webpage. Did you save it in pdf format and then referring to the page numbers?

**Comment by Psharma2193** [comment]
Yes, I'm viewing the book in pdf format.

**Comment by Psharma2193** [comment]
Issue is fixed and changes merged into contributions
