### ISSUE TITLE
Unnecessary spacing, Text and Image cutoff in the pdf format of the file 

### ISSUE THREAD

**Issue by Psharma2193** [mschermann/data_viz_reader#853]
The PDF format of the file has unnecessary spaces in the text at multiple places and few images are not resized to the layout. However, the same content is properly visible in the browser view. 

**The browser view -**
![image](https://user-images.githubusercontent.com/37756459/55677884-077d2180-58a5-11e9-859b-4202f16619fa.png)

**The pdf view -**
![image](https://user-images.githubusercontent.com/37756459/55677888-1bc11e80-58a5-11e9-89ca-bafa820df7a4.png)

similar issue at multiple places-
![image](https://user-images.githubusercontent.com/37756459/55677904-a144ce80-58a5-11e9-80bb-c7f3ae7de14c.png)

**The images are not centered and resized to page layout in the pdf format.**
![image](https://user-images.githubusercontent.com/37756459/55677898-7d818880-58a5-11e9-8c75-38b053400475.png)

**Comment by Psharma2193** [comment]
Adding to the same Issue. The sequence of images is also haphazard in PDF compared to browser where the text description is proper and followed by respective image. The majorly affected section is chapter 4 where there is no flow between the text and images.

**Comment by Psharma2193** [comment]
I have checked the rmd files and they are fine. This issue seems more like a format issue when the reader is published as PDF. 
Are there any suggestions on this or should I go ahead and close the issue ?

**Comment by strivedi2** [comment]
I am not familiar with rendering a Red file into pdf. Also I have only been referring to the browser for content and the pdf. Unless there is a solution maybe this can be closed.

**Comment by VikitaNayak** [comment]
Yes, we can close this out
