### ISSUE TITLE
All Chapters: List of citation issues with ??? 

### ISSUE THREAD

**Issue by pragyansharma24** [mschermann/data_viz_reader#854]
Chapter 2 : 2.1, 2.3.2.5
Chapter  3: 3.2 , 3.3.2, 3.3.3, 3.7
Chapter  4: 4.9.3, 4.9.6
Chapter  5: 5.8, 5.9, 5.10.1, 5.10.2.6, 5.10.2.7, 5.10.4
Chapter 6: 6.4, 6.6

**Comment by jacksonh2** [comment]
Hi Pragyan, I also saw these issues. I believe they are a bunch of reference link missing. If you look into Rmd file, they do have [@viz] or [@info_viz], so it's probably just missing and can be filled in.

**Comment by mayjai** [comment]
This list is very useful for us to further fix the issues. As I was reading and searching some related information, I found an article that might be the missing citation link of chapter 3.7:
https://medium.com/@uwdata/next-steps-for-data-visualization-research-3ef5e1a5e349

**Comment by Psharma2193** [comment]
Great! This sums up all citation issue and will be a good reference later when we work on the fix.

**Comment by gauravhassija** [comment]
This is a great list that summarizes all broken links and missing citations
I found the article that might be missing citation for section 2.2.2 (McCandless 2010)
https://www.ted.com/talks/david_mccandless_the_beauty_of_data_visualization

**Comment by rlwy** [comment]
Thanks for compiling this list! The issue is due to mismatched citation tags between the .rmb files and the .bib file. I created a similar issue too #743 and quoted the link for R Markdown's Citation Documentation in it.

**Comment by pragyansharma24** [comment]
Below is the list of open and closed issues in the contributions branch: 
Chapter 2 : 2.1, 2.3.2.5 (open)
Chapter 3: 3.2 ,3.7 (closed)  3.3.2, 3.3.3 (open)
Chapter 4: 4.9.3, 4.9.6 (closed)
Chapter 5: 5.8, 5.9, 5.10.1, 5.10.2.6, 5.10.2.7, 5.10.4 (open)
Chapter 6: 6.4 (closed) , 6.6(open)

Many students have been working on them, some of them have been resolved and merged into the contributions branch. Moving forward we can divide the work and resolve all the remaining issues.

**Comment by pragyansharma24** [comment]
All the issues are fixed now.
https://github.com/mschermann/data_viz_reader/pull/1198
