### ISSUE TITLE
Section 2.5 : Point 4 and 5 have repetitive content.

### ISSUE THREAD

**Issue by Psharma2193** [mschermann/data_viz_reader#856]
there is repetition of "Data visualization still leaves room for interpretation." multiple times and its usage is abrupt having no continuity with the content. Either the content of both the points can be merged or they should be framed well.

**Comment by strivedi2** [comment]
I don't see this issue in the reader now. Looks like it was fixed.

**Comment by Psharma2193** [comment]
Yes, i can see that too! The issue seems to be fixed now. Hence closing the issue.
