### ISSUE TITLE
2.4 and 2.7 are the same

### ISSUE THREAD

**Issue by Qing0608** [mschermann/data_viz_reader#859]
section 2.4 and 2.7 are totally the same, should delete either of them.

**Comment by AayushiVAgrawal** [comment]
I agree. One of these sections should be avoided.

**Comment by agrasonal** [comment]
Hi Qing0608
I think you can create an issue directly from the code:
https://help.github.com/en/articles/opening-an-issue-from-code
If you already created this issue, you can just edit it and add the LINK URL(generated by creating a new issue) for the code.
Hope you find it helpful!

**Comment by Qing0608** [comment]
Thank you agrasonal. I will try!
