### ISSUE TITLE
2.1 missing reference

### ISSUE THREAD

**Issue by jacksonh2** [mschermann/data_viz_reader#863]
On the Rmd file, it shows that there's suppose to be a reference to info_viz, but when opened in html form, it becomes (???)

#viewed in Rmd
> **Information visualization** is the art of representing data so that it is easy to understand and manipulate, thus making the information useful. Visualization can make sense of information by helping to find relationships in the data and support (or disproving) ideas about the data. [@info_viz] shares some examples and common uses of information visualization, such as:

#viewed in html
> Information visualization is the art of representing data so that it is easy to understand and manipulate, thus making the information useful. Visualization can make sense of information by helping to find relationships in the data and support (or disproving) ideas about the data. (???) shares some examples and common uses of information visualization, such as:

**Comment by rlwy** [comment]
Issue has been resolved in PR #1069.
