### ISSUE TITLE
2.6.4 Useful to have a comparison table

### ISSUE THREAD

**Issue by mayjai** [mschermann/data_viz_reader#864]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L275-L283

It would be useful to add a Infographics vs. Data Visualizations comparison table, so readers can understand the two subsections 2.6.4.1 and 2.6.4.2 at a glance. Right now, we only have the table showing different use cases. A comparison table of the information can show the difference between a infographic and a data visualization more clearly.

**Comment by Vidya313** [comment]
I agree , the table format can increase readability and summarize the two sections.

**Comment by mayjai** [comment]
### **Revision Proposal:**
We can either add the comparison table before section 2.6.4.1 or after section 2.6.4.2. Both have its advantage:
- Before section 2.6.4.1: used as a quick preview of the following two subsections
- After section 2.6.4.2: used as a summary of the above two subsections

**Proposed comparison table:**
| Data Visualization | Infographics |
| --- | --- |
| Illustrates raw values | Visualize stories |
| Delivers information | Provide stances |
| Offers objectivity | Offer subjectivity |

**Comment by mayjai** [comment]
Added the comparison table.
