### ISSUE TITLE
2.3.1 & 2.3.1.1 unnecessary separation and redundant

### ISSUE THREAD

**Issue by jacksonh2** [mschermann/data_viz_reader#865]
The quotation in 2.3.1 should be merged into 2.3.1.1 since they are closely related, and 2.3.1 has no other content than just the quote, so it's unnecessary to create a subsection for the quote itself.

> 2.3.1 Brief history

> “The only new thing in the world is the history you do not know.” — Harry S Truman

> 2.3.1.1 Data Visualization: A Modern Product?

> Given the recent explosion in data availability and visualization tools, it would be natural to assume that statistical graphics and data visualizations are relatively modern developments. However, the graphic representation of quantitative information has deep roots that reach into the histories of the earliest map-making and visual depictions, and up to thematic cartography, statistics, medicine, and other fields.

The quote is trying to say that data visualization is not a modern development rather it was used long time ago in history, and I think that meaning is conveyed in the first paragraph of 2.3.1.1, thus 2.3.1 should be merged into 2.3.1.1 or removed completely

**Comment by mayjai** [comment]
The issue has been fixed.
