### ISSUE TITLE
Section 5.9:  Addition of a sample dashboard image

### ISSUE THREAD

**Issue by Vidya313** [mschermann/data_viz_reader#868]
The Dashboard section can be expanded with more information and adding an image of a sample dashboard will be a good enhancement.

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L452

**Comment by jymhe120** [comment]
Chapter 4 includes many dashboard illustrations, such as the two below. Therefore, I suppose we can use them as a reference.  
<img width="727" alt="WeChatcd0d539f22851675820397e65a75d168" src="https://user-images.githubusercontent.com/35418915/55704200-6e2b3980-5990-11e9-90d5-d7e017d8cb58.png">

<img width="729" alt="WeChatda070acb04c9f74677f87d18738c6685" src="https://user-images.githubusercontent.com/35418915/55704262-8a2edb00-5990-11e9-81ac-15446f609599.png">

**Comment by Vidya313** [comment]
The issue is fixed in the pull request #1080  and successfully merged
