### ISSUE TITLE
2.3.1 Missing Citation for the Quote

### ISSUE THREAD

**Issue by AjayDeshmukh14** [mschermann/data_viz_reader#870]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/01-intro.Rmd#L100
The quote used in 2.3.1 Brief history needs to be cited.

**Comment by btamsir** [comment]
Interesting find. This quote is popular in American history but I am unsure what source it came from. For instance, it could be from a speech or from a autobiography of Truman himself. As a result, I am unsure how citation conventions stack up in this particular situation.

**Comment by AjayDeshmukh14** [comment]
I agree with you, even I tried to find the source of this quote but was not really sure where it came from.

**Comment by jymhe120** [comment]
Agreed. Cannot find the source for this quote either. For now, this issue may remain open.
