### ISSUE TITLE
2.4.2 The graph show incorrect values for the categories showed in legends

### ISSUE THREAD

**Issue by VikitaNayak** [mschermann/data_viz_reader#871]
The legends display categories where each country is good. For example Commodity, Psychology, Ecology, Gastronomy, Economy, Nicety, Humanity, technology and Nasty. However, a few category values are not relevant to that category For example, Psychology(colored in blue) has a value called doughnuts(colored in blue)  for Canada. Doughnuts actually belong to the category Gastronomy (colored in purple). Refer below image:

![image](https://user-images.githubusercontent.com/43161990/55689978-6479e580-5940-11e9-95b6-a8ba5dfd0224.png)

**Comment by kthang** [comment]
Additionally, Pakistan's specialty is listed as "GAY PORN", however, it is colored purple, which would indicate that gay porn is part of gastronomy.

**Comment by VikitaNayak** [comment]
@kthang Yes correct, similarly we also have "PORNSTAR" for Hungary which is listed under gastronomy

**Comment by VikitaNayak** [comment]
As we don't have the dataset to correct this graph, I am closing out this issue
