### ISSUE TITLE
5.3.11 The legends of the graph are long and hard to read

### ISSUE THREAD

**Issue by VikitaNayak** [mschermann/data_viz_reader#876]
![image](https://user-images.githubusercontent.com/43161990/55690374-a48f9700-5945-11e9-84d6-8bcac7e8dde6.png)

**Comment by JinjinJanelle** [comment]
We can definitely remove "Diagram of". It is redundant because readers understand it is a diagram/graph.

**Comment by VikitaNayak** [comment]
@Psharma2193 @strivedi2 If you can find a graph with which we can replace this graph, please add it
