### ISSUE TITLE
Section 5.10 - The section doesn't have coherent content 

### ISSUE THREAD

**Issue by Psharma2193** [mschermann/data_viz_reader#879]
It gives very useful information on working with specific components using different Visualization tools. But it is unclear what is intended out of this section overall. 
First it starts with working with shapes as Tableau(5.10.1) then switches to legend customization (again specific) in Python(5.10.2) where there is also content of working with MATLAB and R in the same subsection.
This section is too broad. Maybe making a separate chapter for component and useful software tips would be better option?

**Comment by rtamhankar** [comment]
Agreed. A separate chapter for each component would be really helpful!

**Comment by KlippL** [comment]
Hey, so I have been working on putting a lot of stuff into chapter 2, where it seems better suited. My main focus has been on Tableau, so I moved the part about tableau into 3.4.7 (fundamentals). I believe that other parts of 5.10 can be relocated into 3.4 if you guys are interested in working on that!

Pull request reference: Moved Tableau into Fundamentals #1124

**Comment by Psharma2193** [comment]
Hi @KlippL, the content looks good. Closing this issue as it has been merged in Pull request #1124.
