### ISSUE TITLE
7.3.3 Redundant hyperlinks

### ISSUE THREAD

**Issue by syragrg** [mschermann/data_viz_reader#885]
Most of the links under "Resource" and under "Link" ultimately leads to the same website. Examples include Catalogue 2018 and its corresponding link, Kosara 2018b and its corresponding link, beautifuldata.net 2018 and its corresponding link and more. One of the hyperlink in the same row should be removed to access the links more conveniently and to avoid confusion.

**Comment by ttussing** [comment]
Since this is a typing/editing error, I'm going to mark this as a grammatical issue
