### ISSUE TITLE
4.9.2 Difficult to read the graph

### ISSUE THREAD

**Issue by VikitaNayak** [mschermann/data_viz_reader#886]
![image](https://user-images.githubusercontent.com/43161990/55691541-f63f1e00-5953-11e9-9e0b-4172e8f1abda.png)

The overlapping text and images make it difficult to read the graph

**Comment by rtamhankar** [comment]
Agreed! The graph and the text can be improved for clear visualization. The format, font and color of the text can be modified in order to make it more clear and readable.

**Comment by VikitaNayak** [comment]
Closing this issue as we do not have a dataset to create a better version of this graph
