### ISSUE TITLE
5.1 Missing/Corrupted images

### ISSUE THREAD

**Issue by AayushiVAgrawal** [mschermann/data_viz_reader#887]
There are 2 missing / corrupted images in the article 5.1

**Comment by rlwy** [comment]
The broken image is in 04-patterns.rmb line 29 and 35. 
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L29

https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L35

**Comment by AayushiVAgrawal** [comment]
I pulled out master branch and revisited section 5.1 to see the broken images. Seems like issue is fixed now. Closing issue.
