### ISSUE TITLE
6.2 Missing column for serial number in table 

### ISSUE THREAD

**Issue by AayushiVAgrawal** [mschermann/data_viz_reader#888]
In the table shown in article 6.2, there is a column Principle. The contents of that column start with a serial number. It would be better if a separate column for serial numbers could be shown.

**Comment by AayushiVAgrawal** [comment]
Revision Proposal:
A separate column for serial numbers would enhance the look of the table or these numbers can be skipped also

**Comment by AjayDeshmukh14** [comment]
It is a good observation and I feel that it will be a better idea to skip the numbers altogether because the numbers won't be significant in this case.
