### ISSUE TITLE
3.3.6 link not found

### ISSUE THREAD

**Issue by jacksonh2** [mschermann/data_viz_reader#889]
In section 3.3.6 where it's talking about D3.js, the reference/citation for this part is no longer working, showing a 404 Not found.

> Cabot Technology Solution. 2017. “D3.js: the Perfect Dynamic Platform to Build Amazing Data Visualizations.” https://hackernoon.com/d3-js-the-perfect-dynamic-platform-to-build-amazing-data-visualizations-ebe930f0648f.

![image](https://user-images.githubusercontent.com/41307867/55691846-348a0c80-5957-11e9-833e-09a9238c624a.png)

**Comment by syragrg** [comment]
I am marking it as a bug since the link is not working/no longer exist.

**Comment by AjayDeshmukh14** [comment]
I have seen this issue at a couple of places and I feel that it will be a good idea to check when these websites were last accessed in the information of that reference, these links will have to be replaced by links with similar info if these web pages have been taken down (corresponding text of the materials should be changed).
