### ISSUE TITLE
2.5 Reference at the beginning

### ISSUE THREAD

**Issue by btamsir** [mschermann/data_viz_reader#891]
I am personally in favor of having the reference at the end of the sentence instead of the beginning as it gives readers a chance to contextualize information before identifying the source. 

Before : 
(Deloitte, Datawheel, and Hidalgo 2016) MIT Media Lab in collaboration with Deloitte has created a new visualization tool, that aggregates US government open source data and mines information to generate trends and stories about cities, jobs, industries, etc. 

Now : 
MIT Media Lab in collaboration with Deloitte has created a new visualization tool, that aggregates US government open source data and mines information to generate trends and stories about cities, jobs, industries, etc (Deloitte, Datawheel, and Hidalgo 2016).

**Comment by ttussing** [comment]
I agree, [MLA Format](http://www.citationmachine.net/mla/cite-a-website) supports having the in-text citation at the end of the relevant information

**Comment by btamsir** [comment]
Was fixed on my first pull request. Closed.

**Comment by btamsir** [comment]
https://github.com/mschermann/data_viz_reader/pull/966
