### ISSUE TITLE
5.3.13 Pie Chart is in 3d

### ISSUE THREAD

**Issue by btamsir** [mschermann/data_viz_reader#893]
Although this is just giving an example of a 3D graph, I do not believe adding an extra dimension adds any value to digesting the information. 

![image](https://user-images.githubusercontent.com/36384119/55692147-0d810a00-595a-11e9-858c-64d976f66993.png)

**Comment by ttussing** [comment]
I think the point of this graph is to show the lack of value that the 3rd dimension has on the graph, next to the 3D pie chard is the 2D version that contains the same information and color, without the confusion of perspective

**Comment by syragrg** [comment]
Right, I think in addition to the 3D chart not having much value in this instance, it should be mentioned that it is potentially misleading as the 3D skews our perspective. The text does not offer much explanation.

**Comment by mayjai** [comment]
Below the chart it says "adding a 3-D effect to any visualization might qualify as deceptive", so I think the person was trying to give an example using this chart. So I think we don't really need to do anything with this issue and can close it. 
By the way, the chart is now under section 5.4.3.4.
