### ISSUE TITLE
4.6.1 graph coloring/labeling

### ISSUE THREAD

**Issue by jacksonh2** [mschermann/data_viz_reader#894]
In the global carbon emission visualization that's embedded in section 4.6.1, the visualization utilizes various colors.

However, it doesn't have a clear label as to why these countries were given that particular color. 

After a little digging on my own, I found out that the colors represent different continents, for instance, red is for Australia continent, green is for North America continent etc.

It would have been nice if a legend is given to help clarify which color belong to which continent and why that continent was given that color, was it based on emission (continents that had less emissions received green color which generally means healthy and "green"?)

![image](https://user-images.githubusercontent.com/41307867/55692138-f9d5a380-5959-11e9-920f-9e528e91b2ff.png)

**Comment by JinjinJanelle** [comment]
The chart can also be improved by presenting the top countries from left to right. It is people's habit to read that way. Also, the dots show the amount of emission relatively, but it is hard to compare the sizes. Numbers can be added on top of the dots to provide more intuitive impressions.

**Comment by jacksonh2** [comment]
This issue is still open because can't really alter the existing interactive visualization

**Comment by mschermann** [comment]
@jacksonh2 What is the solution to this issue?

**Comment by jacksonh2** [comment]
@mschermann Would it be appropriate if I add some captions and legends on top of the graph?

**Comment by jacksonh2** [comment]
This issue will be closed because no solution could be provided.
