### ISSUE TITLE
2.6.4 Unusual Reference. 

### ISSUE THREAD

**Issue by btamsir** [mschermann/data_viz_reader#895]
2.6.4 Infographics vs. Data Visualizations
_Data visualization and infographics both present visual information to users. While their purposes may seem similar, they have different use cases. This article explains the differences between an infographic and a data visualization. (Pritchard 2016)._

I have never personally seen references done this way. Usually, the sources are cited such as "...data visualization (Pritchard 2016)."

**Comment by kthang** [comment]
I think this was a typo.  Other citations that I've seen were in the style that you are more familiar with.

**Comment by btamsir** [comment]
Closed with prior PR.
