### ISSUE TITLE
4.3.2 Migration Patterns

### ISSUE THREAD

**Issue by btamsir** [mschermann/data_viz_reader#896]
![image](https://user-images.githubusercontent.com/36384119/55692317-87fe5980-595b-11e9-90d6-3499cd1ebc4a.png)

We can see that 75% of people stayed in California and 25% of them have left to go elsewhere. Perhaps an enhancement would be to add a similar but separate chart that subsets only the 25% of people that have left. It can be difficult to read this chart if presenting to a large audience.

**Comment by rtamhankar** [comment]
Agreed! The exact percentages for 'Midwest' and 'Northeast' regions are not visible in this chart so a separate chart with detailed percentages could be helpful in order to present it to a large audience.

**Comment by btamsir** [comment]
For this issue, one would need to modify the chart or perhaps just give a pro/cons list of this chart for the user.

**Comment by mschermann** [comment]
@btamsir What is your plan for moving forward?

**Comment by btamsir** [comment]
Definitely alter the descriptions to include a pros/cons of this type of charts.

**Comment by jacksonh2** [comment]
It was nice that you added a section on the pros and cons of this type of charts. Are you planning on modifying the graph in addition to the pros and cons list? If not, I think the issue can be closed

**Comment by mschermann** [comment]
@btamsir Can we close this?

**Comment by btamsir** [comment]
Yes!
