### ISSUE TITLE
4.7.1 Green Honey

### ISSUE THREAD

**Issue by kthang** [mschermann/data_viz_reader#897]
I'm unsure of what the visualization is trying to convey.  I understand that it originally moved while you scroll down the page, but even so it's still hard to imagine what was the point.  

A big part of the problem, I think, is that I have no idea what "base" colors are.  This is as someone who understands both English and Chinese.

**Comment by btamsir** [comment]
I agree with you, kthang. It seems like this graph prioritizes visual aesthetics before information transfer.

**Comment by mayjai** [comment]
I didn't get the point at first either, but then I went back to the [original article](https://visme.co/blog/best-information-graphics-2016/) and found that the visualization was showing that the idea that different languages may have vastly different ways of describing things—including color, using English and Chinese as an example. 
The below screenshot shows the different ways of describing color in Chinese as shown in the link above.
<img width="775" alt="Screen Shot 2019-05-09 at 11 27 22 AM" src="https://user-images.githubusercontent.com/41956190/57478261-570d8f00-724f-11e9-9aa4-19019ba1a2be.png">

So I think readers can better understand what this section is trying to convey by quoting the original article "Language shapes the way we view the world. Different languages may have vastly different ways of describing things—including color." at the beginning of section 4.7.1.
