### ISSUE TITLE
4.7.2 CL terminology 

### ISSUE THREAD

**Issue by kthang** [mschermann/data_viz_reader#899]
I was reading the section and was confused when the term "CL" started to be used.  Based on the contents on the section, I am guessing that CL stands for **Computational Linguistics**, but I would prefer to have this made explicit in the text.  

First instance of the term CL:

"Traditional statistical graphs and custom-designed data illustrations fill the pages of CL papers..."

This is the opening sentence of the paragraph where the above quote is from.  I guessed the meaning of CL from this line: 
  
"Much of what computational linguists fall back upon..."

**Comment by kthang** [comment]
A simple fix would be to say:  Much of what computational linguists (CL) fall back upon...

There might issues with matching the style that Schermann intended, but this is a common way to introduce acronyms.

**Comment by Vidya313** [comment]
Issue is fixed with pull request #1203.
