### ISSUE TITLE
5.10.2.4 Latitude and Longitude

### ISSUE THREAD

**Issue by btamsir** [mschermann/data_viz_reader#900]
![image](https://user-images.githubusercontent.com/36384119/55692780-fe9d5600-595f-11e9-81b3-ecfe71851249.png)

This graph shows the long/lat of California cities but I feel like this doesn't really give any useful information at all since no one knows cities' lat/long coordinates.

**Comment by btamsir** [comment]
A revision would to be have the California Map with the population and city area on top of a city's respective location.

**Comment by kthang** [comment]
Instead of an outline of California, it might also help to superimpose the visualization over a map.  This would also allow the viz to work on different locations, not just California.

**Comment by btamsir** [comment]
Agreed! I think also a pros/cons list for this visualization would benefit the reader.

**Comment by mschermann** [comment]
@btamsir What is your plan for moving forward?

**Comment by mschermann** [comment]
@btamsir can we close this?

**Comment by btamsir** [comment]
Yes we can!
