### ISSUE TITLE
7.2 Proper labeling for 'How is it being used?' needed

### ISSUE THREAD

**Issue by AjayDeshmukh14** [mschermann/data_viz_reader#901]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/06-conclusion.Rmd#L73-L87
This section needs to be properly formatted and bulleted, since lines 77, 80, 83 and 86 explain the usage and thus should be bulleted under the point given on line 73.

**Comment by rtamhankar** [comment]
I agree with you. Proper bullet points are required to catch the reader's attention.

**Comment by AayushiVAgrawal** [comment]
I strongly agree. Bullets help highlight important information.
