### ISSUE TITLE
Map visualization types in patterns needs to be expanded on

### ISSUE THREAD

**Issue by ttussing** [mschermann/data_viz_reader#903]
The world maps section (below) only includes one source, I think we can improve on this, especially since it includes no example visualizations. For instance we can use tableau and a supporting app (Mapbox) to make many custom map visualizations: [Allan Walker 2018](https://blog.mapbox.com/my-favorite-tableau-visualizations-d85e869200b4)  

> 
> ## Maps
> 
> **Use Maps Only When Effective**  

> Maps are a popular choice when it comes to displaying geographical data; they are more exciting and engaging than a simple bar or line chart but still easy to comprehend. Maps are attention-grabbing, so at the first glance they seem like a great option.
> 
> However, just because the data can be represented on a map does not mean that it should be. When used properly, a map can be an excellent choice for illustrating a story. However, if geographic information is not relevant to convey the desired message, then a visualizing your data using a map is actually counterproductive.  As with any visual, maps are not a universal solution simply because they are eye-catching.
> 
> One good use of a map is to show points or specific locations. This use of a map can show how points are distributed and reveal patterns, for example, certain areas having more high-end restaurants. This is not the right approach if the geographic information does not tell a story. If the story is more about comparing data such as median salary, a map is not the most effective. Caution should also be exercised with map visualizations if there are too many points and the data blurs together, causing the data to lose its meaning. 
> 
> Encoding the data is another potential area for confusion. The most popular methods are using color, shape, and size. Again, each of these can be effective when done properly, but many people misuse them. Using too many colors can make the chart harder to interpret. If necessary, data can be grouped into categories such as good and bad or high, medium and low. Shapes should be easily distinguished, so there shouldn't be too many unique ones. Also, if the use of shapes does not significantly add to the story, it is probably best to remove them. The size of a marker is a clear way to describe amounts but can easily become a problem if there are outliers. Locations with large values could obscure other data points. The best practice is to use just one of these methods rather than combining two or more.
> 
> Use of maps can be tricky. Geographical data doesn't imply that a map is the best choice to represent it. Maps can be useful for application where proximity matters, but for straight "what is higher" type comparisons, they're not very effective since large regions will draw more attention than smaller regions due to more concentrated color.
> 
>

**Comment by Bradshaw** [comment]
I don't understand why I've been tagged here, I'm not involved with this project, you might be looking for someone else

**Comment by mschermann** [comment]
@ttussing What is the status of this issue?

**Comment by ttussing** [comment]
I plan to fully complete this this upcoming week, I hope that timing is ok

**Comment by ttussing** [comment]
This was already completed by another student
