### ISSUE TITLE
4.3.2 Migration Patterns #2

### ISSUE THREAD

**Issue by btamsir** [mschermann/data_viz_reader#904]
![image](https://user-images.githubusercontent.com/36384119/55693586-a74db480-5964-11e9-96dc-24aa0af0a4d3.png)

This graph is similar to the previous issue concerning 4.3.2. The bottom portion subsetting the people who have left Pennsylvania have been labeled on the left, middle, and right sides. This causes readers to be constantly looking back and forth to validate the graph.

**Comment by VikitaNayak** [comment]
@btamsir Yes correct, you may have to look back and forth to see the track. Some other format of the chart might help here.
