### ISSUE TITLE
Pie chart coloring in 5.3.13.4

### ISSUE THREAD

**Issue by ttussing** [mschermann/data_viz_reader#905]
I understand that the point of this commentary is to show that pie charts can be unnecessary, but it is cutting pie charts at the knees with the examples:

> 4. A pie chart may be useful when comparing two different categories with different amounts of information. Specifically, it does a better job to distinguish two parts with a 25:75 split or one that is not 50:50 as people are sensitive to a right angle or a dividing line that is not straight. However, this could be done more simply by showing two numbers!

<img width="388" alt="Screenshot 2019-04-07 18 46 03" src="https://user-images.githubusercontent.com/49251758/55693711-699d5b80-5965-11e9-89de-7f4397fcbce7.png">

I don't think this commentary is strong enough to be its own argument

**Comment by pragyansharma24** [comment]
I agree with you, Hale. 
It's like selecting a bad pie chart and making an argument pie charts are bad in general.

**Comment by JinjinJanelle** [comment]
My understanding is that the paragraph argues that if there are only two categories, it is unnecessary to show pie charts as information of the original sheer number will be lost. But the paragraph is very unclear and does not state under what conditions pie charts will be useless.
