### ISSUE TITLE
6.5 Missing citation

### ISSUE THREAD

**Issue by AjayDeshmukh14** [mschermann/data_viz_reader#909]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/05-ethics.Rmd#L91
The citation for the article 'Vox's gun violence' is missing.

**Comment by jacksonh2** [comment]
Hello, I went online and found the link to the Vox's article on gun violence, and it contains various maps and charts(visualizations) on gun violence. This can be added to the citation.

https://www.vox.com/policy-and-politics/2017/10/2/16399418/us-gun-violence-statistics-maps-charts

**Comment by srivasud** [comment]
Hi,
You can use the below link to cite Vox's article on gun violence.
https://www.vox.com/policy-and-politics/2018/2/21/17028930/gun-violence-mass-shootings-us-statistics-charts

**Comment by Vidya313** [comment]
Hi Ajay , 
You have fixed the issue and merged through the pull request #1131. Can we close this issue?
