### ISSUE TITLE
6.9.6 Link expired

### ISSUE THREAD

**Issue by AjayDeshmukh14** [mschermann/data_viz_reader#910]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/05-ethics.Rmd#L192-L193
In this section, the reference [@scaling_issues] points to a link that may be expired or moved and returns a 404 error when we try to access it

**Comment by strivedi2** [comment]
Missing/ incorrect/ non-existent references seems to be one of the most common issues in the reader. I have created and added a new label to help identify all such issues.

**Comment by AjayDeshmukh14** [comment]
Yaa that is a better label for this issue, thank you

**Comment by srivasud** [comment]
We have discussed the same issue in https://github.com/mschermann/data_viz_reader/issues/787
I have updated the solution and details in the issue 787.

**Comment by srivasud** [comment]
@AjayDeshmukh14 , Can you please let me know if  I can fix missing graph/broken link in section 6.9.6 as part of issue #787 ?

**Comment by srivasud** [comment]
@AjayDeshmukh14, Never mind. I have removed section 6.9.6 from #787. So you can go ahead with your fix as planned.

**Comment by srivasud** [comment]
You can use the below links:

https://www.forbes.com/sites/naomirobbins/2011/11/17/whats-wrong-with-this-graph/#e0b966b2a336

https://www.forbes.com/sites/naomirobbins/2012/02/28/misleading-graphs-displaying-a-change-in-one-variable-using-area-or-volume/#4392dbb71781
