### ISSUE TITLE
3.7 Reference missing

### ISSUE THREAD

**Issue by strivedi2** [mschermann/data_viz_reader#911]
Missing reference (???) for the article mentioned in the paragraph under section 3.7 Contemporary Research Results & What’s Next in the reader. 

https://github.com/mschermann/data_viz_reader/blob/57964d97c595bb867435b170ee875e66b05856f2/02-fundamentals.Rmd#L574

**Comment by jymhe120** [comment]
Here is the link for the missing reference: https://medium.com/@uwdata/next-steps-for-data-visualization-research-3ef5e1a5e349

**Comment by strivedi2** [comment]
Updated in pull request #1065
