### ISSUE TITLE
6.1 The structure of the section and transition is incongruous

### ISSUE THREAD

**Issue by syragrg** [mschermann/data_viz_reader#912]
Transition from 6 to 6.1 seems like its not the same chapter. In addition, 6.1 is written as a summary of Cairo's article.

**Comment by harizhisham** [comment]
I think the initial purpose of this section was for the reader to read Cairo's article _and then_ read section 6.1. Though, I agree with you that it'll be better if we rewrote the section so that the reader flows better.
