### ISSUE TITLE
Section 5.4 Use of maps not very clear 

### ISSUE THREAD

**Issue by shriya22** [mschermann/data_viz_reader#913]
As maps can be tricky to use, it would be of more help to provide examples of maps for different scenarios. Hence I would suggest to create a subsection and give examples of the good and bad maps 
 
https://towardsdatascience.com/ways-to-improve-a-map-visualization-ba3dc083b3cb
https://blog.stratasan.com/bad-maps-bad-maps

The above 2 link gives clear explanations along with examples .

**Comment by rlwy** [comment]
We can also include an example or two of map visualization to the section.

**Comment by shriya22** [comment]
Content proposal:
This [link]( https://towardsdatascience.com/ways-to-improve-a-map-visualization-ba3dc083b3cb) gives a clear example of when maps are appropriate to use. Even the reader mentioned that maps have to be used only when we are looking for insights based on the geographic locations. The example mentioned below gives a clear illustration of how important maps are when used appropriately
![image](https://cdn-images-1.medium.com/max/1500/1*hMKLq1KDQcnYCMgJScheBA.png)
The above graph doesn't do a good job at illustrating about the profit ratio for each state.
![image](https://cdn-images-1.medium.com/max/1500/1*m6CBCutwN3DVJd4HgpRf5A.png)
But this map does such a better job and the audience understands right away about the condition of each state.


This [link](https://blog.stratasan.com/bad-maps-bad-maps) talks about bad maps and some elaborate tips :
Do not over complicate maps, the audience should not find it hard to interpret the visual.
![image](https://blog.stratasan.com/hs-fs/hubfs/REALLY_Bad.png?width=1050&name=REALLY_Bad.png)
We can see that there are too many things going on and the combination of the colors of reading,writing and earning money is making it even worse. Hence less is more when it comes to maps.
Adding to the above points, it is important to keep maps to the point. Think about how the audience might interpret it, and think of any possible errors and confusions your map might create. 
To give you an example, Consider the below plot where each dot represents 5000 hogs. And the dots are black in color. But the background is also black,hence the audience were confused by this. Even though the information provided was clear, the use of the same color ruined the whole point of the visual.
![image](https://blog.stratasan.com/hs-fs/hubfs/HogFarming.png?width=1050&name=HogFarming.png)


Therefore I would suggest to include these in the reader, as it can give us a clearer idea of why maps are useful and gives some tips on how to use them efficiently.

**Comment by bharatimalik** [comment]
The tips shared are indeed useful. Good addition!

**Comment by shriya22** [comment]
Pull request to add this in the reader has been done and approved hence will be closing this issue
