### ISSUE TITLE
5.8 table formatting missing (line 430)

### ISSUE THREAD

**Issue by harizhisham** [mschermann/data_viz_reader#915]
Table headers are missing borders. Text of body should be top-aligned for easier reading.

**Comment by AjayDeshmukh14** [comment]
I think the table is quite readable and changing it won't be of great use, plus the change to this table style cannot be specific rather the style of all the tables will need to be changed to address this issue

![](https://user-images.githubusercontent.com/49258147/57594708-416dc300-74f6-11e9-9152-f1c8939d14b9.png)

**Comment by rlwy** [comment]
I don't think we can make the text body top-aligned but we can make it left-aligned to match the other tables in the book.
