### ISSUE TITLE
6.9.6 missing graph (line 192)

### ISSUE THREAD

**Issue by harizhisham** [mschermann/data_viz_reader#917]
![image](https://user-images.githubusercontent.com/39789163/55699585-446a1680-5980-11e9-812c-31b6da0d2462.png)

The section is referencing a graph in line 193 ("This one used..."), but is not accompanied by any graph. Would be useful to the reader to have the graph printed out alongside the section rather than have them read text alone.

**Comment by srivasud** [comment]
Hi,
We have discussed the issue in https://github.com/mschermann/data_viz_reader/issues/787.
This is just an information.
Thanks

**Comment by srivasud** [comment]
@harizhisham , Can you please let me know if  I can fix missing graph in section 6.9.6 as part of issue #787 ?

**Comment by srivasud** [comment]
@harizhisham , Never mind. I have removed section 6.9.6 from #787. So you can go ahead with your fix as planned.

**Comment by srivasud** [comment]
Hi,
You can use the below links and also you can embed the graphs as well.

https://www.forbes.com/sites/naomirobbins/2011/11/17/whats-wrong-with-this-graph/#e0b966b2a336

https://www.forbes.com/sites/naomirobbins/2012/02/28/misleading-graphs-displaying-a-change-in-one-variable-using-area-or-volume/#4392dbb71781
