### ISSUE TITLE
5.10.1 citation dead link

### ISSUE THREAD

**Issue by harizhisham** [mschermann/data_viz_reader#920]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/04-patterns.Rmd#L476

The citation is referencing a dead link and needs to be updated.

**Comment by kthang** [comment]
I was unable to find the referenced link.  It seems that the section is question is no longer there.  I will consider this issue closed.
