### ISSUE TITLE
5.2.2 Missing space 

### ISSUE THREAD

**Issue by jymhe120** [mschermann/data_viz_reader#922]
There is a space missing between xor(x,y). The correct format should be x or (x,y). The text does not explain what (x,y) is, which might cause confusion to the readers. 
<img width="668" alt="WeChatf68e76a11af8a9a3ad73ef7df0310bb9" src="https://user-images.githubusercontent.com/35418915/55699995-4fbe4180-5982-11e9-9dcc-afc871d4c885.png">

**Comment by jacksonh2** [comment]
Based on the graph demonstration, we can see that the x or (x,y) means that to select x and y where they don't overlap ( to exclude those overlapped areas). I do agree that with some word explanation it would make this more clear for the readers to understand.
