### ISSUE TITLE
3.5.2.3 incorrect grammar

### ISSUE THREAD

**Issue by harizhisham** [mschermann/data_viz_reader#923]
https://github.com/mschermann/data_viz_reader/blob/26d22854c0c07be1a4af80324e7e10cdb0cf60c9/02-fundamentals.Rmd#L455

Sentence should be "Then **how does** data visualization become..."

**Comment by Vidya313** [comment]
The issue has been marked done in the project folder 'Language and Grammar', hence closing the issue.
