### ISSUE TITLE
2.3.2.2 & 2.6.4.5 Duplicates 

### ISSUE THREAD

**Issue by jymhe120** [mschermann/data_viz_reader#927]
Duplicated contents. 
<img width="667" alt="WeChat3d24df363e5aeb60208169befcc245b6" src="https://user-images.githubusercontent.com/35418915/55701171-01f80800-5987-11e9-9ff5-2404fbe2605e.png">
<img width="663" alt="WeChatbae9c2dbe126458e9b423dc9b5828da4" src="https://user-images.githubusercontent.com/35418915/55701191-15a36e80-5987-11e9-812a-e6782b55f5db.png">

**Comment by jacksonh2** [comment]
Yes, it is redundant to have that visualization in earlier sections and later repeat it. Even though the text are somewhat different, but they still do carry similar meaning and one should be deleted. I have added the duplicate label to this issue.

**Comment by rlwy** [comment]
Issue has been resolved in PR [#962](https://github.com/mschermann/data_viz_reader/pull/962).

**Comment by strivedi2** [comment]
> Issue has been resolved in PR [#962](https://github.com/mschermann/data_viz_reader/pull/962).

Issue has been resolved hence closing it.
