### ISSUE TITLE
2.3.2.3 & 2.6.4.6 Duplicates

### ISSUE THREAD

**Issue by jymhe120** [mschermann/data_viz_reader#928]
Duplicate contents
<img width="674" alt="WeChatccb7bca5bd9bcbd0948d2cd751eb57a6" src="https://user-images.githubusercontent.com/35418915/55701270-66b36280-5987-11e9-8001-4b171ed04560.png">

<img width="666" alt="WeChat76ca221f64992ec23f32a2169955faeb" src="https://user-images.githubusercontent.com/35418915/55701310-8054aa00-5987-11e9-9c84-69ab59d0bcd8.png">

**Comment by strivedi2** [comment]
Closing the issue since it was rectified in pull request #962
