### ISSUE TITLE
4.3.5 Coloring and category clarification needed

### ISSUE THREAD

**Issue by jymhe120** [mschermann/data_viz_reader#929]
This graph is very confusing. Many colors are used in this graph. The color suppose to symbolize each category in the overview section of the graph. For instance, Alcoholic drinks, beverages, and soft drinks are drinks and are colored in blue. Carcase meat and non-carcase meat are meat and are colored in red. Fish are under the fish category. A better way to display this info is to match the color of the each category in the overview section and on the graph. 
Additionally, cupboard and treats are ambiguous categories that needs clarifications. 

<img width="727" alt="WeChat1c4f3512ae258eca79c43eb979a5a7bc" src="https://user-images.githubusercontent.com/35418915/55701587-a0389d80-5988-11e9-8f13-060c32b7426e.png">

**Comment by jymhe120** [comment]
This issue still exists due to a lack of explanation for the cupboard and treats category.  Cannot seem to alter the graph directly with existing data either.

**Comment by mschermann** [comment]
@jymhe120 What is your plan for moving forward?
