### ISSUE TITLE
4.9.5 Graphics clarifications needed

### ISSUE THREAD

**Issue by jymhe120** [mschermann/data_viz_reader#930]
Very interesting graphics but why all the percentages are zero? Does the percentage sign mean the proportion of the specific tree type of each district of NYC or of the whole NYC? Clarifications are needed. 

<img width="728" alt="WeChat6df6b8a908cb071522bc215c64e71a3e" src="https://user-images.githubusercontent.com/35418915/55702538-bdbb3680-598b-11e9-9a2e-2f64b6b54e95.png">

**Comment by jymhe120** [comment]
I double checked the [link](https://www.cloudred.com/labprojects/nyctrees/) and interacted with the graph. Here are the result and clarification. 
![Screen Shot 2019-05-12 at 12 10 46 AM](https://user-images.githubusercontent.com/35418915/57578988-6e649c00-744a-11e9-8a11-83ea22404e27.png)


The original graph included in the reader is static. The percentages are zero because the user hasn't clicked on the trees yet. The percentage represents the proportion of a specific tree for a certain area of NYC. For instance, there are 27474 maple trees among all 101840 trees on Staten Island, which is about 26% of all the street trees. 

After interacting with the graph, all my confusions are resolved. I think this interactive chart is visually appealing and functional. I think we should update the image in the reader with the interacted one and close this issue.

**Comment by Cindyli0310** [comment]
@jymhe120 Hi, very interesting finding,I really like it. And I am totally agree with your idea that we need to update the graph.

**Comment by jacksonh2** [comment]
@jymhe120 , great for finding the clarification! Thou the graph looks impressive by the color and stacked bar,  but it's not really easy to interpret by just looking at it. Not too sure if there's anything we can do to it, but perhaps change the screenshot in the reader to a one with the interaction?

**Comment by JinjinJanelle** [comment]
I like the new graph. Now it has a title and numbers, which helps the audience to have a better understanding of the illustration.
I do not agree with @jacksonh2 about that it is not interpret the graph. I think it is pretty easy to know that each stacked bar represents the nunber of trees in each borough, and the color is corresponding to a specific type of tree. If we add some texts, I think it will actually take the readers more time to read the text content and the graph loses its main purpose.

**Comment by mschermann** [comment]
@jymhe120 What is your plan for moving forward?

**Comment by jymhe120** [comment]
@mschermann  Will update the image in the reader with the interacted one and close this issue this week.

**Comment by jymhe120** [comment]
Updated the original graph. I will close this issue.
