### ISSUE TITLE
4.9.12 Graph hard to read

### ISSUE THREAD

**Issue by jymhe120** [mschermann/data_viz_reader#931]
Two y-axes? What are the unit of the numbers? Why 50 on the left is higher than 51 on the right? 

<img width="778" alt="WeChat56c5194826b0c65dd230d8d62627321d" src="https://user-images.githubusercontent.com/35418915/55703184-d7f61400-598d-11e9-9119-df65eff74d37.png">

**Comment by jacksonh2** [comment]
Hi, I agree that this dual axis can be quite confusing, especially there weren't any labels given. After reading it I think both sides use the same unit, which is age. Is there anything we can do to help label this graph?

**Comment by jymhe120** [comment]
I agree. The unit for both axes is age. Clear label on both axes should help. I also think that the digits are squash to fit the limited space. Maybe stretching the axes more and making sure that 50 is below 51 would be helpful.

**Comment by mschermann** [comment]
@jymhe120 What is your plan for moving forward?
