### ISSUE TITLE
References are missing

### ISSUE THREAD

**Issue by mschermann** [mschermann/data_viz_reader#980]
reference info_viz not found
reference Tufte_Graphical_integrity not found
reference data_journ not found
reference benefits_interactive_viz not found
reference PythonDataVizLibraries not found
reference next_steps not found
reference malaria_zambia_original not found
reference malaria_cases_zambia not found
reference oscars_sowhite_chart not found
reference viz_R not found
reference viz_R not found
reference decept_study not found
reference rose_tint not found
reference mislead_graph_ex not found
reference socialchange not found

**Comment by mschermann** [comment]
Still missing

reference info_viz not found
reference data_journ not found
reference benefits_interactive_viz not found
reference PythonDataVizLibraries not found
reference next_steps not found
reference oscars_sowhite_chart not found
reference viz_R not found
reference decept_study not found
reference rose_tint not found
reference mislead_graph_ex not found

**Comment by mschermann** [comment]
reference Ocean-XRay not found

**Comment by mschermann** [comment]
pandoc-citeproc: reference healthcare_rev not found
pandoc-citeproc: reference rise_of_healthcare not found
pandoc-citeproc: reference media_viz not found
pandoc-citeproc: reference media_entertainment not found

**Comment by pragyansharma24** [comment]
All the missing (???) references are resolved.

**Comment by mschermann** [comment]
reference NarcosNetflix not found
reference data_viz_marketing not found
reference Marketing_Metrics not found
reference types-of-dashboards not found
reference types-of-dashboards not found

**Comment by 82817** [comment]
Fixed reference NarcosNetflix with pull request #1290
