### ISSUE TITLE
5.2 'Tips to Improve Data Visualization' content needs to improve

### ISSUE THREAD

**Issue by Cindyli0310** [mschermann/data_viz_reader#993]
https://github.com/mschermann/data_viz_reader/blob/807bfeb092a95668c952ba8769deaf278ef7d5a5/04-patterns.Rmd#L44

Reader mentioned 7 important elements on improving data visualization, I also think graph integrity is a very important element should be add on, because an overblown or understated message will mislead audience. So graph integrity is very important.

**Comment by mschermann** [comment]
Sounds good. Please create a project and start developing some issues.
